### ISSUE TITLE
Dispatching workflows with `LocalExecutor` fails 

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1009]
### Environment

- **Covalent version**: 0.177.0rc0 
- **Python version**: 3.8.13
- **Operating system**:  CentOS 7, MacOS Monterrey 12.2 (21D49)

### What is happening?

If Dask was previously used, and we use `covalent start --no-cluster`, dispatching a workflow with `LocalExecutor` seems to fail.  Getting the result afterwards seems to throw the error:
`requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://localhost:48008/api/result/SOME_DISPATCH_ID?wait=True&status_only=False`

### How can we reproduce the issue?

1. Start covalent with LocalExecutor: `covalent start --no-cluster`
2. Dispatch the workflow below (or any workflow):
```python
import covalent as ct

@ct.electron
def join_words(a, b):
    return ", ".join([a, b])

@ct.electron
def excitement(a):
    return f"{a}!"

@ct.lattice
def simple_workflow(a, b):
    phrase = join_words(a, b)
    return excitement(phrase)

dispatch_id = ct.dispatch(simple_workflow)("Hello", "World")
print(ct.get_result(dispatch_id, wait=True).result)
```

### What should happen?

Output from workflow should be: `Hello, World!`

**Comment by AlejandroEsquivel** [comment]
from @cjao:
`covalent tries to assign dask as the default executor` and `dask info isn't automatically cleared from the config`

so `covalent purge && covalent start --no-cluster` seems to be the steps to resolve issue

**Comment by AlejandroEsquivel** [comment]
Closed by https://github.com/AgnostiqHQ/covalent/pull/1020

**Comment by cjao** [comment]
Hi @AlejandroEsquivel , I think you linked the wrong PR. #1020 addresses #1019 , not this one (which is still unsolved AFAIK).

**Comment by AlejandroEsquivel** [comment]
Ah gotcha, thanks @cjao

**Comment by AlejandroEsquivel** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Covalent-Open-Source-61a12f9cbea1d7000f1b919b/issues/AgnostiqHQ/covalent/1009?planning-poker) with ZenHub @kessler-frost
