### ISSUE TITLE
`ct.sync`'s interface is not designed for end users

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1026]
The signature for `ct.sync` [has changed](https://github.com/AgnostiqHQ/covalent/blob/d637eabc5ba76446fb65d041cfff0d03dcedc606/covalent/_results_manager/results_manager.py#L243-L245) has changed to accept a `db` parameter. This should be not be exposed to end users, who are [expecting to simply pass a dispatch_id](https://covalent.readthedocs.io/en/latest/how_to/execution/synchronize_lattice.html).

## Acceptance Criteria

- Remove RTD references to ct.sync which is currently only in the how-to guide [Synchronize a lattice](https://covalent.readthedocs.io/en/latest/how_to/execution/synchronize_lattice.html)

**Comment by santoshkumarradha** [comment]
Lets not expose `ct.sync` and remove the how-to. It was intended for very early use.
