### ISSUE TITLE
Sublattices dispatches appear only ephemerally in the UI

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1029]
When I dispatch a workflow that dispatches sublattices, the sublattice dispatches appear in the UI's workflow list only while they are running. They disappear immediately afterwards, regardless of whether the sublattice completes or fails. Here is what I see after running the `vary_distance` workflow in the [quantum chemistry tutorial](https://covalent.readthedocs.io/en/latest/tutorials/quantum_chemistry/nitrogen_copper_interaction.html):

![Screenshot from 2022-08-15 11-26-53.png](https://images.zenhubusercontent.com/61f80f4bba3c01f2d375a8c2/66015252-2335-4dbb-b18b-2725a52ec1fd)

None of the sublattice dispatches appear.

**Comment by cjao** [comment]
@mshkanth

**Comment by Prasy12** [comment]
@cjao  We filter out the lattice values in the db which don't have an electron_id in the lattices table to show on the GUI. I think the reason the sublattice is getting shown when it is on running stage is that the record on the db populates the electron_id field in the lattice table only after the workflow is completed. If there is a way to popluate the electron_id field for the subblattice while the workflow is in the running stage,we can counter this problem.  
 Please let me know if my assumption is wrong.
 
 cc: @mshkanth @santoshkumarradha

**Comment by mshkanth** [comment]
> @mshkanth, @Prasy12

@cjao Thanks for pointing this out. Your expectation was that sub-lattices should always appear on the list. Correct?

**Comment by cjao** [comment]
Hi @Prasy12, 
>If there is a way to popluate the electron_id field for the subblattice while the workflow is in the running stage,we can counter this problem

I think the sublattice electron id is [written to the db immediately after dispatch](https://github.com/AgnostiqHQ/covalent/blob/1feddd96a6428482845cc7fe510f9feb3ca82f56/covalent_dispatcher/_core/execution.py#L299), not after the dispatch has completed.

This of course still leaves a small window during which the sublattice dispatch is running without an `electron_id`. We will likely eliminate this gap in the near future by running the sublattice workflow "internally", without going through an API call. This would allow us to write the sublattice record, complete with `electron_id`, in a single transaction.

**Comment by cjao** [comment]
Hi @mshkanth, yes, sublattices did previously always appear in the list.
