### ISSUE TITLE
Resolve TypeError and ValueError in Bash Lepton Tutorial

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#1031]
### Environment

- **Covalent==0.177.0rc0**
- **Python==3.8.13, 3.9.13, 3.10.4**
- **Ubuntu 18.04, 20.04/ CentOS 7 / Mac OS 12.2 / Fedora 35**

### What is happening?

Cells 3 and 5 in the [Construct Bash Lepton](https://covalent.readthedocs.io/en/latest/how_to/orchestration/construct_bash_task.html) tutorial generate the errors when they are run in a jupyter notebook session.

Cell 3: ``TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given``
Cell 5: ``ValueError: Specify either library_name or command using this language``

### How can we reproduce the issue?

Run cells 3 and 5 in the [Construct Bash Lepton](https://covalent.readthedocs.io/en/latest/how_to/orchestration/construct_bash_task.html) tutorial to reproduce the errors

### What should happen?

All cells in the tutorial are expected to run without errors.

**Comment by cjao** [comment]
I've fixed what I could #1031. I am unable to test the Slack bot example though (don't have a token). At least there are no TypeErrors or ValueErrors.

**Comment by cjao** [comment]
In the future, some documentation would be nice for Bash leptons.

**Comment by cjao** [comment]
The handling of kwargs for bash (like `CPP=gcc` in the tutorial) will need some follow up work. For some reason, all kwargs [are echoed back](https://github.com/AgnostiqHQ/covalent/blob/1feddd96a6428482845cc7fe510f9feb3ca82f56/covalent/_workflow/lepton.py#L322) in the output.
