### ISSUE TITLE
Tutorial references to wait=true may cause 503 http errors

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1033]
## Description

Using `ct.get_result(dispatch_id, wait=True)` in tutorials results in 503 error

## Acceptance Critieria

- Remove the wait keyword argument in order for `get_result` to default to `wait.EXTREME` in tutorials where result may take a while (Refer to https://docs.google.com/document/d/15As8367PrXLXy5R_-0UwmhiVFVpgWHJ7cN3xl7ZOWd8/edit# for tutorials/how-to guides that require updating)

**Comment by kessler-frost** [comment]
I think this PR https://github.com/AgnostiqHQ/covalent/pull/1047 should resolve this issue as well @AlejandroEsquivel.
