### ISSUE TITLE
RTD reference to `ct.wait.LONG` must be removed

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1035]
## Acceptance Criteria

- RTD reference to `ct.wait.LONG` in MNIST Tutorial must be removed

**Comment by venkatBala** [comment]
this must be updated on all tutorials... @scottwn  updated me saying that this has been fixed in v 0.178

**Comment by cjao** [comment]
v0.178 only deconflicts two public "wait" symbols by renaming the wait enum as `WAIT` (I used all caps b/c I thought an enum was basically a constant). According to @scottwn , however, this doesn't quite conform to PEP8 guidelines.

A couple of ways forward:
* Choose a different name for the wait enum or the `ct.wait` function, and use that in the RTD.
* Don't expose the wait enum at all, revert the RTD to `wait=True`, and make `wait=True` equivalent in the backend to `wait.EXTREME`; thus would involve just a [minor adjustment here](https://github.com/AgnostiqHQ/covalent/blob/1feddd96a6428482845cc7fe510f9feb3ca82f56/covalent/_results_manager/results_manager.py#L172). This would be consistent with the original intent of `wait=True`, which according to @wjcunningham7  was to make `get_result()` block until the workflow completes.

**Comment by santoshkumarradha** [comment]
I vote for the last point for now, making long the default and we can work out the UX in the next release if we are planning to expose it. @wjcunningham7
