### ISSUE TITLE
Visualize the lattice how-to guide needs removal

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1036]
How to guide https://covalent.readthedocs.io/en/latest/how_to/orchestration/visualize_lattice.html references draw functionality which is currently not working.

## Acceptance Criteria 

- The Visualize Lattice guide is to be removed until the draw functionality is supported
- Remove reference to `lattice.draw()` in RTD (Astronomy tutorial)

**Comment by santoshkumarradha** [comment]
Waiting to hear back from @Prasy12 if a hotfix can be given for this.

**Comment by Prasy12** [comment]
@AlejandroEsquivel The hotfix for the lattice.draw() will be issued in a few hours time. 
 
cc: @mshkanth
