### ISSUE TITLE
Local executer in RTD API

### ISSUE THREAD

**Issue by santoshkumarradha** [AgnostiqHQ/covalent#106]
### What should we add?

API section is missing the local executer part which includes things like result dir, log std out etc...

**Comment by HaimHorowitzAgnostiq** [comment]
@santoshkumarradha Can you please elaborate on what should be done?

**Comment by santoshkumarradha** [comment]
Hey @HaimHorowitzAgnostiq, indeed. Almost there. Since local executer is not a decorator (i.e not accessed by `@localexecuter`), we dont need the `.. autodecorator::` directive. Instead we just need the autoclave one. But since we also want theinhereted parameters, we need to add `:inherited-members:`
so it would be 

```
.. autoclass:: covalent._workflow.executor.executor_plugins.local.LocalExecutor
    :members:
    :inherited-members:
```

Once this is done, in the PR, you should be able to view the documentation site built from that PR where we can check if everything is indeed okay 👌 .

**Comment by wjcunningham7** [comment]
related to #41

**Comment by FyzHsn** [comment]
@HaimHorowitzAgnostiq Additional subtask to this issue:

Check out the [How to customize the executor](https://covalent.readthedocs.io/en/latest/how_to/execution/choosing_executors.html) and `doc/how_to/index.rst`.

There's some discrepancy here. Fix it.

**Comment by HaimHorowitzAgnostiq** [comment]
@FyzHsn Can you please be more specific on where the discrepancy is?
