### ISSUE TITLE
User to be able to select all & delete all dispatches at once

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#1067]
**Description**
Right now, a user can only select all dispatches that are in view, and then delete them all. 

There is a feature request to 
1. permit a user to select all dispatches beyond what is shown on the page. 
2. permit a user to delete all dispatches (incl ones that are not shown on the view)

Eg - Assume there are 100 dispatches. With a page size of 10, a select all will only select the shown 10 records. The ask is to let them 1. select all 100. 2. Subsequently delete all 100 at once. 

The current delete implementation is shown in the below screenshot with relevant areas highlighted. 
![image](https://user-images.githubusercontent.com/23229840/185066780-20fdab01-ec3b-467f-adeb-67c49b812996.png)

**Requirements**
1. A dropdown mechanism with different options for delete all is set to be included. Attached screenshot for reference. 
![image](https://user-images.githubusercontent.com/54540812/188299090-3bbcc75f-8c5e-4e79-90cf-1255c8218634.png)

2. Once one of the options are selected from the above, a popup bar will be displayed asking confirmation from the user to perform the delete operation. Note that there is no retrieval option and it is a permanent delete on the UI.
3. The options on the dropdown will only show the count that is consistent with the current search & filter query. Eg if there are in total 100 dispatches and only 17 starting with 'Expe'. Then when a user searches for 'Expe', a total of 10 records will be displayed in Page 1 with a total of 17 records. The 'Select all' will only apply to the 17 and not 100. 

**Implementation details**
1. To handle deletion of 100s of dispatches at once, it is proposed for the UI to pass an identifier 'all' directly or indirectly that informs the BE reg the request to delete all dispatches. The BE will respond back with a generic 'acceptance notification' as described above.
5. One edge case to handle might be if any dispatch is running during the moment of the delete all request. In that case, it is preferred to retain the on-going dispatch and only delete non-running dispatches. 

Flow:
https://www.figma.com/file/uob78GrXC0l4iLo6Ux9FJx/OS-UI?node-id=1012%3A32330

**Comment by mshkanth** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Psi-Engineers-6220381c7f976300196f8756/issues/AgnostiqHQ/covalent/1067?planning-poker) with ZenHub @ArunPsiog @Prasy12

**Comment by mshkanth** [comment]
Hi @santoshkumarradha - Pls vet out these details once. Have requested Soc for designs.

**Comment by santoshkumarradha** [comment]
just to add a bit, ideally what we want is kind of "select all" and not just delete all. For instance, once filter is enabled, if a user selects "failed" dispatches and chooses the all tick and clicks select all and then delete it etc..

**Comment by mshkanth** [comment]
> just to add a bit, ideally what we want is kind of "select all" and not just delete all. For instance, once filter is enabled, if a user selects "failed" dispatches and chooses the all tick and clicks select all and then delete it etc..

@santoshkumarradha Pls note that the 'Select all' will only apply to the current searched/queried dispatch list.
`This 'Select all 100 dispatches' will only show the count that is consistent with the current search & filter query. Eg if there are in total 100 dispatches and only 17 starting with 'Expe'. Then when a user searches for 'Expe', a total of 10 records will be displayed in Page 1 with a total of 17 records. The 'Select all' will only apply to the 17 and not 100.`

**Comment by Prasy12** [comment]
@amalanpsiog
