### ISSUE TITLE
Duplicate entries to `user_interface` config entry

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#1068]
### Environment

- **Covalent version**: v0.170.0 (Noticed on this, but should happen across versions)
- **Python version**: 3.9
- **Operating system**: Ubuntu 20.04

### What is happening?

Sometimes, a duplicate entry of `user_interface` gets added to the Covalent config file ( inside `.config/covalent/`). The attributes in this new entry already exist under the original `user_interface` heading. Some attributes written re in-complete words. All this results in an error when Covalent is started. 

### How can we reproduce the issue?

This was observed when running `covalent_ui/app.py` a few times (ie stop, start, stop . . ) along with issuing new workflows and using the UI. An exact pattern of replication has not thus far been observed

### What should happen?

No duplicate `user_interface entry should be added to the config file. If at all there are any updates to the config, the existing config should get updated

**Comment by santoshkumarradha** [comment]
@venkatBala / @FyzHsn this was the bug I was mentioning about config was being modified by the cli.

CC : @wjcunningham7
