### ISSUE TITLE
Terraform & Functional Tests for EC2 Plugin

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1088]
## Acceptance Criteria

- In the corresponding plugin repo (not terraform repo) add a folder `./tests/functional_tests` and add appropriate functional tests for the plugin which should include dispatching a non-trivial workflow as well as validating that various config options are being used as intended

**Note: these are "live" functional tests so no mocking required, also they are not expected to run in the `tests` workflow of the plugin, furthermore they should not use pytest in any manner as they will be invoked using `python`**

**Comment by AlejandroEsquivel** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Covalent-Open-Source-61a12f9cbea1d7000f1b919b/issues/AgnostiqHQ/covalent/1088?planning-poker) with ZenHub @Emmanuel289

**Comment by Emmanuel289** [comment]
@AlejandroEsquivel Does point no 2 mean that we run `terraform init` and provision the required resources that are declared in a `main.tf` file for example?

**Comment by AlejandroEsquivel** [comment]
@Emmanuel289 yes, good point for ec2 as it does it's own provisioning we only really need point 3 which is the functional tests that will be run for ec2
