### ISSUE TITLE
Sublattices on the UI

### ISSUE THREAD

**Issue by ArunPsiog** [AgnostiqHQ/covalent#1097]
Description
A user needs to be able to view the list of sublattices corresponding to the main lattice on the lattice side bar view. 

Requirements

1. By default when the user navigates to the graph view of a lattice, the main lattice graph will be shown on the UI. 
2. A sublattices tab will be introduced on the left lattice side bar which will display the list of all the sublattices that are part of the main dispatch. 
![image](https://user-images.githubusercontent.com/54540812/192936330-c64af16d-dd6e-4323-9414-5dfeb7d53563.png)

3. The user will be able to sort the sublattices by name,runtime and nodes fields in both ascending and descending order. 
4. When a sublattice row is clicked, the graph on the right will be refreshed to show the current subattice graph and the sublattice row on the left lattice side bar will be highlighted to give the user an understanding of what he is currently viewing. 
5. There will be an revert button next to the status on the top for the user to revert back to the main lattice graph. The name of the sublattice will also be displayed along with this. 
6. The user will be only be able to view the sublattices graph when clicked upon and on any other view he will be able to view only the main lattice graph. 
For ex: If a user is currently viewing a sublattice graph and then proceeds to click the overview button, the graph will revert back to original state (main lattice graph).

UI reference :
![image](https://user-images.githubusercontent.com/54540812/192936787-4e4b9d14-c33d-4548-9508-06abef2a45b2.png)

**Comment by Prasy12** [comment]
Edit the issue based on recent discussions. 

cc : @santoshkumarradha @mshkanth
