### ISSUE TITLE
Nested electrons can drag in dependencies on executor plugin packages

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1101]
Users sometimes create workflows where an electron (A) refers to another electron (B). For example, beginners may inadvertently create more electrons than necessary because they are unaware that the electron magic only applies to the top-level functions within a lattice. This could also happen when users are simply experimenting with different ways to modularize their workflows. 

For such workflows, the executor for A will need the executor plugin for B in its environment. Such pip dependency requirements are easy to miss because the executor plugin isn't referred to explicitly in the body of electron A, and the resulting workflow failures can be puzzling.

In the following example, the braket executor for `task_1` wouldn't be able to unpickle `task_1` unless it also has `covalent-ssh-plugin` installed.

```python
from covalent.executor import BraketExecutor, SSHExecutor

braket_exec=BraketExecutor() # params omitted
ssh_exec=SSHExecutor() # params omitted

@ct.electron(executor=braket_exec)
def task_1(x):
    task_2(x)
    #...

@ct.electron(executor=ssh_exec)
def task_2(x):
    pass

@ct.lattice
def workflow(x):
    task_1(x)
    task_2(x)
    #...
```

One way around this is to JSON-serialize the electron constraints in the electron decorator [before passing it to the closure](https://github.com/AgnostiqHQ/covalent/blob/4eb962c4cd7cfc16d1207af0307337a4f6c43168/covalent/_workflow/electron.py#L597) returned by the decorator. Such metadata are presently serialized only after build-graph and before the workflow is sent to the dispatcher; this is too late since any function that refers to an electron will have already acquired a dependency on the electron's executor plugin when it is stored in the transport graph.

**Comment by cjao** [comment]
The following demo now works in the linked PR:

1. `pip install -e covalent-ssh-plugin` (the `requirements.txt` needs to be adjusted to allow newer covalent versions)
2. Serialize a function that refers to an electron with an SSHExecutor executor.
```python
import cloudpickle as pickle
import covalent as ct
from covalent.executor import SSHExecutor

ex = SSHExecutor(username="casey", hostname="beehive.agnostiq.ai", ssh_key_file="~/.id_rsa")

@ct.electron(executor=ex)
def task(x):
    return x

def outer_task(x):
    return task(x)**2

with open("function.pkl", "wb") as f:
    pickle.dump(outer_task, f)
```
3. `pip uninstall covalent-ssh-plugin`
4. Deserialize and run the function without the SSH plugin installed:
```python
import inspect
import pickle

with open("function.pkl", "rb") as f:
    task = pickle.load(f)
    
print(task(3))
```

**Comment by santoshkumarradha** [comment]
@kessler-frost does this also help in the other discussion we had for passing executer before hand while dealing with qiskit plugin?

**Comment by kessler-frost** [comment]
@santoshkumarradha Hmm, I'm not sure.
