### ISSUE TITLE
User to filter dispatch list by status on web app GUI

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#1103]
**Description**
A user needs to be able to filter the dispatch list by the dispatch status by clicking on the short link above the dispatch list

**Requirements**
1. By default, the 'All' filter should be highlighted/selected.
2. If a user selects a status, the dispatch list should get filtered for only that status. However, it should include any sort or search parameters already in play. 
3. If a user searches for a keyword after filtering for a status, they will act in combination ie Both the search & filter will appear. 
4. 'Complete' status includes all post processing states as well. 
5. Besides the current statuses shown (All, Complete, Failed, Running), if it makes sense to add any more statuses (Eg `NEW_OBJECT` , `CANCELLED` etc), it also needs to be added.  

**UI reference**
![image](https://user-images.githubusercontent.com/23229840/185903516-b698cd3c-c05a-44c7-bddc-8d3f82fa1b77.png)

Nice to have - If a user filters by a status and navigates to the graph page, and if he comes back to the dashboard, the filter state should be retained. This ideally needs to be extended to both sort, search & pagination as well.

**Acceptance criteria**
- [ ] Change log has been modified
- [ ] Notion document & RTD has been modified
- [ ] By default, the 'All' filter gets selected
- [ ] When a user selects a status, the dispatch list will show only those dispatches belonging to that status. This will however include any sort or search criteria already added.
- [ ] All post processing statuses are to be treated as 'Complete'
- [ ] State of search, filter & sort is maintained across page navigation

**Comment by mshkanth** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Psi-Engineers-6220381c7f976300196f8756/issues/AgnostiqHQ/covalent/1103?planning-poker) with ZenHub @ArunPsiog @Prasy12

**Comment by ArunPsiog** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Psi-Engineers-6220381c7f976300196f8756/issues/AgnostiqHQ/covalent/1103?planning-poker) with ZenHub @mpvgithub
