### ISSUE TITLE
Remove "\n" and quotes (" ") on inputs and results section on the GUI and show as python strings. 

### ISSUE THREAD

**Issue by Prasy12** [AgnostiqHQ/covalent#1114]
![image.png](https://images.zenhubusercontent.com/62394e2170affc1fe89357a7/1e21ff97-d973-46b2-aefe-490d60905847)

![image.png](https://images.zenhubusercontent.com/62394e2170affc1fe89357a7/415f17e7-2055-40e5-af47-b462682de1ef)

**Comment by santoshkumarradha** [comment]
@Prasy12 is this completed ( i assume so?)
