### ISSUE TITLE
Backend unit tests - Framework & first unit test

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#1115]
**Description** 
Team Psi have started implementing back end  test cases. This issue is more of what approach have been implemented.

**Frameworks** 

1. fastAPI testclient 
2. unittest.mock 
3. pytest 

**FastAPI testclient:** 
Since FastAPI is based on Starlette, TestClient is used for API testing. 

**unittest.mock:** 
unittest will used for functionality test purpose.

**pytest:** 
pytest is used for running and collecting detailed info of passing/failing tests.

**Current Implementation Approach:** 
Currently, unit test case has been initialised for back end.  When test cases gets initiated from pytest, a mock database is created and all API test cases will make use of the test database so that test workflows get populated on the test database. This approach avoids unnecessary workflows getting populated on the actual database.
After the tests are completed, the test database gets deleted automatically.

**Comment by Aravind-psiog** [comment]
@wjcunningham7 FYI, this is the approach that we have initially implemented. Please let us know if there are any comments.
