### ISSUE TITLE
Misc CI Bugs

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#1118]
### Environment

- **Covalent version**: 0.185.0
- **Python version**: 3.8.13
- **Operating system**: Gentoo 2.7

### What is happening?

1. Cannot run tests manually
2. Docker build/push prerelease should be triggered
3. Logs are always dumped in the tests workflow

### How can we reproduce the issue?

N/A

### What should happen?

N/A

### Any suggestions?

1. In tests.yml add curly brakets around line 83
2. In release.yml change lines 295-297 to say
```
inputs.prerelease 
&& inputs.stable_version == '' 
&& github.event_name == 'workflow_call'
```
3. Edit the conditional logic for dumping the logs

**Comment by tinaoberoi** [comment]
Hi @wjcunningham7 I am a new contributor and would like to work on this issue. Let me know if it has to be assigned or I can go ahead and create a PR.

**Comment by FyzHsn** [comment]
> Hi @wjcunningham7 I am a new contributor and would like to work on this issue. Let me know if it has to be assigned or I can go ahead and create a PR.

Hi @tinaoberoi apologies for the late response. First of all, thank you for your interest. This issue is unfortunately outdated and we'll close it. Please feel free to look around and see if there is another issue that interests you. We'd be very happy to assign it to you.
