### ISSUE TITLE
Empty error box shown on the node drawer for SLURM executor workflows

### ISSUE THREAD

**Issue by Prasy12** [AgnostiqHQ/covalent#1120]
![image.png](https://images.zenhubusercontent.com/62394e2170affc1fe89357a7/abb0baa6-c77f-4e83-acbd-55698e055dd7)

**Comment by Prasy12** [comment]
Example file
`from covalent_slurm_plugin import SlurmExecutor
import covalent as ct

executor = SlurmExecutor(
    ssh_key_file="~/.ssh/beehive",
    username="sankalp",
    poll_freq=3,
    address="beehive.agnostiq.ai",
    remote_workdir="/federation/sankalp/workdir",
    options={"partition": "debug", "cpus-per-task": 2, "nodelist": "beehive-debug-st-t2medium-1"},
)


@ct.electron(executor=executor)
def join_words(a, b):
    return ", ".join([a, b])

@ct.electron(executor=executor)
def excitement(a):
    return f"{a}!"

@ct.lattice
def simple_workflow(a, b):
    phrase = join_words(a, b)
    return excitement(phrase)

dispatch_id = ct.dispatch(simple_workflow)("Hello", "World")
print(dispatch_id)`

**Comment by Prasy12** [comment]
@Aravind-psiog Can you take a look at this script and run them in your local and see the output once.

**Comment by arosen93** [comment]
I believe this can be closed.

**Comment by santoshkumarradha** [comment]
Thanks @arosen93 just getting back to closing all old issues !
