### ISSUE TITLE
Updates to BaseExecutor family

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1131]
## Acceptance Criteria

- [ ] Remove `cache_dir` from EXECUTOR_DEFAULTS for `CustomExecutor` and `LocalExecutor` classes
- [ ] Move the following from `BaseExecutor` to `AbstractBaseExecutor`: `cache_dir`, `log_stdout`, and `log_stderr`
- [ ] Add the following attributes to `AbstractBaseExecutor`: `time_limit` and `retries` (Note: these are suitable to implement in every executor plugin.  The retries variable should be defined in the executor rather than the dispatcher, since many (but not all) remote backends accept this retry parameter.)
- [ ] Update docstrings of affected classes 
- [ ] Update unit tests as necessary

**Comment by cjao** [comment]
Hi @AlejandroEsquivel, are there any plans for the (currently broken) conda env code in BaseExecutor? See also #1025.

**Comment by AlejandroEsquivel** [comment]
Closing as duplicate of https://github.com/AgnostiqHQ/covalent-staging/issues/580.
@cjao moving discussion there.
