### ISSUE TITLE
Update config customization notebook

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1153]
### What should we add?

[BUG]

In the Config Customization [notebook](https://covalent.readthedocs.io/en/stable/how_to/config/customization.html), `ct.lattice` decorator is called with an unnecessary parenthesis and `get_metadata` is called without any arguments.

**Comment by madhur-tandon** [comment]
Either the notebook linked is incorrect or has been updated since I cannot find references of both `ct.lattice` OR `get_metadata`. So, this issue can be closed perhaps?
