### ISSUE TITLE
Write the transport graph to the DB atomically

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1162]
When the dispatcher first receives a lattice, it persists the transport graph to the datastore. However, the metadata for the lattice, nodes, and edges are written in [separate DB transactions](https://github.com/AgnostiqHQ/covalent/blob/6ecbd17361d93762a1acb63b82849dfdff035a6e/covalent/_results_manager/result.py#L884). If the Covalent server were to crash in the middle of a `Result.persist()` operation, the DB could be left in an inconsistent state, where only part of a lattice is written. 

To prevent this, we ought to perform all writes that logically belong together in a single transaction.

**Comment by wjcunningham7** [comment]
@cjao is this resolved?

**Comment by cjao** [comment]
Will be fixed by [PR 1495](https://github.com/AgnostiqHQ/covalent/pull/1495).
