### ISSUE TITLE
Update File Transfer concepts / how-to page

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#1182]
### What should we add?

- [ ] References to TransferFrom & TransferTo have to be removed since those functionalities are not working. We get the following error when trying to use them: `AttributeError: module 'covalent._file_transfer' has no attribute 'TransferFrom'`

(Not essential but worth considering)
- [ ] Make the File Transfer section a more abstract discussion.
- [ ] Move the File transfer how-to details in the How-to section
- [ ] When creating the How-to's, it would be beneficial to separate the use cases as much as possible. For example, one how-to section for local file transfers, another for remote file transfers, etc.

**Comment by dwelsch-esi** [comment]
I'm working on rewriting the How-to section. I've split the File Transfer notebook into several different examples: local file transfer; remote transfer to and from; and S3. Will update when complete.
