### ISSUE TITLE
changelog.yml is failing, blocking releases

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#1197]
### Environment

- **Covalent version**: > 0.197.0
- **Python version**: N/A
- **Operating system**: N/A

### What is happening?

See these two runs:
https://github.com/AgnostiqHQ/covalent/actions/runs/3016482600
https://github.com/AgnostiqHQ/covalent/actions/runs/3017070175

### How can we reproduce the issue?

Merge to develop with a change that should trigger a version increment.

### What should happen?

Changelog should be reformatted and version incremeted.

**Comment by scottwn** [comment]
@wjcunningham7 this is probably unrelated, but why are both Ubuntu 18 and Ubuntu 20 `ubuntu-latest`?
https://github.com/AgnostiqHQ/covalent/blob/c73822836e03759a4707d817890f35a41dfa2d7f/.github/workflows/test_matrix.json#L60-L82

**Comment by scottwn** [comment]
per https://github.com/actions/runner/issues/1733 I believe the problem is caused by passing the blob of JSON commits to the action as a var
