### ISSUE TITLE
Deletion of Workflows

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1207]
## Overview

- Move the logic of workflow deletion logic `covalent_ui/api/v1/data_layer/summary_dal.py:delete_dispatches` to a `delete_workfow` function located in covalent dispatcher
- The workflow deletion logic should be reviewed to ensure it is sound and exposed as an API endpoint DELETE `/api/result/:dispatch_id` in covalent_dispatcher that invokes the above method
- A separate `delete` method should be exposed by the SDK that calls the above endpoint 
- Update UI to call the above endpoint

**Comment by kessler-frost** [comment]
Duplicate of #1217
