### ISSUE TITLE
Add an AMI job to release.yml

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#1212]
*Acceptance 

- [x] Get the proposal to modify `release.yml` approved by AQ managers
- [x] The job should build and deploy a new Covalent AMI from `terraform/images`
- [x] The job should only run on a stable release

**Comment by scottwn** [comment]
expect 9-15

**Comment by venkatBala** [comment]
PR: https://github.com/AgnostiqHQ/covalent/pull/1240

**Comment by venkatBala** [comment]
Add a new job aws
* This job should only run after the pypi jobs has finished and uploaded a pkg to pypi
* This job should have the following conditional guards to prevent it from executing on anything other than a stable release
```if: >
      github.event.inputs.stable_version
      && contains(env.PAUL_BLART, github.actor)
      && !github.event.inputs.test_release
```
* aws_ami job has several steps
  * Do a git checkout of the terraform repo
  * Configure the AWS credentials
  * Initialize the packer templates via packer init
  * If successful, validate the templates via packer validate
  * If validation is successful, build the AMI via packer build
  * For all these steps using the hashicorp/packer-github-action@master

**Comment by venkatBala** [comment]
Has been handed off to @wjcunningham7 since the blocker is AWS IAM permissions
