### ISSUE TITLE
Build a Covalent AMI

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#1213]
*Acceptance Criteria*
- [x] Add HCL in `terraform/images` that can be run by Packer to build a Covalent AMI

This may be resolved by https://github.com/AgnostiqHQ/terraform/pull/1, but that PR has many old commits and it may be easier to close it and open a new one.

**Comment by scottwn** [comment]
expect done by 9-14

**Comment by venkatBala** [comment]
Acceptance criteria

- [ ] Update the README.md with details explaining how to build the AMI images manually

- [ ] Add new fields to the AMI tags block

- [ ] Update the logic in the ansible playbook for conditionally building/install covalent

**Comment by venkatBala** [comment]
PR: https://github.com/AgnostiqHQ/terraform/pull/12
