### ISSUE TITLE
Split config into client and server

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#1215]
Consider the existing default config.
https://github.com/AgnostiqHQ/covalent/blob/8095e61dfa5ac44e13fa618727e5b62951ca51c2/covalent/_shared_files/defaults.py#L122-L129

Today, the config is created as a single file in https://github.com/AgnostiqHQ/covalent/blob/8095e61dfa5ac44e13fa618727e5b62951ca51c2/covalent/_shared_files/config.py#L34-L55

In a remote dispatch scenario, the dispatcher will not have access to a config file on a local machine. Dispatcher config should be created as a separate file. 

Add a `config_file` path in `get_default_dispatcher_config()`. Add an argument to the `ConfigManager` constructor to create client config, server config, or both. Alternatively you could create a `DispatcherConfigManager` class that manages just the dispatcher config. 

Server config should include `dispatcher`, `dask`, and `user_interface`.

Related to https://github.com/AgnostiqHQ/covalent/issues/1208

**Comment by scottwn** [comment]
It's important to have these separated out; if we had a situation where Covalent was installed locally and remotely with overlapping configs, the chance of conflicts is very high

**Comment by venkatBala** [comment]
PR that closes this: https://github.com/AgnostiqHQ/covalent/pull/1249

**Comment by venkatBala** [comment]
PR: https://github.com/AgnostiqHQ/covalent/pull/1249
