### ISSUE TITLE
Remove DB dependency from get_all_node_results

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#1223]
*Acceptance Criteria*
- [ ] `get_all_node_results()` in result.py uses API instead of DB to generate the list of results

**Comment by cjao** [comment]
Will there be a separate method that queries `Result.lattice.transport_graph` directly?

**Comment by scottwn** [comment]
I think that would be one way to do it? I was thinking of enhancing the API, so `get_all_node_results` can get the lattice and electron data it needs from the API instead of the DB. But maybe it's easier to get it from the in memory `Result` object?

**Comment by santoshkumarradha** [comment]
Yes I vote for in memory syntax. The goal is for result object, once queried to contain all information presented by methods instead of making costlier http calls as at that point of post queried result space, the users work is scripting in Jupiter notebook for rapid analysis.

**Comment by santoshkumarradha** [comment]
PS: we can backlog an issue to deal with large objects in our optimization releases.
