### ISSUE TITLE
Expose API endpoint for Workflow Cancellation

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1229]
## Acceptance Criteria

- [ ] Allow cancellation of tasks mediated by Local / Dask Executor
- [ ] Expose endpoint to accept a dispatch id to cancel 
- [ ] Add corresponding unit & functional tests as necessary

**Comment by santoshkumarradha** [comment]
@Prasy12 / @mshkanth  can you follow this to see if we can expose in UI as well ?
