### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#1232]
Using this issue to document flaky tests:
- `tests/covalent_tests/executor/init_test.py::test_get_executor_local`

**Comment by rryoung98** [comment]
Hey @wjcunningham7  can you provide a bit more context to these tests?

I would love to get started. Is there a hunch as to what the test results are dependent on (timezone etc).

Is this part of hacktoberfest?

How many tests are flaky?


thanks!

**Comment by AnnaGwen** [comment]
Hi @rryoung98 , this is no longer an active problem that needs to be resolved, but you can find the Hacktoberfest issues [here](https://github.com/AgnostiqHQ/covalent/labels/hacktoberfest), or by searching for issues with the hacktoberfest label.
