### ISSUE TITLE
Corrupted config file

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1235]
### Environment

- **Covalent version**: 0.198.0
- **Python version**: 3.8.13
- **Operating system**: MacOS 12.3.1

### What is happening?

It seems the corrupted config file issue has crept up again. This is most likely due to performing multiple writes from different threads.

### How can we reproduce the issue?

After installing covalent, when I do

```bash
covalent start --ignore-migrations -d
covalent purge -y
```

Then the following error is thrown:
```bash
toml.decoder.TomlDecodeError: Found invalid character in key name: ']'. Try quoting the key name. (line 33 column 16 char 927)
```

This happens even when say a test is run after starting covalent server. So it is rather sporadic, and might be difficult to reproduce.

### What should happen?

No error should be thrown.

### Any suggestions?

I'd say the solution for this would be to not perform any writes whenever the `ConfigManager` is initialized. Instead do it when necessary. Reading however can still be performed.

**Comment by kessler-frost** [comment]
The following sequence of commands might generate the error with more certainty:

```bash
covalent start                                                                # will show warning to run db migrate
covalent db migrate                                                     # might throw a db related error
covalent start --ignore-migrations -d
covalent purge -y                                                         # now this should throw the above error
```

**Comment by AlejandroEsquivel** [comment]
I also found this as well when creating the CI workflow for functional tests, the way to get around this temporarily was to do a sed command to start with debug mode:

`sed -i'' -e "s/log_level/log_level=\"debug\"#/g" ~/.config/covalent/covalent.conf`
`covalent start --ignore-migrations`

instead of 
`covalent start --ignore-migrations -d`

For long term solution requires some investigation,
Could it be that we need a dedicated thread for file i/o operations?

**Comment by cjao** [comment]
What threads are writing the config file besides the main dispatcher thread?

**Comment by Prasy12** [comment]
So when this error throws up, we are actually getting a duplicate sections on the config file. The [user_interface] and the [workflow_data] see to duplicate. 
![image](https://user-images.githubusercontent.com/54540812/190311228-6fea8fea-c964-4ff5-ad5b-dd679441275b.png)

**Comment by cjao** [comment]
At least two processes write to the config:
* The click app
* The actual dispatcher server invoked by `_graceful_start()`

`DaskCluster.run()` also calls `update_config()`, so presumably that would be a third process if covalent is started without `--no-cluster`. However, I see the corruption even with `--no-cluster`.

It looks like within each process only a single thread writes to the config file.

Perhaps try a [multiprocessing lock](https://docs.python.org/3/library/multiprocessing.html#synchronization-between-processes)?
