### ISSUE TITLE
Show a helpful message if trying to dispatch when Covalent is not started

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#1260]
### Description

If you attempt to dispatch when Covalent is not started, you get a trace with a `ConnectionRefusedError: [Errno 61] Connection refused`. For an experienced user, it's obvious this is caused by the dispatcher server not running, but for others it might not be so obvious. We should implement more graceful exception handling, so that the user gets a helpful message like "The Covalent dispatcher server is not running. You must start Covalent before dispatching your workflow."

### Acceptance Criteria
- [x] The `LocalDispatcher.dispatch` method displays a pretty message describing the error.
- [x] The error message appears when a `ConnectionRefusedError` is raised.
- [x] The error message is printed using Covalent's logger, `logger.app_log`, and is raised at the `ERROR` log level.
- [x] A unit test is created in the corresponding test file, `tests/covalent_tests/dispatcher_plugins/local_test.py` (this file does not currently exist). Note that unit tests in the Covalent CI are run _without_ the server running, so any attempt to dispatch a workflow within the unit test should return this error message.

**Comment by rutvikk05** [comment]
Hello, I would like to work on this issue. Could you please assign it to me?

**Comment by wjcunningham7** [comment]
Thanks for participating in Hacktoberfest @rutvikk05!  Looking forward to your contribution :+1:

**Comment by rutvikk05** [comment]
Thanks @wjcunningham7!
I've started working on this, but not sure how to approach the problem. In which file should I make the changes to change the error message?

**Comment by wjcunningham7** [comment]
@rutvikk05 the file you'll want to take a look at is `covalent/_dispatcher_plugins/local.py`.  That will include the classes and methods referenced in the acceptance criteria.

**Comment by rutvikk05** [comment]
@wjcunningham7 I'm trying to reproduce the error in windows 11, but I'm unable to setup covalent. Is it compatible with windows?

**Comment by scottwn** [comment]
Windows is not supported. [Here is the list of supported platforms](https://covalent.readthedocs.io/en/latest/getting_started/compatibility.html).

**Comment by scottwn** [comment]
hey @Aravind-psiog, I no longer have responsibility for issue assignment, @wjcunningham7 can assign the issue

**Comment by Aravind-psiog** [comment]
PR created @scottwn @wjcunningham7 . https://github.com/AgnostiqHQ/covalent/pull/1364. Please let me know if anything has to be done.
