### ISSUE TITLE
Issues in customization.ipynb

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#1261]
### What should we add?

Since the config was split into client config and server config in https://github.com/AgnostiqHQ/covalent/pull/1249, `customization.ipynb` is broken.

The function signatures for `set_config()`, `get_config()`, and `reload_config()` have changed. We'll need to either update the notebook with the new signature, or make the `type` arg optional. @santoshkumarradha should make a call on which approach is better.

The config file updates should also be reflected in the doc. There should be some mention of the difference between covalent.conf and covalentd.conf, and the examples in the doc should reflect the actual structure of these files.

**Comment by AlejandroEsquivel** [comment]
@cjao I think maybe there should be a sensible default for config manager type, and maybe instead of a function arg this could be an environment variable (maybe a commonly used one at some point will be `IS_SERVER={0,1}` @cjao @santoshkumarradha thoughts?

**Comment by cjao** [comment]
In a self-hosted scenario, the client wouldn't be able to directly access the server's config; conversely, "client config" makes no sense from the server's point of view. What about exposing separate `get_config()` and `_get_config()` functions to be used client-side and server-side, respectively, which invoke the current `get_config` with appropriate type?
