### ISSUE TITLE
Ability to copy python objects from the UI for inputs and result files. 

### ISSUE THREAD

**Issue by Prasy12** [AgnostiqHQ/covalent#1263]
Current scenario:

1. The input and results value for both electron and lattice will be shown as a plain string on the GUI.
![image.png](https://images.zenhubusercontent.com/62394e2170affc1fe89357a7/0c70e074-de8b-42bf-ae77-0faa65c89098)

Expectation:

1. The input and results file will now have a copy button next to the string representation. This will allow the users to copy the byte value (python object) corresponding to the input/result in the below format.
`#----- Copied-----
import pickle
import base64
pickle.loads((base64.b64decode(TransportableObject._object.encode("utf-8"))))
`

**Comment by Prasy12** [comment]
cc : @santoshkumarradha

**Comment by santoshkumarradha** [comment]
PS : @Prasy12  if you are anyway using python backend you can potentially simplify this by doing tthis `a=(base64.b64decode(TransportableObject._object.encode("utf-8")))` and copying 
```
import pickle 
pickle.loads("whatever_a_is")
```
as this reduces the complexity a bit more from user side

**Comment by cjao** [comment]
Hi @Prasy12, this is an interesting feature. Would the encoded object be decoded when it is saved to the user's clipboard? If so, in what Python environment would the decoding take place, and how would it be accessed from the web browser?

**Comment by Prasy12** [comment]
@cjao The feature would look something like this.
[screen-capture (29).webm](https://user-images.githubusercontent.com/54540812/192222109-f7c2633a-4375-41dd-8b29-c64c79382970.webm)

We will be giving them a 2 liner when they give a copy button and when they run the decoding will happen. It is just the pure python code and they can run it in any python environment that they desire.

**Comment by santoshkumarradha** [comment]
> @cjao The feature would look something like this. [screen-capture (29).webm](https://user-images.githubusercontent.com/54540812/192222109-f7c2633a-4375-41dd-8b29-c64c79382970.webm)
> 
> We will be giving them a 2 liner when they give a copy button and when they run the decoding will happen. It is just the pure python code and they can run it in any python environment that they desire.

A small correction they can run it on any environment where the dependencies are installed to unpickle it. The expectation is that the ability to unpickle the object is assumed.
