### ISSUE TITLE
Dissolve loop to string join

### ISSUE THREAD

**Issue by boneyag** [AgnostiqHQ/covalent#1278]
### Environment

- **Covalent version**:
- **Python version**:
- **Operating system**:

### What is happening?

This issue is related to the PR [#1270](https://github.com/AgnostiqHQ/covalent/pull/1270).

The file `covalent_ui/api/v1/utils/file_handle.py` uses a loop to concatenate strings. I think `"".join(list_comp)` is a more pythonic way and much faster when the list is very long.
Change: lines 36-38
            list_str = ""
            for obj in unpickled_object:
                list_str += obj
To:
            list_str = "".join([obj for obj in unpickled_object])

### How can we reproduce the issue?

There is no issue here. I am suggesting to use a Pythonic best practice.

### What should happen?

Dissolve the loop to Python API `join()`

### Any suggestions?

Use `"".join(list_comp)` instead of the loop.

**Comment by mohantyrohan3** [comment]
Hey @boneyag Can you please assign the bug to me . I would love to work to resolve the bug

**Comment by boneyag** [comment]
Hi @mohantyrohan3,  
Unfortunately, I do not have the privileges to assign you to this issue as I am a first-time contributor.
