### ISSUE TITLE
Covalent RTD revamp ("Getting Started")

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent#1283]
* Restructure the existing read the docs in a more elegant manner
* Better organize content to enable better user experience
* Review other workflow tools (Dask,rapids)
* Provide template in Notion

**Comment by venkatBala** [comment]
Notion: https://www.notion.so/ReadTheDocs-Revamp-a139a4623ab94fffa836aefe7f5f89ec

**Comment by beckernick** [comment]
Hi! I just came across this project (due to the RAPIDS mention) and it looks great.

Happy to try to help answer questions about RAPIDS and Dask if you have any!

**Comment by venkatBala** [comment]
- [ ] Get RTD revamp notion draft reviewed by owners

- [ ] Restructure existing docs to match the approved revamp

- [ ] assert docs build

**Comment by venkatBala** [comment]
Not relevant any longer
