### ISSUE TITLE
Electrons with unspecified executors do not inherit the Lattice-level executor

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1284]
### Description

Electrons that don't explicitly specify an executor in their decorator should inherit the executor provided in the Lattice decorator. If no executor is provided in the lattice decorator, the electron should use the Covalent default executor ("local" or "dask" depending on whether Covalent is started with `--no-cluster`).

However, this executor inheritance doesn't actually work. Consider the following example:

```python
@ct.electron
def task(x):
    return x

@ct.lattice(executor="awslambda")
def workflow(x):
    return task(x)

workflow.build_graph(1)
```

Since the `task` electron doesn't specify an executor, we expect the Lattice-level executor `awslambda` to apply to that electron. This is not what happens:

```
print(workflow.metadata["executor"])
print(workflow.transport_graph.get_node_value(0, "metadata")["executor"])
```

```
awslambda
local
```

The same problem occurs for other metadata such as `call_before` or `deps`; however, to minimize scope this issue only tracks the propagation of executors from lattices to their electrons. Other metadata can be dealt with similarly in followup issues.

Here are some places to start your debugging:
- The [Electron decorator](https://github.com/AgnostiqHQ/covalent/blob/32929263ab5defc3232f72b8da2c2fe8facf33f9/covalent/_workflow/electron.py#L519) (implements `@ct.electron`)
- [The place where electrons are supposed to inherit lattice-level metadata](https://github.com/AgnostiqHQ/covalent/blob/32929263ab5defc3232f72b8da2c2fe8facf33f9/covalent/_workflow/electron.py#L322).

### Acceptance criteria

- [ ] The Lattice-level executor shall propagate to any electron whose executor is not explicitly set.
- [ ] Any explicit executor setting for an electron shall take precedence over the lattice's setting.
- [ ] Add unit tests checking both of the above two scenarios.

**Comment by RaviPsiog** [comment]
Hi @cjao,
I am working on this issue, and couldn't get clarity on one thing. can you help me clarify that. For this above case, if there's a dispatch with a sublattice, then should the sublattice also get the executor as the parent lattice? **or the electrons alone should inherit the executor and the sublattice executor will be the default?**

Similarly, in the connected issue #1291, Nothing was mentioned about the electrons. In that case, should the electrons also get the executor as the parent lattice? **or the sublattice alone should inherit the executor and the electrons executor will be the default?**

**Comment by cjao** [comment]
Hi @RaviPsiog, thanks for looking into this issue! 

>For this above case, if there's a dispatch with a sublattice, then should the sublattice also get the executor as the parent lattice? or the electrons alone should inherit the executor and the sublattice executor will be the default?

The sublattice should get the parent lattice's executor only if the user did not specify an executor for the sublattice.

>Similarly, in the connected issue https://github.com/AgnostiqHQ/covalent/issues/1291, Nothing was mentioned about the electrons. In that case, should the electrons also get the executor as the parent lattice? or the sublattice alone should inherit the executor and the electrons executor will be the default?

The first behavior is correct. These are split into different issues because they can be addressed independently.

**Comment by RaviPsiog** [comment]
Got it @cjao . Thanks for clarifying the doubt.

**Comment by RaviPsiog** [comment]
Hi @cjao , @wjcunningham7 
I have solved the issue, checked both conditions mentioned, wrote the unit tests, and created PR.
Thanks for providing this opportunity.
