### ISSUE TITLE
Sublattices without explicitly specified executors don't inherit the parent lattice's executor.

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1291]
### Description

When users do not specify an executor in a lattice decorator, the lattice's executor is intended to be automatically set as follows:
- If the lattice is top-level, use the default executor from the Covalent config.
- If the lattice is a sublattice, use its parent lattice's executor.

Consider the following simple lattice consisting of a single sublattice. The top-level lattice's executor is set to `"dask"`, whereas the sublattice's executor is unspecified.
```python
@ct.electron
def task(x):
    return x*x

@ct.electron
@ct.lattice
def subworkflow(x):
    return task(x)

@ct.lattice(executor="dask")
def workflow(x):
    return subworkflow(x)

dispatch_id = ct.dispatch(workflow)(5)
result_object = ct.get_result(dispatch_id, wait=True)
sub_result_object = result_object.lattice.transport_graph.get_node_value(0, "sublattice_result")
```

Since the sublattice does not specify an executor, it should inherit its parent lattice's executor. However, this is not what happens; the sublattice's executor is set to `"local"`, the default executor:

```python
print(result_object.lattice.metadata["executor"])
print(sub_result_object.lattice.metadata["executor"])
```

```
dask
local
```

### Acceptance criteria

- [ ] If a sublattice does not specify an executor, it should inherit its parent lattice's executor.
- [ ] Explicit executor settings for a sublattice shall be honored.
- [ ] If a top-level lattice (not a sublattice) does not specify an executor, it should use the Covalent default executor -- `"local"` if Covalent is started with the `--no-cluster` option and `"dask"` otherwise.
- [ ] Add tests to verify executor settings for lattices and sublattices in all three of the above scenarios.

Some suggestions to start debugging:
- The [lattice decorator](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent/_workflow/lattice.py#L307)
- The server's [internal logic for running sublattices](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent_dispatcher/_core/execution.py#L191); see also `_build_sublattice_graph`.
- The related issue #1284 for automatically setting electron executors.

**Comment by anonymousr007** [comment]
Hello Covalent, 

I am Rishabh Singh, Computer Engineer and Quantum Developer. I am interested in this issue. Skills in Quantum Computing - Qiskit, Pennylane and Cirq. Past contributions - Pennylane, Cirq, and Scikit-Learn.

Best Regards
Rishabh Singh

**Comment by scottwn** [comment]
go for it @anonymousr007! thanks for contributing 😄

**Comment by RaviPsiog** [comment]
Hi @cjao , @scottwn 
I have solved the issue, checked all three conditions mentioned, wrote the unit tests, and created PR. Please let me know if changes to be made.
Thanks for providing this opportunity.

**Comment by scottwn** [comment]
Hey @RaviPsiog, can you link the PR?
