### ISSUE TITLE
Self-Hosted Deployment Guide

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1398]
## Acceptance Criteria

Notes: Check in with @cjao before starting this task

- [x] Add an item in main RTD  side bar containing copy "Deployment"
- [x] Add "Deployment with Docker" section describing how users can pull the image and run covalent locally with docker
- [x] Add "Deployment on AWS" guide outlining the different methods one can run covalent within AWS as well as instructions. (Note: Kubernetes Backend on EKS section outside scope of this issue for now)

See the following for existing work on this issue:

https://github.com/AgnostiqHQ/covalent/pull/1166
https://covalent--1166.org.readthedocs.build/en/1166/deployment.html

Also refer to:

https://github.com/AgnostiqHQ/covalent/issues/1383

**Comment by venkatBala** [comment]
PR: https://github.com/AgnostiqHQ/covalent/pull/1431
