### ISSUE TITLE
Fix MNIST tutorial image

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1422]
@cjao Thank you very much for the detailed reply and explanation! One more thing I wanted to mention is that MNIST tutorial seems to have an incorrect output displayed (likely caused by the issue described above). 
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/71763551/202294565-f0b1b6ff-106b-45a7-8462-8573ec8e077d.png">

_Originally posted by @ineporozhnii in https://github.com/AgnostiqHQ/covalent/issues/1418#issuecomment-1317674035_

**Comment by madhur-tandon** [comment]
@cjao @santoshkumarradha
I guess this is already fixed since https://covalent.readthedocs.io/en/latest/tutorials/0_ClassicalMachineLearning/mnist_images/source.html seems to have the correct image now...see cell 16 in the notebook's HTML

So maybe we can close this...
