### ISSUE TITLE
Unify collection nodes and ordinary nodes

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1428]
# Background

When the Covalent SDK encounters an argument to an electron that is a list, such as 

```
my_electron([1, 2, 3])
```
it first creates a special type of "collection" node in the transport graph to first gather the sequence `1, 2, 3` into a list, and then passes the list as input to the electron. Thus, the above expression is actually decomposed into
```
(1, 2, 3) -> [1, 2, 3] -> my_electron
```
where the first transformation `(1, 2, 3) -> [1, 2, 3]` is done by an [auto-generated](https://github.com/AgnostiqHQ/covalent/blob/f1df14d57761723a4cf0871f8f117a23759f1b39/covalent/_workflow/electron.py#L409) "collection" electron.

The same applies when a dictionary is passed to an electron:
```
my_electron({key: value})
```
is decomposed by Covalent into
```
(key, value) -> {key: value} -> my_electron
```
where the first transformation is accomplished by a [special](https://github.com/AgnostiqHQ/covalent/blob/f1df14d57761723a4cf0871f8f117a23759f1b39/covalent/_workflow/electron.py#L425) collection node.

Unfortunately, because collection nodes try to [use the same auto-generated electron](https://github.com/AgnostiqHQ/covalent/blob/f1df14d57761723a4cf0871f8f117a23759f1b39/covalent/_workflow/electron.py#L651) to process lists and dictionaries, the dispatcher needs to treat collection nodes separately from other electrons and distinguish [whether they are trying to generate a list or dictionary](https://github.com/AgnostiqHQ/covalent/blob/f1df14d57761723a4cf0871f8f117a23759f1b39/covalent_dispatcher/_core/execution.py#L116). The main problem with this approach is that it involves [intermediate pickling](https://github.com/AgnostiqHQ/covalent/blob/f1df14d57761723a4cf0871f8f117a23759f1b39/covalent_dispatcher/_core/execution.py#L133) by the dispatcher, which both incurs needless computation by the dispatcher and tightly couples the dispatcher's Python version to the executor backend's Python version.

# Proposal

It would be better to generate separate electrons for gathering lists and dictionaries. For example, define
```python
def _auto_list_node(*args, **kwargs):
    return list(args)
    
def _auto_dict_node(*args, **kwargs):
    return dict(kwargs)
```
and use the corresponding function for list and dict-type inputs. This would [simplify the dispatcher's logic](https://github.com/AgnostiqHQ/covalent/compare/develop...unify-collection-nodes-exp#diff-a99ca6e887d5a6439efcda540e9e2661cdafa9e3a92109f2ac9c390299f794fbR104) for processing tasks and, more importantly, remove a pickling operation from the dispatcher. With this change, the number of node types would reduce to two: parameter nodes and non-parameter nodes.

**Comment by cjao** [comment]
@kessler-frost

**Comment by kessler-frost** [comment]
Hey @cjao, yeah, I agree with this proposal. Let's do it this way.
