### ISSUE TITLE
Update Dask and Distributed version requirements

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#1538]
### What should we add?

Update the Dask and Distributed versions to avoid getting the following error 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
distributed 2022.9.0 requires tornado<6.2,>=6.0.3, but you have tornado 6.2 which is incompatible.
```

when doing:

```
> conda create -n test python=3.8 -y && conda activate test
> pip install covalent
> pip install notebook
``` 

When installing the requirements via an environment.yml file shown below a runtime error is raised:

```
name: aps_march_covalent
dependencies:
  - python=3.8
  - pip
  - pip:
    - -r requirements.txt
```

This needs to be fixed by choosing the appropriate Dask/Distributed versions.

Note that Conda is able to resolve the dependencies, while pip raises an error.

**Comment by araghukas** [comment]
The following version of dask/distributed is confirmed to solve the issue: `2022.6.0`

Perhaps there is a later verison <`2022.9.0` that also solves the issue.

**Comment by araghukas** [comment]
Regarding conda, this also works:

```bash
 conda create -n test_env python=3.8 -y && conda activate test_env
 pip install covalent
 conda install -c anaconda jupyter -y
 conda install nb_conda -y
```

in this case, it installs `dask==2022.9.0`, `distributed==2022.9.0` and `tornado==6.1`
