### ISSUE TITLE
Failing functional tests in CI pipeline

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1540]
### Environment

- **Covalent version**: 0.219.0-rc.0
- **Python version**: 3.8.14
- **Operating system**: Ubuntu 20.04

### What is happening?

Functional tests for How To guides are failing.

### How can we reproduce the issue?

In the CI pipeline the How To functional tests have been failing recently. We should be able to reproduce it locally with `pytest`. One example run of these failed tests: https://github.com/AgnostiqHQ/covalent/actions/runs/4324808464/jobs/7550126950

### What should happen?

Functional tests should pass.

**Comment by madhur-tandon** [comment]
I cannot reproduce this + the CI passes on `develop` branch as well, maybe this should be closed?

**Comment by madhur-tandon** [comment]
@kessler-frost We can close this!
