### ISSUE TITLE
Reduce memory consumption when running workflows

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#1544]
For background, check [here](https://www.notion.so/Reduce-memory-consumption-when-running-workflows-5bf8043e72f041c7ae40b941daf55de1).

**Comment by santoshkumarradha** [comment]
https://github.com/AgnostiqHQ/covalent/pull/1728
https://github.com/AgnostiqHQ/covalent/pull/1729
https://github.com/AgnostiqHQ/covalent/pull/1690
