### ISSUE TITLE
Hook up the new runner to the cancel method

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#1553]

**Comment by FyzHsn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Covalent-Open-Source-61a12f9cbea1d7000f1b919b/issues/AgnostiqHQ/covalent/1553?planning-poker) with Zenhub @AlejandroEsquivel @cjao @kessler-frost

**Comment by santoshkumarradha** [comment]
@kessler-frost / @cjao assume all the improvements/memory tag issues can be closed now? If so @kessler-frost can you please close them ? 🙏
