### ISSUE TITLE
Electron metadata

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#1569]

**Comment by Prasy12** [comment]
Figma reference : 
https://www.figma.com/file/uob78GrXC0l4iLo6Ux9FJx/OS-UI?type=design&node-id=3419-41741&t=UHAUOSb25z0taFan-0#450523480

**Comment by Prasy12** [comment]
@arosen93 This was a different feature we were working on and might not be related to the issue that you have created. This was a placeholder for another feature we are planning. Hence, closing this and that issue you have linked can be tracked separetly.
