### ISSUE TITLE
There are a few dead links in the docs (and other minor issues)

### ISSUE THREAD

**Issue by arosen93** [AgnostiqHQ/covalent#1585]
A few suggestions for docs cleanup:

1. Some of the "See Also" links in the how-to guide are dead. See click "Constructing a Sublattice" on the bottom of [this page](https://covalent.readthedocs.io/en/latest/how_to/coding/add_electron_to_lattice.html) or "Transferring Remote Files During Workflows" on [this page](https://covalent.readthedocs.io/en/latest/how_to/coding/file_transfers_for_workflows_local.html).
2. There are empty Jupyter cells at the bottom of some how-to pages, such as [here](https://covalent.readthedocs.io/en/latest/how_to/coding/visualize_lattice.html) or [here](https://covalent.readthedocs.io/en/latest/how_to/coding/file_transfers_for_workflows_local.html).
3. There are some misformatted docstrings [here](https://covalent.readthedocs.io/en/latest/api/electrons.html). See "it is bound to a graph node."
4. Some of the tutorial pages have no title in the browser window, such as [here](https://covalent.readthedocs.io/en/latest/tutorials/1_QuantumMachineLearning/pennylane_iris_classification/source.html) or odd ones as shown [here](https://covalent.readthedocs.io/en/latest/tutorials/1_QuantumMachineLearning/pennylane_parity_classifier/source.html), due to a lack of proper markdown formatting in the headers.

Some typos:
- [here](https://covalent.readthedocs.io/en/latest/api/data_transfers.html#basic-file-transfer-interface). See "are are".
- [here](https://covalent.readthedocs.io/en/latest/how_to/execution/creating_custom_executors.html?highlight=postprocess). See "abackend"
- "nay" is used a few times instead of "any", as shown [here](https://covalent.readthedocs.io/en/latest/search.html?q=nay&check_keywords=yes&area=default)

**Comment by kessler-frost** [comment]
Addressing these in #1588
