### ISSUE TITLE
On-the-fly modification of the electron executors in a lattice

### ISSUE THREAD

**Issue by arosen93** [AgnostiqHQ/covalent#1587]
### What should we add?

It'd be great to have some utility function that is part of the `Lattice` object where the executors of the underlying electrons could be modified on-the-fly; something like `Lattice.set_electron_executors(["local", "slurm"])`, which would update the executors of electron 1 and 2 in a 2-electron lattice to "local" and "slurm," respectively. It's clear from the docs that you could set the executor of the lattice decorator, but this will apply a single executor type to _all_ electrons in the lattice.

For an example of this challenge to be addressed, consider the following electrons:

```python3
@ct.electron
def add(val1, val2):
    return val1 + val2

@ct.electron
def multiply(val1, val2):
    return val1 * val2
```

The user's lattice might look something like this:

```python3
@ct.lattice
def latt(val1, val2):
    out1 = add(val1, val2)
    out2 = multiply(out1, val2)
    return out2
```

If I want to update the individual electron executors, I can of course set the executor kwarg in the electron decorators. But let's say these functions are used over and over again and are imported in a given user's workflow. The user doesn't want to touch the electrons as they are defined. If the user only wants to modify the executor of one electron in the lattice without touching the original definitions (or perhaps modify the executor of multiple electrons but with different executors in each case), it does not seem that there is a clear mechanism for doing this. This is going to come up for users who are building software packages around covalent where they are defining a curated set of electrons for users to import and use in their custom-defined lattices.

### Describe alternatives you've considered.

I tried using a class-based approach as shown in #1586, but that presented its own challenges and is quite clunky.

**Comment by cjao** [comment]
Hi @arosen93 , thanks for raising the issue! An alternate pattern which might help in your use case is to first define `add` and `multiply` as regular python functions and then apply the `ct.electron` decorator "on the fly" with different executors as needed. For instance:
```python3

def add(x, y):
    return x + y

def mult(x, y):
    return x * y

@ct.lattice
def workflow(x, y):
    x1 = ct.electron(add, executor="local")(x, y)
    y1 = ct.electron(mult, executor="dask")(x, y)
    return ct.electron(mult, executor="local")(x1, y1)
```
This results in the following compute graph:
![image](https://user-images.githubusercontent.com/15801897/233524056-2c497b6a-c9d9-4709-b735-3d3cbf6e89eb.png)




We demonstrate a similar pattern in the [MNIST tutorial](https://covalent.readthedocs.io/en/latest/tutorials/0_ClassicalMachineLearning/mnist_images/source.html) (see Cell 13).

**Comment by cjao** [comment]
Nvmd I see that @santoshkumarradha has given a much more comprehensive response in #1586 !.
