### ISSUE TITLE
Fixes in How To guides

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1588]
There are some how to guides which require several small changes for broken links, etc. This issue will track progress of fixing those issues.

**Comment by kessler-frost** [comment]
Thanks a lot @arosen93 ! I went through your issue related to these as well and will soon be taking care of them in a PR 😄 . And yes `results_dir` in the lattice decorator function is a remnant of deprecated code, will fix the documentation 👍 .

**Comment by arosen93** [comment]
Sounds great :) Thanks!
