### ISSUE TITLE
Add macOS 13 (Ventura) to compatibility overview

### ISSUE THREAD

**Issue by RCdeWit** [AgnostiqHQ/covalent#1590]
### What should we add?

I ran into an issue with `pip install covalent` because my environment used Python 3.11. After looking at the [Compatibility](https://github.com/AgnostiqHQ/covalent/blob/develop/doc/source/getting_started/compatibility.rst) page, I noticed that 3.11 wasn't listed as a supported version for earlier macOS versions.

My suggestion would be to add the latest macOS version (13, Ventura) to the compatibility overview.

Additionally, might it be a good idea to add Python 3.11 as "not currently supported"?

**Comment by madhur-tandon** [comment]
@santoshkumarradha you might wanna close this as well...
