### ISSUE TITLE
Hanging UI at dispatch-id `this-id-doesnt-exist`

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1603]
There is an harmless but unnecessary dispatch id existing in the UI code which when visited just shows a blank UI page with no details. We should remove this special case if it's not needed anymore. It look something like this:

![image.png](https://images.zenhubusercontent.com/61a508f4b0eb9f4075385c2a/98b23b70-65ac-44f7-8f90-f46f05ad1417)

**Comment by santoshkumarradha** [comment]
@Prasy12 is this a front end test ID ?

**Comment by Prasy12** [comment]
@santoshkumarradha We don't have any test-ids in OS. 
@kessler-frost  Can you let me know the steps to recreate this?

cc : @RaviPsiog

**Comment by kessler-frost** [comment]
@Prasy12 after starting up covalent if we go to `http://localhost:48008/this-id-doesnt-exist` we see this page.

**Comment by Prasy12** [comment]
Is it been shown in the list of dispatches in the dashboard page?

**Comment by Prasy12** [comment]
And can you try any other random text? Something like 
http://localhost:48008/abcd and see if you're getting the same error?
@kessler-frost

**Comment by kessler-frost** [comment]
It's not. It's only if we go to this url precisely.

**Comment by Prasy12** [comment]
Okay we will check @kessler-frost

**Comment by kessler-frost** [comment]
Oh, actually you're right, it is the case with any other random url as well, I see the same page.

**Comment by Prasy12** [comment]
@RaviPsiog Can you validate this when you find time? TIA!

**Comment by Prasy12** [comment]
@Kamalesh-suresh Please take a look at this.
