### ISSUE TITLE
Update SLURM plugin instructions

### ISSUE THREAD

**Issue by arosen93** [AgnostiqHQ/covalent#1615]
### What should we add?

The SLURM plugin instructions have been updated [here](https://github.com/AgnostiqHQ/covalent-slurm-plugin/pull/53). The RTD instructions should be updated to match. I'll submit a PR.

**Comment by santoshkumarradha** [comment]
Lets keep this open past https://github.com/AgnostiqHQ/covalent/pull/1616, there seems to be another updated to RTD from https://github.com/AgnostiqHQ/covalent-slurm-plugin/pull/52

**Comment by arosen93** [comment]
Since the plugin docs are now merged, the sshproxy instructions now just have to be updated in the RTD.
