### ISSUE TITLE
Working directory is not appropriate for local executors

### ISSUE THREAD

**Issue by arosen93** [AgnostiqHQ/covalent#1619]
### Environment

- **Covalent version**: 0.220.0
- **Python version**: 3.9
- **Operating system**: Ubuntu

### What is happening?

By default, the working directory for a local or Dask-executed Lattice is the Python package folder for the Covalent UI (e.g. `~/anaconda3/envs/covalent/lib/python3.9/site-packages/covalent_ui`). This is problematic for several reasons, in part because this is not an expected location for the user. Also, the filesystem where the Python package is installed may not always be the fastest for large file I/O that might happen at runtime.

Note: I brought this up in #1592 but now have made a standalone issue for it.

### How can we reproduce the issue?

```python3
import covalent as ct
import os

@ct.electron
def job(val1, val2):
    with open("job.txt", "w") as w:
        w.write(str(val1 + val2))
    return "Done!"

@ct.lattice
def workflow(val1, val2, val3, val4):
    job1 = job(val1, val2)
    job2 = job(val3, val4)
    return "Done!"

dispatch_id = ct.dispatch(workflow)(1, 2, 3, 4)
result = ct.get_result(dispatch_id)
print(result)
```

### What should happen?

The `job.txt` files should not be written in the `...covalent/lib/python3.9/site-packages/covalent_ui` path, but it is. This is just a demo of the issue, not an actual use case. Also, the file from each electron overwrite one another (but that problem is discussed in #1592). 

### Any suggestions?

1. For the executors that run locally, change the default working directory to be in a more logical location than the Covalent UI folder where Covalent was installed.
2. As a rule, allow for user modification of the current working directory in all executors as a configuration variable. In the SLURM executor, this can already be modified by the `remote_workdir` variable, but a similar `workdir` argument is not available for the local and Dask executors and should be added.

**Comment by madhur-tandon** [comment]
I can verify this issue.
This is basically happening because the `FastAPI` app is being served from `covalent_ui`.

**Comment by wjcunningham7** [comment]
In most other executors, we use containerization so this problem wouldn't arise -- it should be isolated to Local and Dask executors.  We could leverage something existing like `dispatcher.results_dir` although files there really shouldn't be touched by the user.  It might be appropriate to introduce a new `workdir` directory for these two executors as suggested by @arosen93.  Any comments on UX @santoshkumarradha?

**Comment by madhur-tandon** [comment]
@wjcunningham7 Can I work on this perhaps? Your thoughts resonate with me, `dispatcher.results_dir` basically contains many `.pkl` and `.log` files, which should ideally be separate from user intended output.

**Comment by arosen93** [comment]
While I can't speak for @wjcunningham7 of course, I would certainly appreciate your help on this one :)
