### ISSUE TITLE
No UI after starting covalent (pip editable mode)

### ISSUE THREAD

**Issue by kinow** [AgnostiqHQ/covalent#1629]
### Environment

- **Covalent version**: 5172f98c8b967f15364a2f6c35d47294eff4ba7b in editable mode
- **Python version**: 3.10.6
- **Operating system**:ubuntu LTS 22.04.1

### What is happening?

I started following the quick start, but using `pip install -e .` to install covalent, and then `covalent start`.

Upon starting covalent, I get the message 

```bash
(venv) kinow@ranma:~/Development/python/workspace/covalent$ covalent start
Covalent server has started at http://localhost:48008
```

Visiting that page I get a web page with the text `Not Found`.

After that I run a workflow as in "3. Run a workflow.", but then when I try to visit the UI as in "4. View the workflow progress.", I still get the Not Found, instead of seeing my workflow in the queue as in the screenshots of the docs https://covalent.readthedocs.io/en/latest/getting_started/quick_start/index.html

### How can we reproduce the issue?

Follow the quick start with the latest version.

### What should happen?

Same as when using the non-editable version.

### Any suggestions?

Or, we could have a note somewhere in the documentation explaining that the quick start only works for the latest PyPI release, and not the latest code with editable version.

**Comment by santoshkumarradha** [comment]
Hey @kinow, just wanted to give you a heads up: if you choose to install in `pip` editable mode, keep in mind that the UI won't be automatically built. You'll need to build the UI yourself by following the instructions provided [here](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent_ui/README.md). Once you've got that done, everything should run smoothly.

Hi @Prasy12, I hope you're doing well. I just wanted to point out that the contributing guide might be missing some steps when it comes to building the UI while developing. Do you think it would be possible to add a few steps from the UI's Readme to the contributing guide? I would really appreciate your help with this. Thank you so much in advance!

**Comment by kinow** [comment]
Thank you @santoshkumarradha !!!

**Comment by arosen93** [comment]
I get the same behavior when pip install-ing from a branch rather than via PyPI. Good to know how to fix it though.
