### ISSUE TITLE
Add source link to example notebooks

### ISSUE THREAD

**Issue by janosh** [AgnostiqHQ/covalent#1661]
### What should we add?

Would be great to have a link (maybe in the form of a GitHub icon) at the top of example notebooks to quickly open and/or download them on GitHub:

![Screenshot 2023-05-22 at 17 50 42](https://github.com/AgnostiqHQ/covalent/assets/30958850/fd160152-97dc-4fd7-b4db-41fa9f0b3016)

The current edit icon prompts me to fork the repo which I assume will repel many users. It's a simple change of URL but most wil be unaware so maybe have two buttons, one to edit, one to open:
```diff
- https://github.com/AgnostiqHQ/covalent/edit/develop/doc/source/tutorials/3_QuantumChemistry/dynamic_quantum_chemistry/source.ipynb
+ https://github.com/AgnostiqHQ/covalent/blob/develop/doc/source/tutorials/3_QuantumChemistry/dynamic_quantum_chemistry/source.ipynb
```

**Comment by arosen93** [comment]
A little birdy told me this won't be a relevant issue in the upcoming new version of the docs 👀
