### ISSUE TITLE
Python stalls when importing covalent on Perlmutter, likely due to issue with locking mechanism on the config

### ISSUE THREAD

**Issue by arosen93** [AgnostiqHQ/covalent#1697]
### Environment

- **Covalent version**: 0.220.0 or 0.256.0-rc.0
- **Python version**: 3.9 or 3.10
- **Operating system**: Linux (SUSE Linux Enterprise Server 12 SP2)

### What is happening?

Through a very specific set of circumstances, Python simply hangs upon importing Covalent, likely due to issues with a locked config. I describe the _precise_ steps needed to reproduce this issue and what my hunch is.

Tagging @wjcunningham7 and @santoshkumarradha who I discussed a very related issue with weeks ago that I thought was due to the pickling process but is likely entirely independent of that after further investigation.

### How can we reproduce the issue?

Note that I am doing this on the Perlmutter HPC machine by NERSC in my `/pscratch/sd/r/MyUserName` directory, for the sake of full reproducibility.

0. Start with a clean slate, i.e. temporarily remove `~/.config/covalent` and `~/.local/share/covalent`
1. Install Miniconda locally
2. With Miniconda accessible in your bash environment, run `conda create --name test python=3.9`
3. Run `conda activate test`
4. Run `pip install covalent` in your `test` environment
5. In a Python console on the head node, run `import covalent`. Note that it imports just fine. Exit the Python console.
6. Submit the Slurm job (see below) via `sbatch job.sh`, which runs `test.py` (see below)
7. Note that it just hangs.......
9. While the job is stalled or after you `scancel` it, open up a Python console on the head node again and try `import covalent` again. Note that Python stalls on the head node now as well. Trying to do `import covalent` doesn't work anywhere for that matter anymore.

The `test.py` file contains:

```python
import covalent

print("hi")
```

The `job.sh` file contains:

```
#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --qos=debug
#SBATCH --time=00:10:00
#SBATCH --account=YourAccountName
#SBATCH --job-name=debug
#SBATCH --output=debug-%j.out
#SBATCH --error=debug-%j.error
#SBATCH --constraint=cpu

conda activate test
export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=1

python test.py>test.out
```
### What should happen?

Covalent should not hang.

### Any suggestions?

I am nearly certain this has to do with the config file locking mechanism. If at the end of the above steps you run `rm -r ~/.config/covalent` and then run `import covalent` again in a Python console on the head node, then Python does not hang anymore.

Hitting Ctrl+C while it's hanging yields the following traceback, further supporting this:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/r/rosen/software/miniconda/envs/test/lib/python3.9/site-packages/covalent/__init__.py", line 26, in <module>
    from . import executor, leptons  # nopycln: import
  File "/global/homes/r/rosen/software/miniconda/envs/test/lib/python3.9/site-packages/covalent/executor/__init__.py", line 33, in <module>
    from .._shared_files import logger
  File "/global/homes/r/rosen/software/miniconda/envs/test/lib/python3.9/site-packages/covalent/_shared_files/logger.py", line 34, in <module>
    log_level = get_config("sdk.log_level").upper()
  File "/global/homes/r/rosen/software/miniconda/envs/test/lib/python3.9/site-packages/covalent/_shared_files/config.py", line 247, in get_config
    cm = ConfigManager()
  File "/global/homes/r/rosen/software/miniconda/envs/test/lib/python3.9/site-packages/covalent/_shared_files/config.py", line 55, in __init__
    self.update_config()
  File "/global/homes/r/rosen/software/miniconda/envs/test/lib/python3.9/site-packages/covalent/_shared_files/config.py", line 117, in update_config
    fcntl.lockf(f, fcntl.LOCK_EX)
```

**Comment by santoshkumarradha** [comment]
Interesting ! We actually do manual tests for config corruption. 

@kessler-frost / @AlejandroEsquivel can you take a look at this ?

**Comment by kessler-frost** [comment]
Hey @arosen93 ! Unfortunately, even after multiple tries, I wasn't able to reproduce this issue locally (i.e. w/o slurm) on my end 🤔 . I have a suspicion that it might have to do with using `fcntl` on an NFS (which I thought you might be using according to the `"/global/homes/r/rosen/..."` dir structure). Related SO: https://stackoverflow.com/questions/48770531/how-to-do-proper-file-locking-on-nfs.

Have you been able to locally reproduce it? That would make it even more interesting o.O. The machine I tried on is an Ubuntu 20.04, and I repeated the exact same steps as you mentioned, except the slurm job submission part, I instead ran this `python test.py>test.out` in a bash script.

**Comment by arosen93** [comment]
@kessler-frost: I have a small update.

I ran the exact same steps but from my home directory rather than the scratch directory. As before, I got the same stalling issue where the Slurm job does not complete the import process (and locks the config during this). I only observe this behavior when the Slurm job is submitted (I removed the bash export commands in the Slurm script too). Running on the Covalent import on the head node causes no issues.

Sadly, I'm not able to get any more specifics than this (except that it's not a temporary issue --- I ran into the same problem a month ago but thought it was due to something ese).

If it might help, I would be happy to hop on a Zoom call to debug remotely if it might help pinpoint the problem. Otherwise, please let me know if there is anything else I can/should do to provide more useful information for you. I wish I had more details I could provide!

**Comment by kessler-frost** [comment]
@arosen93 One thing you can try if you're not too worried about what the config is, is that you can try changing the config directory in the slurm script using `os.environ.set("COVALENT_CONFIG_DIR", "something/else")` - basically changing the `COVALENT_CONFIG_DIR` environment variable, since that's the first thing covalent checks, whether it exists or not and creates the config file there if it does, whenever imported. This way it should create a new config file and ideally shouldn't get deadlocked. Although I do understand this is not an ideal solution but lmk if that helps.

**Comment by arosen93** [comment]
@kessler-frost: Another update.

I took your suggestion and defined `COVALENT_CONFIG_DIR` in the Slurm script before anything is run. In doing so, there is no hanging and everything closes gracefully. Of course, this isn't really a long-term solution as you noted, but it does confirm your suspicion about what is happening at a high-level and does offer a potential (if somewhat inconvenient) workaround.

I am going to keep the issue open because I think it is still important for this to get resolved "for real." Longer term, I think there is also some value in considering a different mechanism because if Covalent switches to a different locking scheme that is OS-agnostic, then it is actually quite trivial for Covalent workflows to run on Windows as a completely unrelated side benefit.

**Comment by santoshkumarradha** [comment]
Thanks for trying it out @arosen93 ! I agree, this is not a fix, based on this exp we have atleast narrowed down the problem. It should be quite trivial to have a OS agnostic lock mechanism, there are quite a few libraries that does this as well. We will definitely tackle this.

**Comment by arosen93** [comment]
Sounds great to me! As always, happy to test things out whenever the time comes. 👍 Thanks, all, for the help with digging into this!

**Comment by arosen93** [comment]
@wjcunningham7, @kessler-frost:

I found this message on the NERSC slack:
```
> I'm experiencing some issues with the filelock Python package; I can no longer acquire file locks on Perlmutter. Is this related to the DVS filesystem change? I seem to recall on Cori, there was some issue related to file locking and the HDF5 package https://docs.nersc.gov/development/languages/python/parallel-python/#parallel-io-with-h5py, also related to DVS.

> Yes, DVS doesn’t support file locking unfortuantely. You should be able to use this on Perlmutter scratch though
```

This suggests to me that this Perlmutter-specific issue may be because my config, by default, was stored in my `~/` directory. When switching the `COVALENT_CONFIG_DIR` to the scratch directory, jobs don't seem to stall even when the config file is already present. One downside of this is that a config stored in scratch means you have to `touch` it regularly or it gets lost, but that's a side-comment. I'll continue trying this and see if I am understanding it correctly.

**Comment by kessler-frost** [comment]
Thanks @arosen93 🤘!

**Comment by tylern4** [comment]
I was working with @arosen93 this morning and we trigged a bug on Perlmutter when loading in covalent. I checked though the code and it seems to be file locking causing the issue and triggering the bug. 

It looks like in `ConfigManger` you are opening a file to read the configs and [locking](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent/_shared_files/config.py#L112) the file. Then in the same context you try to [write](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent/_shared_files/config.py#L121) the config file which [locks the file again](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent/_shared_files/config.py#L146). Gaining the lock on the file that has already been locked by the same process seems to confuse and freeze the filesystem mounted with [DVS](https://docs.nersc.gov/performance/io/dvs/#data-virtualization-service-dvs).

**Comment by kessler-frost** [comment]
Thanks a lot for looking into this @tylern4 !

**Comment by kessler-frost** [comment]
Thanks to @tylern4 's PR I have closed this issue. If this issue arises again, we can reopen this.
