### ISSUE TITLE
'conda activate' lines generated in slurm script even if conda_env is set to None

### ISSUE THREAD

**Issue by JackSleuters** [AgnostiqHQ/covalent#1755]
### Environment

- **Covalent version**: Release version 0.220.0
- **Python version**: Python 3.9.5
- **Operating system**: Ubuntu 20.04.6 LTS
- **Slurm plugin:  0.12.1

### What is happening?

When using a slurm executor, the generated slurm-dispatchId.sh file always includes lines for conda although one has specified conda_env=None.

### How can we reproduce the issue?

Have a look at the code of slurm.py:

lines 395 and 396:
```
# assemble script
return "".join([slurm_preamble, slurm_conda, slurm_python_version, slurm_body])
```

This is where the slurm-<dispatchId>.sh script is created. Then I looked at the 'slurm_conda' string in line 337-346:

```
# sets up conda environment
        slurm_conda = f"""
source $HOME/.bashrc
conda activate {conda_env_str}
retval=$?
if [ $retval -ne 0 ] ; then
  >&2 echo "Conda environment {conda_env_str} is not present on the compute node. "\
  "Please create the environment and try again."
  exit 99
fi

"""
```

It seems that the conda lines are generated independent of 'conda_env_str' having the value "". I think that if 'conda_env_str = ""' the conda lines should not be generated. 

### What should happen?

When conda_env=None or conda_env="" no lines related to conda environment should be generated in the slurm-dispatchid.sh scripts.

**Comment by arosen93** [comment]
@JackSleuters: Could you try it with `pip install covalent-slurm-plugin --pre` to install the [v0.16.0 pre-release](https://github.com/AgnostiqHQ/covalent-slurm-plugin/releases)? It's likely that my PR here https://github.com/AgnostiqHQ/covalent-slurm-plugin/pull/61 fixed the issue. If you still get the error, let me know and I can debug.

Tagging @wjcunningham7. If this does fix the issue, it's probably worth minting a new "regular" release to avoid confusion.

**Comment by JackSleuters** [comment]
Dear Andrew,

I tried pip install covalent-slurm-plugin –pre in my covalent_pre virtual environment. However, I get a build erron in ‘Building wheel for aiohttp (setup.py)…
I’m using python 3.9.5. Any ideas?

Kind regards,
Jack

Building wheels for collected packages: aiohttp, multidict
  Building wheel for aiohttp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/username/covalent/covalent_pre/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tcicr_n2/aiohttp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tcicr_n2/aiohttp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-elsqdh63
       cwd: /tmp/pip-install-tcicr_n2/aiohttp/
  Complete output (9 lines):
  **********************
  * Accellerated build *
  **********************
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for aiohttp
  Running setup.py clean for aiohttp
  Building wheel for multidict (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/username/covalent/covalent_pre/bin/python /tmp/tmp6rjlbas4_in_process.py build_wheel /tmp/tmpss8p07mj
       cwd: /tmp/pip-install-tcicr_n2/multidict
  Complete output (89 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
 creating build
  creating build/lib.linux-x86_64-cpython-39
  creating build/lib.linux-x86_64-cpython-39/multidict
  copying multidict/_multidict_py.py -> build/lib.linux-x86_64-cpython-39/multidict
  copying multidict/_multidict_base.py -> build/lib.linux-x86_64-cpython-39/multidict
  copying multidict/_abc.py -> build/lib.linux-x86_64-cpython-39/multidict
  copying multidict/__init__.py -> build/lib.linux-x86_64-cpython-39/multidict
  copying multidict/_compat.py -> build/lib.linux-x86_64-cpython-39/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  adding license file 'LICENSE'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  /tmp/pip-build-env-5sxje5tv/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:204: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'multidict._multilib' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'multidict._multilib' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'multidict._multilib' to be distributed and are
          already explicitly excluding 'multidict._multilib' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


          [^1]: For Python, any directory (with suitable naming) can be imported,
               even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  copying multidict/__init__.pyi -> build/lib.linux-x86_64-cpython-39/multidict
  copying multidict/_multidict.c -> build/lib.linux-x86_64-cpython-39/multidict
  copying multidict/py.typed -> build/lib.linux-x86_64-cpython-39/multidict
  creating build/lib.linux-x86_64-cpython-39/multidict/_multilib
  copying multidict/_multilib/defs.h -> build/lib.linux-x86_64-cpython-39/multidict/_multilib
  copying multidict/_multilib/dict.h -> build/lib.linux-x86_64-cpython-39/multidict/_multilib
  copying multidict/_multilib/istr.h -> build/lib.linux-x86_64-cpython-39/multidict/_multilib
  copying multidict/_multilib/iter.h -> build/lib.linux-x86_64-cpython-39/multidict/_multilib
  copying multidict/_multilib/pair_list.h -> build/lib.linux-x86_64-cpython-39/multidict/_multilib
  copying multidict/_multilib/views.h -> build/lib.linux-x86_64-cpython-39/multidict/_multilib
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-x86_64-cpython-39
  creating build/temp.linux-x86_64-cpython-39/multidict
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/username/covalent/covalent_pre/include -I/usr/include/python3.9 -c multidict/_multidict.c -o build/temp.linux-x86_64-cpython-39/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  multidict/_multidict.c:1:10: fatal error: Python.h: No such file or directory
      1 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for multidict
Failed to build aiohttp multidict
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly




Kind regards,
Jack


[cid:canon-logo-email_70d9ca90-c358-4f81-8813-a2ad1f096963.png]<https://cpp.canon/>
Canon Production Printing Netherlands B.V.
P.O. Box 101, 5900 MA Venlo
Van der Grintenstraat 10, 5914 HH Venlo
The Netherlands | Trade register: 12002662
www.cpp.canon<https://www.cpp.canon>


This message and attachment(s) are intended solely for use by the addressee and may contain information that is privileged, confidential or otherwise exempt from disclosure under applicable law. If you are not the intended recipient or agent thereof responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by telephone or with a 'reply' message and delete the message and its attachment(s), if any, from your system(s). Thank you for your co-operation.

**Comment by JackSleuters** [comment]
Dear Andrew,

I looked at your code changes for v0.16.0 pre-release and I think your changes should fix the problem. If self.conda_env == None the slurm_conda lines are empty which means they are not generated.

Kind regards,
Jack


[cid:canon-logo-email_70d9ca90-c358-4f81-8813-a2ad1f096963.png]<https://cpp.canon/>
Canon Production Printing Netherlands B.V.
P.O. Box 101, 5900 MA Venlo
Van der Grintenstraat 10, 5914 HH Venlo
The Netherlands | Trade register: 12002662
www.cpp.canon<https://www.cpp.canon>


This message and attachment(s) are intended solely for use by the addressee and may contain information that is privileged, confidential or otherwise exempt from disclosure under applicable law. If you are not the intended recipient or agent thereof responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by telephone or with a 'reply' message and delete the message and its attachment(s), if any, from your system(s). Thank you for your co-operation.

**Comment by arosen93** [comment]
@JackSleuters: I haven't seen that error before. Could you try `pip install aiohttp==3.8.1` and see if you still get a build error?

**Comment by arosen93** [comment]
@santoshkumarradha: Looks like this can be closed.

**Comment by santoshkumarradha** [comment]
Thanks for this update @arosen93  ! 🙏
