### ISSUE TITLE
QElectron: revisit mechanism for returning QDB to dispatcher

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#1759]
Executors currently return the QElectron DB to the Covalent server by appending the base64-encoded database to the task's stdout. This stdout is then postprocessed in-memory to strip out the database into a separate object. This is a stopgap measure for speed of initial development but is not ideal in the long term. Reasons include:

- Incompatibility with task-packing
- Unnecessarily coupling the dispatcher Python version with that of the SDK and executor environments
- Postprocessing stdout is incompatible with upcoming changes to improve memory consumption during workflow processing. One particular change is that the covalent server will act as a mere file server for task artifacts and not preprocess or postprocess them in any manner.

We should revisit how we are transferring the QElectron DB back to Covalent.

**Comment by kessler-frost** [comment]
Since the Asset management has been introduced to `develop` now as part of memory improvements changes, we should add the Qelectron DB as an asset instead.
