### ISSUE TITLE
Adding covalent version attribute to Remote Executors

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1785]
Since the pickling of task functions and other assets happens on the client side, the version of Covalent SDK that was used in this procedure is a vital piece of information that should be propagated to the machine which will deserialize and execute that function.

This is because there are changes in the codebase that might happen and the Covalent version used by these remote executors might be outdated. Sharing this information from the machine where the task functions were serialized on, to the machine where the task functions will be run becomes necessary. Thus, this issue will require adding a new `covalent_version` attribute to the `RemoteExecutor` class in `covalent/executor/executor_plugins/remote_executor.py` file to simply convey this. It will be each executors responsibility to respect this version and updating these executors is out of the scope of this issue.

*This issue is a part of Hacktoberfest.  Closing this issue will earn you 1 point.*

**Comment by maskboyAvi** [comment]
@wjcunningham7 I would like to work on this issue. Please you assign it to me .

**Comment by kessler-frost** [comment]
Hey @maskboyAvi, glad to hear that! Please feel free to create a PR for this and let us know if you have any questions. Don't worry about the assignment of the issue, it isn't a requirement.
