### ISSUE TITLE
Adding image URI attribute to AWS Executors

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1786]
When using container-based executors, users often need a greater degree of customization than is possible through `PipDeps` or `BashDeps` alone.  For this reason, we allow users to customize the image used by Covalent tasks in container-based executors.  While the Azure Batch and GCP Batch plugins provide a constructor parameter `container_image_uri`, the AWS plugins are a little older and so they rely on an environment variable, which is used globally for all jobs using those plugins.  This issue is dedicated to updating the AWS plugins, both adding this new constructor parameter to the AWSExecutor (see AgnostiqHQ/covalent-aws-plugins) and removing the environment variable.

*This issue is a part of Hacktoberfest.  Closing this issue will earn you 1 point.*

**Comment by i-am-SnehaChauhan** [comment]
@wjcunningham7 I would like to work on this issue. Can it be assigned to me?

**Comment by kessler-frost** [comment]
Hi @i-am-SnehaChauhan ! Glad to hear that! Please feel free to open a PR for this, assignment of the issue is not a requirement 😄 !

**Comment by kessler-frost** [comment]
Please let us know if you have any questions here.

**Comment by kessler-frost** [comment]
@i-am-SnehaChauhan bumping, to let us know if you're blocked on this. Thanks!

**Comment by i-am-SnehaChauhan** [comment]
Hey @kessler-frost Actually, I am currently in the midst of my midterm exams. Could you please give me 3-5 days? I will complete this and submit my pull request as soon as possible.
