### ISSUE TITLE
Adding website link in readme

### ISSUE THREAD

**Issue by Arkaroy147** [AgnostiqHQ/covalent#1831]
### What should we add?

I wish to edit the readme file so when someone clicks the banner, it redirects them to the covalent main site
Please add hacktoberfest tag and assign me

**Comment by Aady7** [comment]
Assign me this

**Comment by kessler-frost** [comment]
We are not planning to add this issue as part of Hacktoberfest. If you would like to still submit a PR for this, feel free to do so but that will not be considered as part of Hacktoberfest. Also, please go through their guidelines about spammy PRs here: https://hacktoberfest.com/participation/#spam

**Comment by wjcunningham7** [comment]
This is not a change we want to include at this time.  Closing as not planned.
