### ISSUE TITLE
Proper error handling in covalent/doc/generate_docs.py

### ISSUE THREAD

**Issue by THEGAMECHANGER416** [AgnostiqHQ/covalent#1833]
### What should we add?

I would like to improve the code in the file `covalent/doc/generate_docs.py` by adding additional logging and adding a logging error if cmd.returncode != 0.
Seems like a simple fix. I would like to work on this issue for hacktoberfest 23.
Looking forward to get assigned on this issue.
Thanks

**Comment by kessler-frost** [comment]
Hey @THEGAMECHANGER416 , thanks for the issue, however we are not planning to add this into our set of Hacktoberfest issues. So, if you'd like to submit a PR for this, we are grateful but keep in mind that it won't be considered as part of the Hacktoberfest contribution. Also, I'd recommend going through their guidelines as well: https://hacktoberfest.com/participation/#spam.

**Comment by THEGAMECHANGER416** [comment]
@kessler-frost Yes sure, don't add hacktoberfest label, Just glad to make a contribution.
Thanks
