### ISSUE TITLE
Request to Update Twitter Logo 

### ISSUE THREAD

**Issue by moheyt** [AgnostiqHQ/covalent#1841]
### Environment

- **Covalent version**:
- **Python version**:
- **Operating system**: Windows

### What is happening?

I have identified that the Twitter logo displayed in the footer section of website is outdated, and it is crucial to keep branding up to date with the latest elements provided by Twitter.

![Screenshot 2023-10-24 215940](https://github.com/AgnostiqHQ/covalent/assets/85775976/a583ce89-55b7-4f74-b3ec-c44efaa73b3a)

![image](https://github.com/AgnostiqHQ/covalent/assets/85775976/dc681df9-ef33-412c-b5a1-bfc1949223a0)

### How can we reproduce the issue?

1. Go to homepage
2. Scroll down the bottom

### What should happen?

New Twitter logo will be used to replace the outdated one in the footer section of our website.

**Comment by moheyt** [comment]
I would like to work on this. Can you assign it to me?

**Comment by wjcunningham7** [comment]
Closing this issue because we are not currently accepting contributions to the website.  Please check out https://github.com/AgnostiqHQ/covalent/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest for a list of issues part of Hacktoberfest.
