### ISSUE TITLE
Expose programmatic equivalent of CLI commands

### ISSUE THREAD

**Issue by araghukas** [AgnostiqHQ/covalent#1853]
### What should we add?

For example:
```python
from covalent_dispatcher import covalent_start, covalent_stop

# start covalent server from Python
covalent_start()

# stop covalent server from Python
covalent_stop()
```
These functions should consider pitfalls, like submitting a workflow *immediately* after starting covalent (i.e. the known missing dispatcher address error).

### Describe alternatives you've considered.

This is doable using `subprocess` to issue "covalent start" or "covalent stop" shell commands.

**Comment by kessler-frost** [comment]
Implemented in #1854.
