### ISSUE TITLE
Research supervisord, gunicorn, and figure out the best way to run the services locally

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#186]
After we have finished the decomposition and local Covalent has a microservice architecture, what should happen when a user does `covalent start`? We need to figure out the best way to run the services on the local OS so that they are aware of each other and don't conflict. It will need to be compatible with the platforms we support.

**Comment by scottwn** [comment]
@AlejandroEsquivel when you make a new issue to track the supervisord development please link it here

**Comment by AlejandroEsquivel** [comment]
Deliverables for this issue:

Supervisord should be compatible with the OS' we support. It can also facilitate managing the state of locally running services, particularly it is:
- easy to start/restart/stop all the services as a group
- more robust way to query status of running applications
- provides dashboard (http://localhost:9001) to see running applications & logs 
- provides restart functionality of processes crash

In principle implementation is quite simple and should remove the need for code used to manage and query the state of running processes.

Supervisor can be installed using pip `pip install supervisor`

Once started with the command: `supervisord`
The `supervisorctl` cli can be used to manage the applications described in the `supervisord.conf` file (below).

When making updates to the config file one should run `supervisorctl reread` and `supervisorctl update`.

```
[program:queuer]
directory=/Users/alejandroesquivel/Documents/agnostiq/covalent
command=python refactor/queuer/main.py 
autostart=true
autorestart=true
stderr_logfile=/Users/alejandroesquivel/Documents/agnostiq/covalent/hello_world.err.log
stdout_logfile=/Users/alejandroesquivel/Documents/agnostiq/covalent/hello_world.out.log
numprocs=1

[supervisord]
logfile=/tmp/supervisord.log ; main log file; default $CWD/supervisord.log
logfile_maxbytes=50MB        ; max main logfile bytes b4 rotation; default 50MB
logfile_backups=10           ; # of main logfile backups; 0 means none, default 10
loglevel=info                ; log level; default info; others: debug,warn,trace
pidfile=/tmp/supervisord.pid ; supervisord pidfile; default supervisord.pid
nodaemon=true               ; start in foreground if true; default false
silent=false                 ; no logs to stdout if true; default false
minfds=1024                  ; min. avail startup file descriptors; default 1024
minprocs=200                 ; min. avail process descriptors;default 200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/tmp/supervisor.sock   ; the path to the socket file


[inet_http_server]         ; inet (TCP) server disabled by default
port=127.0.0.1:9001        ; ip_address:port specifier, *:port for all iface


[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket
serverurl=http://127.0.0.1:9001 ; use an http:// url to specify an inet socket
```

Note: Supervisord will look first in the CWD for the above config file
