### ISSUE TITLE
CHANGELOG is out-of-sync with releases

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [AgnostiqHQ/covalent#1865]
### Environment

- **Covalent version**: 0.229.0.rc0
- **Python version**: NA
- **Operating system**: NA

### What is happening?

The [CHANGELOG](https://github.com/AgnostiqHQ/covalent/blob/develop/CHANGELOG.md) release versions are not compatible with the actual releases on PyPI. For instance, it says [0.230.0.rc0 was released on 2023-11-24 in the CHANGELOG](https://github.com/AgnostiqHQ/covalent/blob/develop/CHANGELOG.md#02300-rc0---2023-11-24), but that was actually [0.229.0.rc.0](https://github.com/AgnostiqHQ/covalent/releases/tag/v0.229.0-rc.0).

### How can we reproduce the issue?

Look at the CHANGELOG :)

### What should happen?

The versions should match.

### Any suggestions?

Maybe I am bad at reading :)

**Comment by kessler-frost** [comment]
Hmm, that is indeed weird :thinking: . We'll look into this.

(btw, I believe you meant 0.230.0 instead of 0.223.0 here :sweat_smile: :
> The [CHANGELOG](https://github.com/AgnostiqHQ/covalent/blob/develop/CHANGELOG.md) release versions are not compatible with the actual releases on PyPI. For instance, it says [0.223.0.rc0 was released on 2023-11-24 in the CHANGELOG](https://github.com/AgnostiqHQ/covalent/blob/develop/CHANGELOG.md#02300-rc0---2023-11-24), but that was actually [0.229.0.rc.0](https://github.com/AgnostiqHQ/covalent/releases/tag/v0.229.0-rc.0).
)

**Comment by Andrew-S-Rosen** [comment]
What is up with me and numbers lately!! 😂😂😂

**Comment by kessler-frost** [comment]
@Andrew-S-Rosen After a quick overview of the nightly workflow, it seems like this should be fixed now as there's a 230 release on pypi. It was actually that release on pypi that got out of sync/wrong. I believe things should function as expected from now as both are now at 230.

**Comment by kessler-frost** [comment]
I'd vote for making this issue as resolved and if we encounter a similar scenario again, we can reopen it.

**Comment by Andrew-S-Rosen** [comment]
Ah, makes sense! Closing.
