### ISSUE TITLE
Enable qelectron tests in CI

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1877]
I believe somewhere along the line we must've missed adding the qelectron tests to the CI tests pipeline. This is now preventing us from knowing which modifications to the codebase will break the qelectron functionality. Plus they are already there in the tests folder, just not executed.

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost Any idea if just adding the tests to the CI suite will be enough to have things pass, or are further edits needed? Would love to see this merged so numpy >= 1.24 can be used!

**Comment by kessler-frost** [comment]
Hey @Andrew-S-Rosen, I don't believe more edits will be required. We'll try to address this very soon to unblock your PR.

**Comment by Andrew-S-Rosen** [comment]
Thanks, that would be a big help! 👍
