### ISSUE TITLE
Deployment CRM does not convert `bool`, `NoneType`, or `Sequence` correctly

### ISSUE THREAD

**Issue by araghukas** [AgnostiqHQ/covalent#1920]
The issue arises from [this line](https://github.com/AgnostiqHQ/covalent/blob/8d22e7d1b3c6078fb7fe1d63939ad064f7dcc04c/covalent/cloud_resource_manager/core.py#L436), where the value is substituted inside a quoted string.

While terraform can convert some strings into other types, it does not convert e.g. `"[]"` to the empty list, `"None"` to `null`, `"True"` to `true`, nor `"False"` to `false`. This leads to errors when deploying AzureBatch, for example, which has a boolean default `create_batch_account`. 

(Tested with `terraform` version `1.7.1`)

**Comment by santoshkumarradha** [comment]
closed by #1921
