### ISSUE TITLE
Remove electron object from electron decorator wrapper

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#1922]
### Environment

- **Covalent version**: 0.233.0

### What is happening?

Currently, the electron object is being passed in the electron decorator wrapper making it more bloated. This was a required feature for the original redispatch strategy. However, this is no longer required.

### How can we reproduce the issue?

NA

## Acceptance criteria

- [ ] Remove this [line](https://github.com/AgnostiqHQ/covalent/blob/8d22e7d1b3c6078fb7fe1d63939ad064f7dcc04c/covalent/_workflow/electron.py#L842)
- [ ] Ensure that this doesn't have any unforeseen repercussions
- [ ] Remove reference to wrapped attribute for function call in CC exec file.

### Any suggestions?

NA

**Comment by santoshkumarradha** [comment]
Note this is the only dynamic way of swapping executors for electrons AFAIK
So this needs to also follow up with an issue to swap executors directly. 
Current setup
```python
electron.electron_object.executor=Executor()
```

Removal of this should lead to this being possible -
```python
electron.electron_object.executor=Executor()
ct.dispatch(lattice_function()
```
