### ISSUE TITLE
Unnecessary `electron` metadata

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#20]
### Environment

- **Covalent version**:  0.22.6
- **Python version**:  3.8.12
- **Operating system**:  macOS 11.6

### What is happening?

`electron` metadata contains a lot of unnecessary fields fields such as `num_cpu`, `num_gpu`, `memory`, etc. This is due to the `default_constraints_dict` in `covalent/_shared_files/defaults.py`.

### How can we reproduce the issue?

```python
import covalent as ct
from matplotlib import pyplot as plt

@ct.electron
def sample_task(x):
    return x ** 2

@ct.lattice
def sample_workflow(a, b):
    c = sample_task(a)
    d = sample_task(b)
    return c, d


sample_workflow.build_graph(1, 2)

graph = sample_workflow.transport_graph.get_internal_graph_copy()
node_metadatas = [node_dict["metadata"] for _, node_dict in graph.nodes(data=True)]

print(node_metadatas)
```

This will output:
```
[
{'backend': 'local'}, {'schedule': False, 'num_cpu': 1, 'cpu_feature_set': [], 'num_gpu': 0, 'gpu_type': '', 'gpu_compute_capability': [], 'memory': '1G', 'backend': 'local', 'time_limit': '00-00:00:00', 'budget': 0, 'conda_env': ''}, 
{'backend': 'local'}, {'schedule': False, 'num_cpu': 1, 'cpu_feature_set': [], 'num_gpu': 0, 'gpu_type': '', 'gpu_compute_capability': [], 'memory': '1G', 'backend': 'local', 'time_limit': '00-00:00:00', 'budget': 0, 'conda_env': ''}
]
```

### What should happen?

These fields can be moved to a different dictionary and commented. Further, that dictionary can be used as an example on how users can define their custom metadata fields and their default values. `default_constraints_dict` should only contain `backend` as a metadata field for now.

**Comment by Aobasi4** [comment]
I can play around with it and see if I can get it to model the expected behavior. You could go the brute force route and pop them out of the dict into a new one but this could be slow and I think there is a better solution. I would love to take a look.

**Comment by kessler-frost** [comment]
Hi @Aobasi4 ! Welcome to Covalent. Please feel free to play around and take a stab at this. Let us know if you come across any obstacle, we're here to help.

**Comment by Aobasi4** [comment]
Thanks so much! I'll let you know if I run into any problems.

**Comment by FyzHsn** [comment]
> Thanks so much! I'll let you know if I run into any problems.

Hey @Aobasi4 what's the status on this issue?

**Comment by Aobasi4** [comment]
> > Thanks so much! I'll let you know if I run into any problems.
> 
> Hey @Aobasi4 what's the status on this issue?

Hey Sorry, School got a little bit crazy. Looking to get it wrapped up this weekend!

**Comment by Aobasi4** [comment]
@FyzHsn Opened the PR with a couple of questions let me know if there is anything else I am missing. Thanks again!
