### ISSUE TITLE
Quantum Gravity tutorial needs to be given another look

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#216]
There are some things which were detected during QA session that don't work in the Quantum Gravity tutorial `doc/source/tutorials/quantum_gravity/spacetime_classification.ipynb`.

Some of these things include:

* We'll need to switch to using PyTorch instead of Tensorflow since the latter doesn't work on M1 Macs.

* There's a PNG missing in the notebook that wasn't found.

* The following code-block blocks indefinitely:

```python
# Summarize the model using synchronous dispatch
model = ct.dispatch_sync(ct.lattice(construct_model))(layers=layer_sizes).result
print(model.summary())
```

* Importing tensorflow with Ubuntu 20.04 and python 3.9 didn't work, gave the following error:

```python
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
```

**Comment by wjcunningham7** [comment]
let's find another solution... we can't entirely write off tensorflow
