### ISSUE TITLE
Minor `README` fixes

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#22]
### What should we add?

In `README.md` sometimes if the user directly copy-pastes the example code written, it might not work as expected. Two places where I found this were:

1. In `README.md` for the "Without and With Covalent" example, `result = ct.get_result(dispatch_id)`, here since the default value of `wait` parameter is `False`, this might not give the expected result because it didn't wait for the calculation to complete. So, simply changing it to `result = ct.get_result(dispatch_id, wait=True)` will do the trick.

2. In the same file, ideally we would like to increase the width of the `Without and With Covalent` table, using some markdown magic in order to fit the `dispatch_id = run_experiment.dispatch` in one line.

3. In `covalent_ui/README.md` the port number is mentioned as `48008` whereas now the UI server runs at `47007` by default.

**Comment by scarycool11** [comment]
Hello can I solve this issue @kessler-frost .
