### ISSUE TITLE
Don't create a new object for every result update

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#221]
Currently there is no way for the data service to replace or delete an object. Because of this, every update to a results object uploads a new object and then points the dispatch id to that new object, creating many orphaned objects. This could be fixed by one of the following approaches.

* enhance data service to take a put update with a file body so at least we're not doing 2way communication on every update
* enhance data service upload to take a overwrite queryparam
* keep results in a DB somehow?

**Comment by cjao** [comment]
[PR #271](https://github.com/AgnostiqHQ/covalent/pull/271) will grow the ability to delete objects via the data service. Also, the data service would be able to replace an object if not for [these lines](https://github.com/AgnostiqHQ/covalent/blob/develop/refactor/data/app/core/localstoragebackend.py#L110-L112).
