### ISSUE TITLE
Remove hardcoded filepaths and standardize global variable names

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#229]
The objective of this issue:

- [ ] Remove all hardcoded file paths in favour of config file variables (Faiyaz).
- [x] Standardize all the global variable names (Alejandro).

**Comment by scottwn** [comment]
see also https://github.com/AgnostiqHQ/covalent/pull/231

**Comment by scottwn** [comment]
see also https://github.com/AgnostiqHQ/covalent/pull/220/files#diff-1e8ec071906439010c5cf87242e760157de0197f36bf269075da032138a9d657R64
