### ISSUE TITLE
Add author names in changelog messages automatically

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#237]
### What should we add?

~~There is a way to do it described here https://github.com/AgnostiqHQ/covalent/pull/207#issuecomment-1075352219~~

The best way to do this is probably to enhance the [changelog workflow](https://github.com/AgnostiqHQ/covalent/blob/develop/.github/workflows/changelog.yml) to retrieve the commit author(s) from the [push payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push) and write them to the changelog message. You might try to append the authors to the `changelog_header` in the workflow, so a changelog message looks like
```
## [0.108.0] - 2022-06-08

### Authors

@wjcunningham7 

### Added

- WCI yaml file

### Docs

- Add pandoc installation updates to contributing guide
```

### Describe alternatives you've considered.

Doing it automatically is better than having people type their handles into the changelog

**Comment by divshacker** [comment]
I can give it a shot.

**Comment by scottwn** [comment]
There are some changes going in #601 that will impact this issue. Once that PR is merged, changelog logic will live in a JavaScript action rather than a workflow file. That will be where you want to focus on automating the author names.

**Comment by cometta** [comment]
is the task is only need to modify one file .github/actions/changelog/index.js ?

is the lines below already automated by .github/workflows/changelog.yml ,  
 uses: EndBug/add-and-commit@v9 

### Added

- WCI yaml file

### Docs

- Add pandoc installation updates to contributing guide

? is that correct?

how to test the workflow if i work on this issue?

should we wait #601 merged first?

**Comment by scottwn** [comment]
> is the task is only need to modify one file .github/actions/changelog/index.js ?

I'm not 100% certain but yes I think the only change will need to be in this JS file

> is the lines below already automated by .github/workflows/changelog.yml

Not those lines specifically. They are added by developers by hand and parsed automatically by the CI to update the version number.

> how to test the workflow if i work on this issue?

You should be able to test it in your own fork, but if you get stuck with testing LMK and I can help with that

 > should we wait https://github.com/AgnostiqHQ/covalent/pull/601 merged first?
 
Don't wait for the merge to get started working. You can branch off `i-34` and work there. Or you can work off `develop` using the existing `changelog.yml` but it might break when #601 gets merged.

**Comment by cometta** [comment]
PR at https://github.com/AgnostiqHQ/covalent/pull/643

**Comment by cometta** [comment]
@scottwn may i know why you rejected my PR?

**Comment by divshacker** [comment]
I have tried to search about this in the given link above and also read some documentation, but like yeah I still don't have a complete solution on how to implement this. Any guidance on other platform like discord would be nice for me.
