### ISSUE TITLE
Streaming and file type issues in data & results

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#242]
via @kessler-frost : 
we may want to change
https://github.com/AgnostiqHQ/covalent/pull/215/files#diff-d5a1b52ef809a88edbb01367cf4a161ddc0b9ce35c885981d8a8363cb0588949R182
to
https://github.com/AgnostiqHQ/covalent/blob/refactor-intermediate/refactor/results/app/api/api_v0/endpoints/workflow.py#L190

this comment from @cjao :
https://github.com/AgnostiqHQ/covalent/pull/215/files#r837530992

**Comment by scottwn** [comment]
We are going to upload bytes and download bytes
We need to change the SDK wrapper to handle this change

**Comment by cjao** [comment]
There are two sub-issues:
1. To benefit from `stream=True` and `StreamingResponse`, one needs to access the response body through `iter_content()` or `iter_lines()`. Currently we load the entire response body into memory using the `content` property, so the `stream=True` argument confers no advantages.

2. Handle the actual StreamingResponse.

**Comment by kessler-frost** [comment]
That is true, but that gives us the option to handle loading into memory on the receiving end. So, if we're using things internally between microservices, we anyway will want to load the whole object into memory as we will be editing it in most cases. But when the user does the download, we can write the download wrapper in the sdk using `iter_lines()` or `iter_content()` so later on when we do support having > memory files we can provide the user the ability to download them.
