### ISSUE TITLE
Add tests for lattice results and results manager

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#28]
@scottwn commented on [Wed Nov 24 2021](https://github.com/AgnostiqHQ/covalent-staging/issues/128)

In GitLab by @FyzHsn on Nov 23, 2021, 10:38

## Overview
Once the lattice results and results manager has been added, we need to add tests for the feature.

**Comment by wjcunningham7** [comment]
@scottwn can we close this?

**Comment by scottwn** [comment]
results manager still does not have good unit test coverage. I've added some tests as I go while improving it, but I think it still needs more tests

**Comment by venkatBala** [comment]
@AlejandroEsquivel is this one still relevant?
