### ISSUE TITLE
CI tests to Verify Container Networking in Cloud Deployments

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#296]
# What should we add ?
- [ ]  There should be a workflow to test the liveness of service containers on every pull request, e.g., by querying health endpoints in each service.
- [ ]  The workflow should fail when containers are unhealthy and log relevant HTTP status codes for debugging.
- [ ]  Containers should successfully ping each other in the self-hosted network.
- [ ]  Images should be pushed to their respective development repositories in ECR on merging to the develop branch.
- [ ]  Images should be pushed to their respective master repositories in ECR on merging to the master branch.

**Comment by scottwn** [comment]
re: `buildx`, see also https://github.com/AgnostiqHQ/covalent/pull/27
