### ISSUE TITLE
Include detect-secrets as a pre commit

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#30]
@scottwn commented on [Wed Nov 24 2021](https://github.com/AgnostiqHQ/covalent-staging/issues/131)

In GitLab by @scottwn on Nov 23, 2021, 18:03

## Overview
do this https://github.com/Yelp/detect-secrets

## Technical Details
`detect-secrets` is a tool that scans your code for API keys, passwords, etc before committing. It's an easy and fun way to prevent accidentally exposing credentials.

## Expected Results
`detect-secrets` runs as a pre-commit

**Comment by scottwn** [comment]
resolved in #367
