### ISSUE TITLE
Writing examples in docstrings inside covalent

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#31]
@scottwn commented on [Mon Nov 29 2021](https://github.com/AgnostiqHQ/covalent-staging/issues/146)

- [ ] executor
- [ ] _results_manager
- [ ] _shared_files
- [ ] _workflow

**Comment by venkatBala** [comment]
@wjcunningham7 @scottwn this can be closed I presume right?

**Comment by scottwn** [comment]
I'm still seeing many docstrings in the code that don't meet our standard. I would keep these docstrings issues open until that is addressed

**Comment by wjcunningham7** [comment]
@scottwn this tool may be useful https://github.com/HunterMcGushion/docstr_coverage
