### ISSUE TITLE
Remove draw function from tutorials, howtos

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#39]
@wjcunningham7 commented on [Wed Jan 05 2022](https://github.com/AgnostiqHQ/covalent-staging/issues/264)

We want to remove the graphviz dependency.  In this issue, replace any references to `draw` in the documentation with a UI screenshot.  Then deprecate the draw function and confirm that the package is pip installable without graphviz.

---

@santoshkumarradha commented on [Thu Jan 06 2022](https://github.com/AgnostiqHQ/covalent-staging/issues/264#issuecomment-1006405095)

@wjcunningham7 instead of depreciating, could we have a error there to put out if graphviz was not there abs asking user to install? Vowing the graph without Ui might still be important in few cases(places like these tutorials or quick prototype before sending to cloud without having UI, debuting too as the plot will not go beyond the electron that does unsupported things inside lattice etc..). And ideally our dependency of graphviz comes not out of totally needing it, but comes only out of plotting the coordinates, so we can in theory write our own code to replace it. 

One feature we are including in the Ui (not in current version but next one) is to display before dispatching. Until we are able to do this I think the draw graph is necessary even in tutorials (with a warning that it's not absolutely required) as there is no way yet to look at the workflow without submitting.

**Comment by wjcunningham7** [comment]
@HaimHorowitzAgnostiq confirm with @valkostadinov the new draw capabilities have been merged, then proceed with this issue

**Comment by scottwn** [comment]
As part of this issue, let's make a couple small fixes
* Add a note in the tutorial to lower the number of sublattices depending on the hardware and indicate that this is a known issue
* Re-add Known Issues to README and make a note of this sublattice issues
