### ISSUE TITLE
Missing positional arguments error thrown when passing same argument twice to electrons in a workflow

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent#392]
**Issue**

When creating a simply workflow, graph build does not recognize the input arguments to an electron when they are exactly the same.

**How to reproduce**
Execute this simple workflow

```python
import covalent as ct

@ct.electron
def add(x, y):
    return x + y

@ct.electron
def multiply(x, y):
    return x*y

@ct.lattice
def workflow(x, y):
    r1 = add(x, y)
    r2 = multiply(r1, r1)
    return r1 + r2

id = ct.dispatch(workflow)(2, 3)
res = ct.get_result(id,wait=True)
```

**Output**

![image.png](https://images.zenhubusercontent.com/623b1a20a1bf5413da5a683b/1d0b5414-abbf-4353-b594-a0014bec507f)

**Comment by cjao** [comment]
Some debugging notes:

- The statement `r2 = multiply(r1, r1)` works if the electron `r1` is replaced by a pure scalar, like `r2 = multiply(5, 5)`.
