### ISSUE TITLE
Fix UI hardcoding the results service URI

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent#401]
* `covalent_ui` needs the following variables to communicate with the results service

REACT_APP_RESULTS_SVC_URI=http://localhost:8005
REACT_APP_UI_BACKEND_SVC_URI=http://localhost:8000

and when the static files are built, the values of these environment variables get hard coded into the files.

For local docker deployments (i.e running all containers on a single machine), this is not a problem since all containers expose their respective ports to the host machine, but this will be an issue when doing self hosted deployments as each service is intended to be deployed on a separate virtual machine

Need a way to dynamically updated these variables so that the UI knows during runtime the connection information of the results service

**Comment by AlejandroEsquivel** [comment]
No longer needed
