### ISSUE TITLE
Covalent's executer in API docs RTD

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#41]
@santoshkumarradha commented on [Tue Jan 18 2022](https://github.com/AgnostiqHQ/covalent-staging/issues/304)

- ~~We now have exposed the executers inside covalent, but still do not yet have any API documentation of various parameters for it in https://covalent.docs.agnostiq.ai/en/latest/api/api.html. We need to expose that in RTD~~

**Edit:** Moving the preceding subtask to a different issue.

- [ ]  https://covalent.docs.agnostiq.ai/en/latest/api/api.html#lattice object has some text not being displayed right `new Lattice <covalent._workflow.lattice.Lattice> object.` 

- [x] Covalent cli https://covalent.docs.agnostiq.ai/en/latest/api/api.html#covalent-restart 's doc string is not correctly formatted that options show up weirdly. Click's doctoring does not need to contain args and return value as those are not used by cli. 

- [ ] Re run covalent in notebooks to change the job-id to uuid everywhere and change it in references like getting started

**Comment by venkatBala** [comment]
same as #781
