### ISSUE TITLE
Add troubleshooting section

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#44]
## Acceptance Criteria
- [ ] Should be an accessible section in Covalent RTD
- [ ] Should cover common issues and how to resolve them (see below)

### Guide

Should cover typical issues users may face including but not limited to:
1. Issues using covalent without virtual environments (resolution: use pyenv, conda, poetry)
2. For long running workflows what to do if you see max-depth issue
3. For large workflows how to increase open file limit
4. Issues faced when running compute intensive workflows (how to increase dask cluster compute)
5. Also see: https://agnostiqworkspace.slack.com/archives/C02JS6NAFV3/p1643123017371300

**Comment by wjcunningham7** [comment]
design: section or page in docs + link in README to docs.

**Comment by Emmanuel289** [comment]
@AlejandroEsquivel @wjcunningham7 @AnnaGwen Some highlights of the discussions to go into guide:

- Covalent troubleshooting guide:
   -- Looking at the logs;
   -- Discourage usage of `covalent purge`;
   -- Restarting the server if workflow execution hangs indefinitely;
   -- Pointing users on how to setup the Dask dashboard if they want to troubleshoot issues related to Dask

- Executor specific (SSH and EC2)
  -- Create an issue for dropped SSH connections during workflow dispatch/execution;
  -- Adding example error codes and messages in guide so users know what to expect
  -- Properly tearing down resources when workflows fail or throw exceptions during execution;

**Comment by wjcunningham7** [comment]
@AlejandroEsquivel @santoshkumarradha reviving this one
