### ISSUE TITLE
Quantum machine learning tutorial

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#45]
@santoshkumarradha commented on [Fri Dec 10 2021](https://github.com/AgnostiqHQ/covalent-staging/issues/195)

Machine learning tutorial using/mixing pennylane and qiskit together.

**Comment by santoshkumarradha** [comment]
Put on hold until parallelization memory/CPU handling is fleshed out.

**Comment by iotaisolutions** [comment]
Hi, I am trying run the Covalent Machine Learning Tutorial code on Google Colab, getting few covalent error(s) while submitting tasks, could you please suggest correct platform to discuss about covalent specific errors.

**Comment by santoshkumarradha** [comment]
Hi @iotaisolutions, thanks for reaching out. Feel free to start either a Q&A or General discussion in our  [discussions](https://github.com/AgnostiqHQ/covalent/discussions) section and our team/other users would gladly come over to help you out. If you run into any error that is related to a bug, please open up an issue here.

**Comment by iotaisolutions** [comment]
Thanks @santoshkumarradha , started a new discussion on https://github.com/AgnostiqHQ/covalent/discussions with screenshot of error
