### ISSUE TITLE
Switch from `workflow.dispatch` to `covalent.dispatch`

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#48]
### What should we add?

Currently we are using `workflow.dispatch` to send a lattice `workflow` for execution to the dispatcher server. Maybe we can use a more intuitive approach for dispatching which is similar to how we obtain the result for a particular dispatch. The proposal is to have a function `covalent.dispatch` similar to `covalent.get_result` so that it is more intuitive for users to send a job the same way they get the result.

Resolving this issue may also involve updating the `README.md`s, tutorials, documentation, etc. So it will turn into a big issue.

**Comment by santoshkumarradha** [comment]
Hey @kessler-frost , dont forget this list as well (could be separate issues as well) 
- including depreciation warning for `lattice.dispatch()`
- Changing tutorials/how-to/readme/examples

**Comment by santoshkumarradha** [comment]
@kessler-frost  another thing to remember is to move the non-executer but dispatcher dependent meta data in lattice like port etc.... inside this function. User should be able to dispatch the same lattice to separate dispatchers without needing to recreate the lattice.
