### ISSUE TITLE
Adding CI/CD checks for  reminding/catching version update/ Change log update in PR.

### ISSUE THREAD

**Issue by santoshkumarradha** [AgnostiqHQ/covalent#54]
### What should we add?

Updates to PR contributors similar to 

```
Hello. You may have forgotten to update the changelog!
Please edit changelog.md with the changes you have made
```

for all incoming PRs to reduce and automate the code review process. Potential things to check include
- version
- changelog 

### Describe alternatives you've considered.

None.

**Comment by scottwn** [comment]
how pennlyane does it https://github.com/PennyLaneAI/pennylane/blob/master/.github/workflows/changelog_reminder.yml

how qiskit does it https://github.com/Qiskit/qiskit-bot/blob/master/tools/generate_changelog.py
