### ISSUE TITLE
`ModuleNotFound` when constructing leptons

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#551]
When following the how-to guide for constructing leptons here: https://covalent.readthedocs.io/en/latest/how_to/orchestration/construct_lepton.html, the following error was raised,

```python
ModuleNotFoundError: No module named '/covalent/covalent/test_module' 
```

which I believe might be because of incorrect pathing.

## Acceptance Criteria

- Update how-to guide for constructing leptons here https://covalent.readthedocs.io/en/latest/how_to/orchestration/construct_lepton.html to include instructions for specifying PYTHONPATH to fix the issue above

**Comment by wjcunningham7** [comment]
@kessler-frost this is resolved by setting the pythonpath before starting the server

**Comment by cjao** [comment]
Setting the PYTHONPATH doesn't seem to work for me. I modified the `python_wrapper` to log the PYTHONPATH in the event of failure:
```
[2022-08-16 12:58:11,231] [WARNING] lepton.py: Line 204 in python_wrapper: Could not import the module '/var/home/casey/Agnostiq/code/covalent/doc/source/how_to/orchestration/test_module' from PYTHONPATH=/var/home/casey/Agnostiq/code/covalent/covalent_dispatcher/_cli/../../covalent_ui/../tests:/var/home/casey/Agnostiq/code/covalent/doc/source/how_to/orchestration.
```

**Comment by cjao** [comment]
Besides setting PYTHONPATH, we also need to set `library_name` correctly in the notebook; we shouldn't prepend cwd to the module name.

**Comment by cjao** [comment]
For reference, PR #1042 modifies `sys.path` using a calldep.
