### ISSUE TITLE
`gcc` error when constructing leptons in C

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#554]
After following the how-to here, https://covalent.readthedocs.io/en/latest/how_to/orchestration/construct_c_task.html, cell block 3 fails with the following error:

```python
/Library/Developer/CommandLineTools/usr/bin/nm: error: libtest.so: File format has no dynamic symbol table.
```

seems to be a gcc/clang related error.

Edit: Adding platform info:

MacOS 12.3.1 Apple M1
`gcc` command uses clang in the backend
Python 3.8.13, clang 12.0.0

**Comment by wjcunningham7** [comment]
this problem is due to clang not properly building the library

**Comment by venkatBala** [comment]
@wjcunningham7 can this be closed?
