### ISSUE TITLE
Changelog Reminder workflow fails with HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#581]
### Environment

- **Covalent version**: 0.106.0
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is happening?

The [Changelog Reminder GitHub Actions workflow](https://github.com/AgnostiqHQ/covalent/blob/develop/.github/workflows/changelog_reminder.yml) is consistently [failing](https://github.com/AgnostiqHQ/covalent/actions/runs/2417511497) on external pull requests.

### How can we reproduce the issue?

Run automated checks on an external PR.

### What should happen?

The action should succeed and post a comment if the contributor has not updated the CHANGELOG.

**Comment by scottwn** [comment]
@cjao we have a new bug on this action
```
(node:1636) UnhandledPromiseRejectionWarning: Error: GITHUB_TOKEN environment variable not set. Read the docs.
```
https://github.com/AgnostiqHQ/covalent/runs/6727761730?check_suite_focus=true

**Comment by scottwn** [comment]
I expect it's because the action is still trying to run in the fork so it doesn't have access to secrets in our account 😢

**Comment by cjao** [comment]
I agree (just learned about [how secrets work](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)). Let's try the `pull_request_target` [trigger](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) approach.
