### ISSUE TITLE
Use central logger in covalent to increase logging verbosity in Covalent

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent#593]
## Acceptance Criteria

- [ ] Check if still is still needed

**Comment by venkatBala** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Covalent-Open-Source-627981af7f141b0020c699d1/issues/AgnostiqHQ/covalent/593?planning-poker) with ZenHub @cjao @Emmanuel289

**Comment by AlejandroEsquivel** [comment]
Not needed
