### ISSUE TITLE
Add type hint for result object in lattice

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#60]
Add type hint for `result_object` in `covalent/_workflow/lattice.py` inside the `_server_dispatch` method.

**Comment by NeelPatel31** [comment]
Hey, I want to work on this issue.
Can you explain the problem briefly ?

**Comment by kessler-frost** [comment]
Hi @NeelPatel31! Thank you for sharing your interest in contributing to covalent. Although, it seems someone is already working on this issue, you can still take a look at some of our other good first issues [here](https://github.com/AgnostiqHQ/covalent/labels/good%20first%20issue) and pick one which interests you the most.
