### ISSUE TITLE
Add cli options to Covalent to support Dask

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#608]
This issue will track development to support the following cli options for Dask in Covalent:

```
covalent start --no-cluster # uses local executor without dask as default
covalent start --memory-limit="2 GiB" --cpu=5 --cluster-port=80021 --method=thread#(or process)
covalent cluster --scale=5 #(scale up or down the cluster)
covalent cluster --adapt 2 9 #(optional, we can implement this later on as well )
covalent cluster --restart
covalent cluster --stop
covalent cluster --address
covalent cluster --info
```

Update the ```covalent --help``` menu to reflect the above cli options.

**Comment by Emmanuel289** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Covalent-Open-Source-627981af7f141b0020c699d1/issues/AgnostiqHQ/covalent/608?planning-poker) with ZenHub @venkatBala

**Comment by venkatBala** [comment]
Acceptance criteria

- [ ] Implement `start` and `memory-limit` CLI options (high priority)

- [ ] Implement pending CLI options, document the ones that remain pending
