### ISSUE TITLE
Add type hint in transportable object

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#61]
Add type hint for `data` field in `deserialize` method of `TransportableObject` in `covalent/_workflow/transport.py`.

**Comment by Udayan853** [comment]
Hey FyzHsn, I would like to work on this issue.

**Comment by FyzHsn** [comment]
> Hey FyzHsn, I would like to work on this issue.

Hi @Udayan853 that sounds great! I'm assigning you the issue.
