### ISSUE TITLE
Add type hint for base executor 

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#62]
Some of the fields in the `covalent/executor/base.py` module are missing Type hints. This issue is to ensure that all the fields have type hints.

**Comment by sayandipdutta** [comment]
I would be happy to add a PR. I looked at the code, considering the `Optional[str]` fields' default value is an empty `str`, I think `Optional` could be dropped. Would you agree?
```diff
    def __init__(
        self,
-        log_stdout: Optional[str] = "",
-        log_stderr: Optional[str] = "",
-        conda_env: Optional[str] = "",
-        cache_dir: Optional[str] = "",
        current_env_on_conda_fail: bool = False,
    ) -> None:
    def __init__(
        self,
+        log_stdout: str = "",
+        log_stderr: str = "",
+        conda_env: str = "",
+        cache_dir: str = "",
        current_env_on_conda_fail: bool = False,
    ) -> None:
```

**Comment by kessler-frost** [comment]
Hi @sayandipdutta ! Yeah, I agree with you. Plus since we are handling the empty string cases in respective places where they are being used we can remove the `Optional` part from these type hints.

**Comment by sayandipdutta** [comment]
I am not sure if I should update VERSION and CHANGELOG over this.
