### ISSUE TITLE
Clarify Covalent best practices in RTD

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#647]
### What should we add?

Naively "Covalentfying" a workflow can introduce subtle and counterintuitive bugs, as illustrated  in #646. We should guide users on how to avoid them. The RTD already has a [Best Practices](https://covalent.readthedocs.io/en/latest/concepts/concepts.html#best-practices) section that we can elaborate.

**Comment by wjcunningham7** [comment]
@santoshkumarradha can this be closed?
