### ISSUE TITLE
UI fails to correctly show the status of a workflow when a burst of workflows are dispatched

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent#650]
### Environment

- **Covalent version**: 0.110.1
- **Python version**: 3.8.13
- **Operating system**:  Linux/MacOS

### What is happening?

At times when there is a burst of workflow dispatches to the covalent server, status of certain workflows fail to update to complete and are left in the `RUNNING` state even when the computations have finished. It always seems to happen after all tasks in a workflow have finished. It seems as if the final update to the database gets skipped occasionally.
![ui_bug](https://user-images.githubusercontent.com/15014089/173596947-861ccf4e-d635-497c-b549-2536f2abdec7.png)

### How can we reproduce the issue?

After starting covalent, one can run the all the tasks in the notebook `tests/stress_tests/stress.ipynb` to reproduce this issue

### What should happen?

When the notebook is run, a burst of workflows get dispatched to the covalent server which can result in some DB writes to get missed resulting in the UI not being able to update/display the correct status of a workflow

**Comment by wjcunningham7** [comment]
@AlejandroEsquivel can this be closed?

**Comment by wjcunningham7** [comment]
> @AlejandroEsquivel can this be closed?

CC @venkatBala
