### ISSUE TITLE
Re-factor lattice graph for better usability

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#662]
The following problems are noticed on the graph page in the OS web app - 

1. For graphs with number of nodes > ~40, entirety of the graph is not visible in one screen.
2. In situations where the entirety of the graph is not visible in one screen, the option to 'Zoom out' and the 'fit to screen' does not seem to work. 
3. For graphs with number of nodes > ~40, the edge length on select portions of the graph is too long. This forces the graph to be spread out un-duly either length wise or height wise. 

The following objectives are desired - 
1. The above problems should be addressed. 
2. Enable all the nodes of a graph to be visibly on one screen at one time. Irrespective of the size of each node, it is sufficient to enable users to zoom in as needed.

**Comment by mshkanth** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Covalent-Open-Source-627981af7f141b0020c699d1/issues/AgnostiqHQ/covalent/662?planning-poker) with ZenHub @Prasy12

**Comment by mshkanth** [comment]
The following are potential approaches to re-factor this with varying timelines, risks & complexities - 

Option 1 -
Dagre.Ranker
react-flow-renderer

Option 2 -
Tweak Rank/Node/Edge seperation & Coordinates
Assign rank manually

Option 3 -
Dagre + graphlib
React flow + ElkJS

Option 4 -
Replace React-flow & Dagre
Kedro-Viz as a stand alone component

**Comment by santoshkumarradha** [comment]
> @santoshkumarradha - Are there any other features/tweaks/problems beyond the above ones that you were also expecting to be resolved?

This covers it !
