### ISSUE TITLE
File Transfer MVP

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#673]
## Epic Acceptance Criteria

- As a covalent user I should be able to transfer files between electrons via SSH

## Issue Breakdown (In order)

Planning doc: https://docs.google.com/document/d/16KOqpjQhAHvhWGodT2xYuCCu60Zr3kcn6JwIHxigPFQ/edit

Discussion: https://github.com/AgnostiqHQ/covalent/discussions/687
 
- Proposal for UX SDK
- Proposal for DB schema
- Create File class that will be used to define file locations locally or remote (will be generalized for Globus, HTTP (Github, ect), FTP)
- Create StorageBackend class (which is responsible for transferring File instances to their according input and output destinations via SSH)

**Comment by venkatBala** [comment]
@AlejandroEsquivel this is good to be closed right?

**Comment by AlejandroEsquivel** [comment]
@venkatBala thanks for keeping an eye on this, this is an epic which still contains a few issues and we anticipate it will close by end of this current sprint

**Comment by venkatBala** [comment]
> @venkatBala thanks for keeping an eye on this, this is an epic which still contains a few issues and we anticipate it will close by end of this current sprint
cheers!
