### ISSUE TITLE
Import Dependencies (Pip)

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#678]
## Acceptance Criteria

- Should be able to specify the name, corresponding versions and relational operators of modules to be installed for **each individual electron** (defaults at workflow level are out of scope) within each executor handling the corresponding electron execution
- Should be able to specify a `requirements.txt` filepath for an electron to improve end-user UX for certain use cases

**Comment by AlejandroEsquivel** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Covalent-Open-Source-627981af7f141b0020c699d1/issues/AgnostiqHQ/covalent/678?planning-poker) with ZenHub @cjao

**Comment by cjao** [comment]
An implicit assumption here is that the dependencies for an electron remain the same across all invocations of the electron. This seems like a reasonable assumption for import deps (the electron's code is static) but may need to be revisited for file deps.

**Comment by cjao** [comment]
Supporting `requirements.txt` is a bit tricky. The file format is [more general than just a list of packages](https://pip.pypa.io/en/stable/reference/requirements-file-format/), and Pip doesn't expose any public API to parse the file. Perhaps we can just support a `packages` list for now.
