### ISSUE TITLE
Proposal for db schema changes to support file transfer

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#680]

**Comment by scottwn** [comment]
@AlejandroEsquivel is there a status update on this issue? I see no action in over a month

**Comment by wjcunningham7** [comment]
@AlejandroEsquivel checking in on this

**Comment by AlejandroEsquivel** [comment]
@wjcunningham7  Currently implementing a prelim schema for this should have no effect on the product as there doesn't seem to be a plan yet around how file transfer operations will be represented in the UI which will better inform us as to the most appropriate schema to use, does it make sense then to re-open issue when we scope out UX?
