### ISSUE TITLE
Performance degradation with scaling of electrons in workflows

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#690]
### Environment

- **Covalent version**: 0.106.0
- **Python version**: 3.8.13
- **Operating system**: Linux/MacOS

### What is happening?

When the number of electrons in a workflow scales to double digits, a significant degradation in the runtime is noticed when the workflow is dispatched to the Covalent server.

### How can we reproduce the issue?

The performance degradation can be noticed when the number of electrons in a workflow begins to exceed 50.

### What should happen?

The runtime performance of dispatched workflows should remain stable with increasing number of electrons.

**Comment by scottwn** [comment]
Closed by #819
