### ISSUE TITLE
`covalent restart` does not store the state of the active execution mode/compute backend

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#692]
### Environment

- **Covalent version**:  110.0
- **Python version**:  3.8.13
- **Operating system**: Linux/MacOS

### What is happening?

covalent restart does not store the state of the active execution mode/compute backend. In essence, running covalent restart after covalent start or covalent start --no-cluster always defaults the compute backend to Dask

### How can we reproduce the issue?

Running `covalent restart` after `covalent start` (starting with Dask backend) or `covalent start --no-cluster`(starting with Local backend) always defaults the compute backend to Dask. This behavior can be observed by checking that the executor attribute in the UI is set to `dask` regardless of which compute backend was selected.

### What should happen?

`covalent restart` should store the selected option for the compute backend in memory and restart Covalent as appropriate.

**Comment by AlejandroEsquivel** [comment]
Closed by https://github.com/AgnostiqHQ/covalent/pull/1148
