### ISSUE TITLE
Reliably switching between Dask Execution and Local Execution

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#695]
### Environment

- **Covalent version**:  0.110.0
- **Python version**: 3.8.13
- **Operating system**: Linux/MacOS

### What is happening?

When the following chain of commands are run: `covalent start && covalent stop && covalent start --no-cluster`, Dask Execution is still activated, despite specifying the --no-cluster option. Currently, users need to run `covalent purge` in between covalent start and covalent start --no-cluster if they wish to switch between Dask Execution and Local Execution

### How can we reproduce the issue?

Run the following chain of commands: `covalent start && covalent stop && covalent start --no-cluster`. Dask Cluster is still spun up at a valid scheduler address as can be seen with`covalent logs` despite specifying the `no-cluster option`.

### What should happen?

After running the following chain of commands: `covalent start && covalent stop && covalent start --no-cluster`, the executor should reliably switch from Dask to Local.

**Comment by scottwn** [comment]
Tested on `Version: 0.110.2.post1`. `covalent start && covalent stop && covalent start --no-cluster` does not activate Dask execution.
