### ISSUE TITLE
Reliably starting covalent from a jupyter notebook

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#696]
### Environment

- **Covalent version**: 0.110.0
- **Python version**:  3.8.13
- **Operating system**: Linux/MacOS

### What is happening?

Executing `!covalent start` from a Jupyter notebook cell results in the server not starting properly. 

### How can we reproduce the issue?

Executing `!covalent start` from a Jupyter notebook cell returns a false positive because the server does not start at the default port and address.

### What should happen?

Executing `!covalent start` from a Jupyter notebook cell should successfully start the server at the default port and address.

**Comment by santoshkumarradha** [comment]
I would also vote for `ct.init(**settings_params)` just like our other brothers like dask to expose an API in python to start when starting from inside a process.

**Comment by wjcunningham7** [comment]
@AlejandroEsquivel given that you got Covalent working in Colaboratory, is there anything remaining to be done here?

**Comment by santoshkumarradha** [comment]
`!covalent start/stop` from jupyter works now :D

**Comment by santoshkumarradha** [comment]
No even though it says it has started the server indeed does not start

**Comment by wjcunningham7** [comment]
*This issue is a part of Hacktoberfest.  Closing this issue will earn you 3 points.*

**Comment by santoshkumarradha** [comment]
https://github.com/AgnostiqHQ/covalent/pull/1854 closes this
