### ISSUE TITLE
The default Dask serialization protocol fails when using Pennylane's QAOA optimizer.

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#698]
### Environment

- **Covalent version**: 0.110.0
- **Python version**: 3.8.13
- **Operating system**: Linux/MacOS

### What is happening?

The default Dask serialization protocol fails when using Pennylane's QAOA optimizer. Thus electrons that call the QAOA optimizer currently have to be executed with the Local Executor.

### How can we reproduce the issue?

A workflow/electron that uses Pennylane's QAOA optimizer will fail execution when dispatched to the Covalent server.

### What should happen?

Dask should properly serialize objects in electrons that use the QAOA optimizer.

**Comment by cjao** [comment]
Does setting [`serializers=["pickle"]`](https://distributed.dask.org/en/stable/api.html#client) help?
