### ISSUE TITLE
Unit tests for electron.py

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#705]
### Description

Electrons are a fundamental building block of the Covalent workflow. Currently, there are several integration tests for the `electron.py` module in `tests/covalent_tests/workflow/electron_test.py`. The purpose of this issue is to stimulate the [addition of unit tests](https://github.com/AgnostiqHQ/covalent/blob/master/CONTRIBUTING.md#writing-tests). Considering the size of this file, we expect several contributors to help add unit tests for the untested methods/functions. Even small additions here is impactful and greatly appreciated.

Within the unit test file, we sould like to have at least one test method corresponding to each source method. In cases where source code has branches or other logic, all logical conditions in the source should ideally be covered during unit test execution.

Below, we list possible parts of the electron module (Electron object) for you to write a test. 

- [ ] Test the __init__ method. (Assigned to: @StreakSharn) 
- [ ] Test the set_metadata method. (Assigned to: @StreakSharn) 
- [ ] Test the get_metadata method. (Assigned to: @StreakSharn)  
- [ ] Test the get_op function.
- [ ] Test the __iter__ method.
- [ ] Test the __call__ method.
- [ ] Test the wait_for method.
- [ ] Test the wait function.
- [ ] Test the electron function.
- [ ] Test the to_decoded_electron_collection function.
- [ ] Test `TYPE_CHECKING = True`
- [ ] Test the Electron iterator with `expected_unpack_values = 2`
- [ ] Test getattr with a non-`--` attribute
- [ ] Test getitem
- [ ] Test passing `backend` argument to `electron()`

### Acceptance Criteria

- [ ] Look through the code and select a section of the electron module that you'd like to write tests for.
- [ ] On the issue ask to be assigned to the specific method/function test that you'd like to contribute (ensure that someone else isn't working on it already).
- [ ] Write the test(s) (making sure it passes).

### More details on running tests and measuring code coverage

Covalent uses `pytest` to run unit tests.  The pre-requisite requirements can be installed with `pip install -r tests/requirements.txt` and then run using `pytest` as follows:

```
pytest -vv tests/covalent_tests/workflow/electron_test.py --cov=covalent/_workflow/electron.py
```

Note that pull requests will generate a code coverage report on [Codecov](https://app.codecov.io/gh/AgnostiqHQ/covalent/).  This report is then posted as a comment so that coverage may be inspected line-by-line.

**Comment by scottwn** [comment]
When trying to write the `getattr` tests, I saw this comment that refers to "magic functions". What is a magic function?
https://github.com/AgnostiqHQ/covalent/blob/62920abba32457e0f8049cf2baa2f63ffbdf8c83/covalent/_workflow/electron.py#L246-L250

**Comment by StreakSharn** [comment]
Hey, could I take this? I'll work on building tests __init__, set_metadata, and get_metadata. 
I'll try to understand Electrons better when I'm doing that so I can create a few more tests later on.

**Comment by FyzHsn** [comment]
> Hey, could I take this? I'll work on building tests **init**, set_metadata, and get_metadata. I'll try to understand Electrons better when I'm doing that so I can create a few more tests later on.

Hi @StreakSharn, that would be great! I'm going to add your name beside the tests you're interested in. And if you're interested in adding more tests later, feel free to let me know. 

Really appreciate your contribution! 😃

**Comment by StreakSharn** [comment]
Thanks! I was following [CONTRIBUTING.md](https://github.com/AgnostiqHQ/covalent/blob/develop/CONTRIBUTING.md), and I don't quite understand a problem I'm having.
When running `python setup.py webapp` after executing all the previous steps, I get:
`running webapp
error: [WinError 2] The system cannot find the file specified`

I haven't made changes apart from adding `encoding='utf-8'` to setup.py, since it couldn't decode README.md. Would you know what file the system can't find, and how I could solve the error?

**Comment by FyzHsn** [comment]
> 

Hi @StreakSharn, one thing I can think of is to check whether you're running `python setup.py webapp` from the root `covalent` directory. If you're in some other subdirectory, that might explain why the system is not able to find the specified file.

Let me know if that fixes it!

**Comment by wjcunningham7** [comment]
@StreakSharn the `WinError` suggests to me you are using Windows.  Covalent does not currently support Windows.  For a list of supported platforms, see [this](https://covalent.readthedocs.io/en/stable/getting_started/compatibility.html) page.
