### ISSUE TITLE
Unit tests for lattice.py

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#706]
### Description

Lattices are a fundamental building block of the Covalent workflow. Currently, there are several integration tests for the `lattice.py` module in `tests/covalent_tests/workflow/lattice_test.py`. The purpose of this issue is to stimulate the [addition of unit tests](https://github.com/AgnostiqHQ/covalent/blob/master/CONTRIBUTING.md#writing-tests). Considering the size of this file, we expect several contributors to help add unit tests for the untested methods/functions. Even small additions here are impactful and greatly appreciated.

Within the unit test file, we would like to have at least one test method corresponding to each source method. In cases where source code has branches or other logic, all logical conditions in the source should ideally be covered during unit test execution.

Below, we list possible parts of the lattice module (Lattice object) for you to write a test. 

- [ ] `serialize_to_json`
- [ ] `deserialize_from_json`
- [ ] `set_metadata`
- [ ] `get_metadata`
- [ ] `build_graph`
- [ ] `persist`
- [ ] `__call__`
- [ ] `lattice` (wrapper function)

### Acceptance Criteria

- [ ] Look through the code and select a section of the lattice module that you'd like to write tests for.
- [ ] On the issue, ask to be assigned to the specific method/function test that you'd like to contribute (ensure that someone else isn't working on it already).
- [ ] Write the test(s) (making sure it passes).

### More details on running tests and measuring code coverage

Covalent uses `pytest` to run unit tests.  The pre-requisite requirements can be installed with `pip install -r tests/requirements.txt` and then run using `pytest` as follows:

```
pytest -vv tests/covalent_tests/workflow/lattice_test.py --cov=covalent/_workflow/lattice.py
```

Note that pull requests will generate a code coverage report on [Codecov](https://app.codecov.io/gh/AgnostiqHQ/covalent/).  This report is then posted as a comment so that coverage may be inspected line-by-line.

**Comment by mpvgithub** [comment]
I would like to look into this issue / write these unit tests. Kindly assign this issue to me. @wjcunningham7

**Comment by FyzHsn** [comment]
> I would like to look into this issue / write these unit tests. Kindly assign this issue to me. @wjcunningham7

Hi @mpvgithub, thanks for looking into this! Let us know if you have any questions.

**Comment by mpvgithub** [comment]
@wjcunningham7 
I tried some test cases with the lattice wrapper function. When I came across the DepsBash test case, I pointed some basic file write bash commands to the lattice decorator

```
@ct.lattice(
        call_before=ct.DepsCall(call_before_lattice),
        deps_bash=DepsBash(["echo 'Hello World' >> /tmp/path.txt"]),
        call_after=ct.DepsCall(call_after_lattice),
    )
```
But when I tried to get the result ( read text from path.txt )
```
def read_file():
        with open('/tmp/path.txt','r') as f:
            return f.read()
```
I get this following error :- **No such file or directory: /tmp/path.txt**

is **DepsBash** expected behavior for lattice or can also be used for both lattice and electron?

Reference : https://covalent.readthedocs.io/en/stable/concepts/concepts.html?highlight=DepsBash#depsbash

CC: @scottwn
