### ISSUE TITLE
Remove remaining references to old topological sort

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#714]
PR #700 replaces the previous "topological sort" in the core dispatcher. It remains to clean up the remaining two references to `get_topologically_sorted_graph()`.

*  `Lattice.check_constraint_specific_sum`; Covalent doesn't currently support consumable constraints and this code can be safely deleted.
 *  `Result._write_dispatch_to_python_file`; this appears to reconstructs the workflow source from the Transport Graph. This should be modified to not use get_topologically_sorted_graph.

**Comment by venkatBala** [comment]
@cjao  this can be closed now right?

**Comment by cjao** [comment]
There is still one more reference in `lattice.py` in `check_constraint_specific_sum()`. That looks like obsolete code (the calling function `check_consumable()` is never used. @scottwn  Can we just delete those two functions?

**Comment by scottwn** [comment]
yes please delete them
