### ISSUE TITLE
Ensure that Covalent How to links correspond to the correct hyperlinks

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#72]
Currently, the hyperlinks in the Collection section of How-To's do not correspond to the actual titles. Ensure that the proper hyperlinks are attached to the section titles.

**Comment by rachana-uniyal** [comment]
Hello FyzHsn,
I would like to work on this issue.

**Comment by FyzHsn** [comment]
> Hello FyzHsn,
> I would like to work on this issue.

That sounds great!
