### ISSUE TITLE
QA feedback on OS theme

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#736]
**Description**
Attend to any pending feedback points from Soc on the OS web app theme

Figma template :
[https://www.figma.com/file/uob78GrXC0l4iLo6Ux9FJx/OS-UI?node-id=592%3A11629](url)

**Comment by mshkanth** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Psi-Engineers-6220381c7f976300196f8756/issues/AgnostiqHQ/covalent/736?planning-poker) with ZenHub @amalanpsiog @Prasy12

**Comment by mshkanth** [comment]
@Prasy12 - Can you see if anything is pending on this?

**Comment by Prasy12** [comment]
This can be closed @mshkanth
