### ISSUE TITLE
Generate codecov reports by domain

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#739]
### What should we add?

We should have 4 separate codecov reports instead of 1. 1 report each for [SDK](https://github.com/AgnostiqHQ/covalent/tree/develop/covalent) [unit tests](https://github.com/AgnostiqHQ/covalent/tree/develop/tests/covalent_tests), [dispatcher](https://github.com/AgnostiqHQ/covalent/tree/develop/covalent_dispatcher) [unit tests](https://github.com/AgnostiqHQ/covalent/tree/develop/tests/covalent_dispatcher_tests), [UI](https://github.com/AgnostiqHQ/covalent/tree/develop/covalent_ui) unit tests, and [functional tests](https://github.com/AgnostiqHQ/covalent/tree/develop/tests/functional_tests). This task should also include cleaning up the `tests` folder structure, like for example `electron_return_value_test.py` should not be in the root of `tests`. The [tests workflow](https://github.com/AgnostiqHQ/covalent/blob/develop/.github/workflows/tests.yml#L120) will have to be enhanced to upload different reports for the different domains. Consider using the [`paths-filter`](https://github.com/dorny/paths-filter) action to check for paths to test as is done [elsewhere in our CI](https://github.com/AgnostiqHQ/covalent/blob/develop/.github/workflows/changelog.yml#L45).

**Comment by scottwn** [comment]
We may want to report "core" coverage vs "beta" coverage. Feature flags are probably the way to do that.

**Comment by Emmanuel289** [comment]
> We may want to report "core" coverage vs "beta" coverage. Feature flags are probably the way to do that.

@scottwn  please could you provide a bit more context on what components of Covalent be flagged as core and beta when generating the coverage reports.

**Comment by scottwn** [comment]
I think the "core" vs "beta" is out of scope for now until we implement feature flags. The breakdown should follow the original issue description.

**Comment by Emmanuel289** [comment]
> I think the "core" vs "beta" is out of scope for now until we implement feature flags. The breakdown should follow the original issue description.

Okay, thanks!
