### ISSUE TITLE
Execute File Transfer post/pre electron execution

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#747]
## Acceptance Criteria

- Should be able to decorate electrons with file transfer objects to perform io operations post and prior to electron execution

**Comment by santoshkumarradha** [comment]
@AlejandroEsquivel , quick comment can we make the second part optional requirement ? i.e. user being able to file transfer without needling to have arg/kwargs (the code they are running might use the file in non pythonic interface). So something like
```python
@ct.electron(ct.file....(from=...,to=...))
def my_function(): #Note that non existence of file input arg/kwarg
   bash('echo "hello world">>my_copied_file')
```

**Comment by AlejandroEsquivel** [comment]
@santoshkumarradha the acceptance criteria was updated to remove the second requirement, so the corresponding PR only performs file transfer without the files arg. I will make a note of that however (making the files arg optional) for the upcoming task to add return values to CallDeps
