### ISSUE TITLE
Dynamic workflows supercharged

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#761]
Electrons cannot currently be used in control-flow statements (`if`, `for`, `while`) when constructing a workflow. Expressions like `if electron > 2`, `while (electron_1 > electron_2)`, `for i in electron_that_returns_an_iterable`, aren't meaningful. Consequently, in most cases the entire workflow transport graph is submitted at once and doesn't change throughout the workflow. However, **the basic design of Covalent doesn't inherently require a static transport graph**; Indeed, sublattice graphs are already built during execution.

It is currently impossible to evaluate control-flow expressions involving electrons because `build_graph()` runs through the entire workflow to build out the transport graph. 

It takes just some minor adjustments remove the control-flow limitation.

Some preliminary observations:
1. Recall that dispatching a lattice involves two steps: `build_graph()`, and `submit`ting the lattice with its transport graph to the dispatcher server:
```python
def dispatch(lattice, args, kwargs):
    new_lattice = lattice.build_graph(args, kwargs) # new_lattice is populated with the transport graph, and workflow args
    dispatch_id = submit(new_lattice)
    return dispatch_id
```
Normally `submit` is asynchronous and returns immediately; `dispatch_sync` is implemented by a synchronous submit function, say, `submit_sync`:
```python
def submit_sync(lattice) -> Result:
    dispatch_id = submit(lattice):
    wait(dispatch_id) # wait for the dispatcher to finish running the submitted computational graph
    return get_result(dispatch_id)
```
(In covalent, the `wait` mechanism basically amounts to polling the `result.pkl` until the result status becomes `COMPLETED` or `FAILED`, but it's not hard to imagine more efficient implementations.)

2. If the dispatcher server merely runs a submitted lattice's computational graph without postprocessing the workflow, it doesn't require the graph to actually model the complete workflow. In fact the graph need not correspond to the workflow at all. 

3. Typical control flow statements are evaluated by calling some magic method to test for (in)equality or determine the truth value of an expression. For example:
* To evaluate `if a == b` one first evaluates `a == b`, which is actually computed by the `__eq__` magic method `a.__eq__(b)`. 
* To evaluate `if a:`, one evaluates whether `a` is `True` by calling `a.__bool__()`
* To evaluate `for i in a`, python first creates an iterator by calling `iter(a)`, which in turn invokes `a.__iter__()`.

*Proposal*: During `build_graph()`, for each of the Electron's magic methods `__le__`, `__eq__`, `__iter__`, etc, just `submit_sync` the partially-built transport graph without postprocessing:

For example, something like
```python
def __eq__(self, other):
        if active_lattice := active_lattice_manager.get_active_lattice():
                res = submit_sync(active_lattice, post_process=False):
                # [update existing nodes with their outputs]
                value_of_self = res.lattice.get_node_value(self.node_id, "output")
                if isinstance(other, Electron):
                        value_of_other = res.lattice.get_node_value(other.node_id, "output")
                else:
                        value_of_other = other
                return value_of_self == other
```

The key is that when two electrons are compared, both sides are defined earlier in the workflow and are therefore both already in the transport graph. Hence both `self` and `other` have a `node_id`.

With this change, `build_graph` would dynamically build out the graph, pausing whenever electrons are encountered in control flow statements to resolve the value of those electrons. This graph building process can be performed automatically by the server using the `workflow_executor` introduced in #748, using the fact that transport graphs are now JSON-serializable so the the dispatcher can receive the transport graph from the `workflow_executor` as a JSON string.

To implement this efficiently one should only `submit_sync` the newly added nodes (nodes without outputs) and edges.

**Comment by wjcunningham7** [comment]
@cjao can this be closed as completed?

**Comment by cjao** [comment]
This approach differs somewhat from the sublattices method in that it would be fully automatic -- but also more involved to design and implement. @santoshkumarradha Is the sublattice method good enough for now?

**Comment by santoshkumarradha** [comment]
@cjao not a super high priority right now, lets add this as a backlog.

**Comment by santoshkumarradha** [comment]
@cjao just checking in with recent sublattice changes, how trivial (non trivial) is it to directly support control sequences in lattice? Also keep in mind that lattice execution can take place in cloud with workflow executor which is default in non local case.
