### ISSUE TITLE
Update README reference to migration guide

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#767]
Either add migration guide to RTD or remove reference from README

**Comment by scottwn** [comment]
@AlejandroEsquivel bumping this issue, cc @wjcunningham7 @santoshkumarradha

**Comment by wjcunningham7** [comment]
This was not resolved -- there is still a line in the README's installation section about a guide that does not exist.

**Comment by AlejandroEsquivel** [comment]
@wjcunningham7 @scottwn will create PR to remove reference from README
