### ISSUE TITLE
CLI tool: implement covalent migrate

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#769]
Add functionality via CLI tool to migrate 

## Acceptance criteria

- [x] If there are migrations which have not yet run when attempting to start covalent via `covalent start` or `covalent restart` this should warn the user that they need to run `covalent db migrate`
- [x] As a covalent user when using cli command `covalent db migrate` this should run the migrations which have not yet run (programatically) [Note: refer to `covalent/_data_store/datastore.py` as `DataStore` class has `run_migrations` method]
- [x] As a covalent user when using cli command `covalent db alembic {command}` this should run the subprocess command `alembic {command}`
- [x] Unit tests with patch test coverage >= 90%.

## Additional Notes

- Exact warning message to run for first requirements are TBD, put place holder for now

**Comment by scottwn** [comment]
@AlejandroEsquivel do you have a status update on this issue?
