### ISSUE TITLE
Simplification of Executor UX

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#771]
## Acceptance Criteria

- As a covalent user I should be able to create custom executor plugins with minimal boilerplate code

## Notes

Currently there is a lot of boiler plate for executer plugin, We need to make it easy to create custom executers without all the fancy bells. For example, all the user needs to construct could be made into this

```jsx
class BaseAsyncExecuter:
	...

something = executer.pull()
```

## User

```python
class MyExecuter(BaseAsyncExecuter):
	def __init__(cores):
			self.cores=cores
			
	
	def execute(self,func,*args,**kwargs)
			print(self.cores)
      result=func(*args,**kwargs)
			
			result+=self.executer_params
      return result

	def pull(self):
    ....
			

executer=MyExecuter(cores=3)
```

In baseexecuter, we can wrap this self.execute function with something else that does various things we are doing right now, like setting status to running, changing conda env, module loading etc... Ideally we want users to do as minimal things as possible to create plugins. Inspiration from prefect’s

**Comment by AlejandroEsquivel** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/AQ-Engineers-61a12f9cbea1d7000f1b919b/issues/AgnostiqHQ/covalent/771?planning-poker) with ZenHub @kessler-frost

**Comment by cjao** [comment]
Where is the user expected to specify other relevant state to the executor, such as SSH credentials or Slurm options? Are the existing base init options like `log_stdout, log_stderr`, still going to be customizable by the user?

**Comment by kessler-frost** [comment]
> Where is the user expected to specify other relevant state to the executor, such as SSH credentials or Slurm options?
That will depend on the user when they create the executor, we will only be providing an interface to the main executable function.

> Are the existing base init options like log_stdout, log_stderr, still going to be customizable by the user?
Yes, for more advanced users, they will just access these values from `super` if needed.
