### ISSUE TITLE
Clarifications & proposal for additions/modifications to new OS DB schema

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#776]
**Description**
1. To contain clarifications from Team Psi on the new proposed OS DB schema
2. To propose additions/modifications to the DB schema and discuss them

**Comment by mshkanth** [comment]
Hi @FyzHsn - Tagging you since believe you are owning the DB schema. Request you to go through the clarifications & additions above. Pls re-assign as you see fit.

Cc @santoshkumarradha @scottwn @wjcunningham7

**Comment by FyzHsn** [comment]
> **Summary of initial clarifications**
> 
> Sno	Original schema reference	New schema reference	Description	Response
> 1	graph.links	electron_dependency	What earlier used to be a link inside graph.links will not be a record inside electron_dependency. Correct? Nothing other than links will be stored here?	electron_dependency stores the same information as graph.links
> 2	graph.links	electron_dependency	Each link used to have a source & target attribute. Is the source now electron_dependency.parent_electron_id and target is now electron_dependency.electron_id?	Yes
> 3	graph.links.key	NA	Original schema has a [key] attribute in each link. Not sure if it is used anywhere yet.	The key is used to differentiate different edges between the same two nodes. It was introduced when we replaced the nx.DiGraph by a nx.MultiDiGraph. We don’t explicitly use it. The electron_dependency table can store multiple edges.
> 4	graph.nodes[].name	electrons.type	What earlier used to be embedded inside the name ‘parameter:abc’ is being abstracted away into electrons.type. Correct?	The combination of electrons.type and electrons.name
> 5	graph.nodes[].value	NA	Sometimes there is a [value] attribute inside graph.nodes[] if the node is a parameter. Where is it available in the new schema?	We will add this column to the electrons table. Thanks!
> 6	graph.nodes[]	NA	There are 3 attributes ‘doc’, ‘sublattice_result’ ‘kwargs’ earlier maintained inside graph.nodes[]. I suppose these weren’t needed and hence discarded?	Correct. “doc” and “kwargs” were never used, and sublattice_result can be looked up in the lattices_table.
> 7	graph.nodes[].metadata.executor	electron_dependency.executor_filename	What will the executor file contain? In the previos schema there were 7 attributes maintained inside the ‘executor’ attribute. Where are these planned to be stored? Inside ‘info_filename’? Similarly for the lattice.	The executor file will contain either a pickled string describing the executor (such as “local”) or a pickled instance of BaseExecutor.
> 8	NA	NA	I see an approach where the function string, result, executor, error, stderr and stdout are all now mantained in the file system. Do you expect a few things like say stderr to be so large that it needs to be stored outside the DB? Ones like result are understandable since they might be large files. I suppose everything has been stored on the file system to maintain some consistency?
> 
> One by product of this approach is that, for every graph page or dashboard page load will potentially have to read from multiple files at a time. This might not have an impact now. But requirements like “search for any workflow which contains an error text ” will be complex. Essentially, this design will simplify/complicate certain types of requirements on the GUI in the future. We can maybe re-factor the DB then and introduce additional columns.	We can implement a helper function to return the raw logs. Let's come back to re-design the schema if performance becomes an issue.
> 9	NA	electron_dependency.info_filename	What all will info_filename contain?	From Will: this file will store "stuff from the multiprocessing info queue generated at execution time, such as a slurm job ID... or rather a filename pointing to an object with that data"
> 10	NA	NA	Can we add number of completed electrons & number of total electrons also to the lattices table? Makes sorting/search easier when the number of dispatches gets high.	We could. That would certainly simplify the querying required for the dashboard.
> 11	lattice.doc	NA	I suppose the doc attribute inside the lattice is no longer needed and hence dropped?	Yes, same as for graph.nodes[].doc
> 12	graph.nodes[].function_string	NA	From AQ : This isn’t stored in the DB but it can be computed from the serialized function using `get_serialized_function_string`.	Will add a column corresponding to this.
> **Clarifications**
> 
> 1. Will `storage_path` in lattices & electrons store an absolute path?

I'm assuming that it'll have to be an absolute path for it to be useful. Do you have any preferences or thoughts on this?

> 2. We noticed a few extra columns after running @scottwn 's DB populating script Eg `storage type`, `arg index` etc. Can you add them to the DB schema diagram and share an updated copy?
> 3. How/In what way is 'value_filename' different from 'results_filename' in the electrons table? Also, can you help us with what will be stored in columns 'attribute' & 'key' in the electron table?
> 4. Can you share possible/known values for `lattices.status`, `electrons.status` and `electrons.type`?
> 5. Incase of a lattice having sub lattices, does `parent_lattice_id` store the `lattices.id` of the immediate parent (sub lattice) or does it store the id of the root lattice?
> 6. Imagine a workflow like below - ![Sub lattice use case](https://user-images.githubusercontent.com/23229840/177579491-313d5d22-d133-4005-a65c-4e83e2da0752.png)
>    How many records will the `lattices`and `electrons` tables have?
> 
> **Additions**
> 
> 1. Can we add `number of completed electrons` & `number of total electrons` also to the lattices table? There is a need to sort by these on the GUI and computing it while sorting is a costly exercise at scale.

Yes, added in V10 of the DB schema already! My apologies, I was supposed to put it back in earlier.

>    _Possible implementations -
>    a. Maintain these columns from the dispatcher itself. ie Whenever the dispatcher updates the `electrons` table, it will also update the `number of completed electrons`
>    b. Delegate it as a DB responsibility For Eg as a Trigger (Performance implications to be studied)_

**Comment by Prasy12** [comment]
@ArunPsiog @mpvgithub @Aravind-psiog

**Comment by mshkanth** [comment]
Hi @FyzHsn - We went through the DB implementation of v9. Wanted to clarifiy the following

**Clarifications on actual DB implementation - v9**

1. Two files `result.pkl` and `results.pkl` are generated. `results.pkl` is the file referenced in the DB but is empty. `result.pkl` has data. Pls let us know which of these will be retained. 
2. The `lattices` table contains a `executor_filename`. This `dispatcher.pkl` one one instance only had a string 'Dask'. In an earlier example, we have seen that it contained an iterable object containing attributes & values. Which of these two will be it for the `lattices` referenced `executor_filename` & `electrons` referenced `executor_filename` ?

**Comment by FyzHsn** [comment]
> Hi @FyzHsn - We went through the DB implementation of v9. Wanted to clarifiy the following
> 
> **Clarifications on actual DB implementation - v9**
> 
> 1. Two files `result.pkl` and `results.pkl` are generated. `results.pkl` is the file referenced in the DB but is empty. `result.pkl` has data. Pls let us know which of these will be retained.

Ah that looks like a type. I'll stick to the Database schema.

> 2. The `lattices` table contains a `executor_filename`. This `dispatcher.pkl` one one instance only had a string 'Dask'. In an earlier example, we have seen that it contained an iterable object containing attributes & values. Which of these two will be it for the `lattices` referenced `executor_filename` & `electrons` referenced `executor_filename` ?

I'm not sure what you mean by `dispatcher.pkl`.  The `executor` field in the Result metadata sometimes contains a string `dask` / `local` and sometimes an Executor object. The current implementation simply pickles what's in the Result object metadata which is why some examples have an actual executor while others have a string name.

**Comment by mshkanth** [comment]
@FyzHsn 

> I'm not sure what you mean by `dispatcher.pkl`.
That was a typo. Should have been `executor.pkl`

> The `executor` field in the Result metadata sometimes contains a string `dask` / `local` and sometimes an Executor object. 
We are currently referring to the executor.pkl file that is referenced under executor_filename DB field to fetech any executor related information. Should we be looking at this or the results.pkl file for any executor information?

> The current implementation simply pickles what's in the Result object metadata which is why some examples have an actual > executor while others have a string name.
Will this implementation stay or will it switch to either in the stable implementation? Rather - Do you think we should handle both possibilities and not expect one format over the other?

**Comment by FyzHsn** [comment]
> @FyzHsn
> 
> > I'm not sure what you mean by `dispatcher.pkl`.
> 
> That was a typo. Should have been `executor.pkl`
> 
> > The `executor` field in the Result metadata sometimes contains a string `dask` / `local` and sometimes an Executor object.
> 
> We are currently referring to the executor.pkl file that is referenced under executor_filename DB field to fetech any executor related information. Should we be looking at this or the results.pkl file for any executor information?
> 
> > The current implementation simply pickles what's in the Result object metadata which is why some examples have an actual executor while others have a string name.
> 
> Will this implementation stay or will it switch to either in the stable implementation? Rather - Do you think we should handle both possibilities and not expect one format over the other?

For the near term, could you handle both possibilities? Later on we can ensure that the string gets replaced by the actual executor when it's stored in the result object.

**Comment by mshkanth** [comment]
> For the near term, could you handle both possibilities? Later on we can ensure that the string gets replaced by the actual executor when it's stored in the result object.

Sure

> We are currently referring to the executor.pkl file that is referenced under executor_filename DB field to fetech any executor related information. Should we be looking at this or the results.pkl file for any executor information?

Can you clarify this? @FyzHsn

**Comment by FyzHsn** [comment]
> 

When the electron object is defined, the user can input executor=SomeExecutorObject() or executor="dask" or executor="local". I think the fix should be that when the metadata is stored, the result object should store the actual objects and not the string. Then the database would only pickle the executor objects instead of sometimes the "dask" and "local" string.

**Comment by mshkanth** [comment]
> _Note - Pls check history for versions_
> 
> Hi @FyzHsn - We went through the DB implementation of v9. Wanted to clarifiy the following
> 
> **Clarifications on actual DB implementation - v9**
> 
> 1. ~Two files `result.pkl` and `results.pkl` are generated. `results.pkl` is the file referenced in the DB but is empty. `result.pkl` has data. Pls let us know which of these will be retained.~ What is in the DB will be the final implementation
> 2. ~The `lattices` table contains a `executor_filename`. This `executor.pkl` one one instance only had a string 'Dask'. In an earlier example, we have seen that it contained an iterable object containing attributes & values. Which of these two will be it for the `lattices` referenced `executor_filename` & `electrons` referenced `executor_filename` ?~ Team Psi to consider this file dynamic and handle both scenarios in the short term - Pure string & Iterable object. `Executor.pkl` is the correct file for the GUI to read executor data.
> 3. `function_string_filename` to continue being the source of data for the function string for the web app.
> 4. `function_string_filename`, `error` & `info` log contain a mix of string & bytes. This will be corrected to only string in the next DB implementation release.
> 5. `electron_id` column in lattices table to be populated when the record belongs to a sub lattice. This will be implemented in the next DB implementation release.

@FyzHsn - Updated takeaways from thursday's discussion in the above [comment](https://github.com/AgnostiqHQ/covalent/issues/776#issuecomment-1183319727)

**Comment by mshkanth** [comment]
**Consolidation of all fixes & schema enhancement requests from Team Psi**

1. Fixes
a. `executor.pkl` to only contain an iterable object with all executor details. 
b. `electron_id` column in `lattices` table to be populated when the record belongs to a sub lattice.
c. Some files contain a mix of bytes & string content. All files to be uniform and per schema spec Eg `function_string_filename`, `error` & `info` log to only contain string, but today has a mix of bytes & string. 
d. Only one result file should be generated and should be correctly linked in the DB. Currently two files `result.pkl` and `results.pkl` are generated. `results.pkl` is the file referenced in the DB but is empty.

2. Schema modifications
a. An `is_active` integer field to be added to all 3 tables and defaulted to 1.
b. A `number of completed electrons` column to be introduced to the `lattices` table. This column is to be updated everytime an electron completes execution.
c. A `total number of electrons` column to be introduced to the `lattices` table. This column to contain the total number of electrons in that lattice

**Comment by FyzHsn** [comment]
> **Consolidation of all fixes & schema enhancement requests from Team Psi**
> 
> 1. Fixes
>    a. `executor.pkl` to only contain an iterable object with all executor details.

Added an [issue](https://app.zenhub.com/workspaces/aq-engineers-61a12f9cbea1d7000f1b919b/issues/agnostiqhq/covalent/854) for that.

>    b. `electron_id` column in `lattices` table to be populated when the record belongs to a sub lattice.

This was fixed last week. Can you confirm that you're still seeing issues with this?

>    c. Some files contain a mix of bytes & string content. All files to be uniform and per schema spec Eg `function_string_filename`, `error` & `info` log to only contain string, but today has a mix of bytes & string.

I'm simply storing pickled files here. Not sure what you mean by a mix of bytes and string. In any case, here's an [issue](https://app.zenhub.com/workspaces/aq-engineers-61a12f9cbea1d7000f1b919b/issues/agnostiqhq/covalent/853) to store the txt and log files as text.

>    d. Only one result file should be generated and should be correctly linked in the DB. Currently two files `result.pkl` and `results.pkl` are generated. `results.pkl` is the file referenced in the DB but is empty.

All the output files that are stored are now called `results.pkl`. In either case, why is the hard coded path being used? Wouldn't it be better to use the Filename path stored in the DB? i

> 2. Schema modifications
>    a. An `is_active` integer field to be added to all 3 tables and defaulted to 1.

Here's the [issue](https://app.zenhub.com/workspaces/aq-engineers-61a12f9cbea1d7000f1b919b/issues/agnostiqhq/covalent/786) for it.

>    b. A `number of completed electrons` column to be introduced to the `lattices` table. This column is to be updated everytime an electron completes execution.
>    c. A `total number of electrons` column to be introduced to the `lattices` table. This column to contain the total number of electrons in that lattice

The issue for points b and c is [here](https://app.zenhub.com/workspaces/aq-engineers-61a12f9cbea1d7000f1b919b/issues/agnostiqhq/covalent/858).

**Comment by mshkanth** [comment]
https://github.com/AgnostiqHQ/covalent/issues/906

**Comment by mshkanth** [comment]
https://github.com/AgnostiqHQ/covalent/issues/900

**Comment by FyzHsn** [comment]
@mshkanth Can this issue be closed?

**Comment by mshkanth** [comment]
> @mshkanth Can this issue be closed?

My bad. Missed the notification. Have assigned this to myself for any final vetting out required.

**Comment by FyzHsn** [comment]
> > @mshkanth Can this issue be closed?
> 
> My bad. Missed the notification. Have assigned this to myself for any final vetting out required.

Thank you sir!

**Comment by wjcunningham7** [comment]
@mshkanth can this be closed as completed?

**Comment by santoshkumarradha** [comment]
@mshkanth closing this for now assuming this is resolved.
