### ISSUE TITLE
Julia integration

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#782]
[Julia leptons](https://github.com/AgnostiqHQ/covalent/pull/183) were closed without merging a couple months back. 

We need to document the right plan for supporting Julia leptons as well as inline julia (`ct.electrons.julia`).

[Notion page](https://www.notion.so/Plan-Julia-integration-638fedb7f76e4d2a937848f0d6c95546)

**Comment by wjcunningham7** [comment]
use this example to prototype and test julia leptons: https://github.com/FluxML/model-zoo/tree/master/vision/dcgan_mnist
