### ISSUE TITLE
Update Database version to V10 and implement corresponding changes

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#786]
The purpose of this issue is to ensure that the the database schema is updated and the corresponding implementations are made in `Result.persist()` and the related helper methods.

**Acceptance criteria:**

- [x] Update the DB schema to V10 (from V9) and include the newly introduced metadata such as deps, call_after, call_before, is_active etc.
- [x] Add new fields to the model.py:
    - [x] Electron.deps_filename 
    - [x] Electron.call_before_filename
    - [x] Electron.call_after_filename
    - [x] Electron/Lattice/Electron_dependency.is_active + default to boolean value True.
    - [x] Electron_dependency.updated_at
- [x] Make changes to `Result.persist` and write_result_to_db.py methods to include functionality to store:
   - [x] Electron.deps_filename 
    - [x] Electron.call_before_filename
    - [x] Electron.call_after_filename
- [x] Ensure that the code has a coverage >= 90%.

**Comment by scottwn** [comment]
note this discussion re: schema https://github.com/AgnostiqHQ/covalent/discussions/778

**Comment by FyzHsn** [comment]
@mshkanth This issue / acceptance criteria defines the scope for what will be delivered at the end of V10 implementation. Notice that logic to change `is_active` field is not included since the implementation strategy / requirements are not well defined.

**Comment by mshkanth** [comment]
> @mshkanth This issue / acceptance criteria defines the scope for what will be delivered at the end of V10 implementation. Notice that logic to change `is_active` field is not included since the implementation strategy / requirements are not well defined.

I understand @FyzHsn. Can we include the field alone in v10 and default it to `is_active = true`? This way, if there is consensus on the Web app updating it, then we do not need to wait for the column to be introduced. Else, if you feel it is too much back/forth, we can wait for complete consensus and then take it up.

**Comment by FyzHsn** [comment]
Reminder that this issue should be broken down into smaller PR's.
