### ISSUE TITLE
Support for Return Values in CallDeps

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#790]
## Acceptance Criteria

- As a covalent user I want to get return values of calldeps into an electron's function

```python

@electron(
  files=[FileTransfer()]
)
function read_file(files=[]):
   pass
```

**Comment by cjao** [comment]
This would involve nontrivial changes in terms of both UX and the backend.

When users construct a workflow today, they pass to each electron either other electrons or fixed parameters. In the latter case, each parameter is assigned a node in the computational graph. The graph completely describes the input-output relationships between electrons and parameters.

The proposed behavior is to inject arguments to electrons at runtime from the return values of call deps. I have a few concerns:

* (UX) Unless users specify default arguments for an electron, there is no natural way to call the electron during workflow construction without supplying its arguments.
* (UX) Even if users provide default arguments (say, a dummy file path in the above sample), the workflow would produce different results depending on whether it is dispatched as a Covalent workflow or executed as a normal Python function. We take great pains today to make Covalent as transparent a layer as possible.
* (UX/Backend) The transport graph can certainly be taught to omit edges for arguments to be injected at runtime. However, the more computations that occur outside the graph, the less useful the graph becomes for reasoning about the workflow.

**Comment by cjao** [comment]
This will need follow up UI work to display the injected parameters in the workflow view.
