### ISSUE TITLE
Meaningful errors for non-lattice dispatches

### ISSUE THREAD

**Issue by santoshkumarradha** [AgnostiqHQ/covalent#793]
### Description

When an object other than `Lattice` is submitted to the dispatcher, we want to provide a helpful error message explaining what happened.  Consider this code:
```
@ct.electron
def new_func(a, b, c, d, e):
    time.sleep(10)
    return a + b + c + d + e


@ct.electron
@ct.lattice
def work_func(a, b, c):
    return new_func(a, b, c, d=4, e=5)

dispatch_id = ct.dispatch(work_func)(5, 6, 7)
print(dispatch_id)
```

Running this will produce an error like this
```
Traceback (most recent call last):
  File "example_db.py", line 246, in <module>
    dispatch_id = ct.dispatch(lattice)(*args)
  File "/home/user/covalent/covalent/_dispatcher_plugins/local.py", line 79, in wrapper
    lattice.build_graph(*args, **kwargs)
AttributeError: 'function' object has no attribute 'build_graph'
```

This arises because the object passed to the dispatcher is a sublattice (type `Electron`) and not a lattice (type `Lattice`), but it would also arise from other types being passed to the `ct.dispatch()` method.

### Acceptance Criteria
- [x] The `LocalDispatcher.dispatch` method displays a pretty message describing the error.  The type of the parameter `orig_lattice` should be validated at the start of the method.
- [x] The error message appears when a non-lattice object, such as a sublattice in the example above, is provided to the `dispatch` method.
- [x] The error message is printed using Covalent's logger, `logger.app_log`, and is raised at the `ERROR` log level.
- [x] A unit test is created in the corresponding test file, `tests/covalent_tests/dispatcher_plugin/local_test.py`.

**Comment by scottwn** [comment]
Go for it @gcamach0! thanks!

**Comment by AlejandroEsquivel** [comment]
Thanks for reaching out @gcamach0 ! I have assigned this issue to you. Let me know if you have any questions and I will do my best to answer :)

**Comment by Aravind-psiog** [comment]
@wjcunningham7 can you assign this issue to me?
