### ISSUE TITLE
Unreasonable amount of time spent in getting function string

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#80]
After a simple profiling of a covalent example, it was found that almost 98% of the total time (to dispatch) was spent in `get_serialized_function_str` inside which, It seems like getting imports is main the culprit. We need to modify/move this function so that dispatching a job doesn't take a long time when a lot of electrons are involved.

Example used for profiling:

```python
@ct.electron
@qml.qnode(qml.device('default.qubit', wires=1))
def calculate(x):
    for _ in range(30):
        qml.RX(x, wires=0)
        qml.RY(x, wires=0)
    return qml.expval(qml.PauliZ(0))

@ct.lattice
def parallalize(x_list):
    values=[]
    for x in x_list:
        values.append(calculate(x))
    return values

job_id=parallalize.dispatch(x_list=np.arange(50))
```
Time taken to dispatch ~ 2-3 minutes

Afterwards the following in `covalent/_shared_files/utils.py : get_serialized_function_str` was commented out,
```python
# imports = _get_imports_from_source()
ct_decorators = []  # _get_cova_imports(imports)
```

Then the time taken gets reduced to ~ 0.005 seconds

This issue blocks the PR https://github.com/AgnostiqHQ/covalent/pull/66 as it will most likely amplify the impact.

**Comment by wjcunningham7** [comment]
related to #66

**Comment by kessler-frost** [comment]
![img_exp](https://user-images.githubusercontent.com/17881378/154749015-6fb38371-0b0b-4c52-99b7-a2d75917d70f.png)

Difference between the develop branch and the PR https://github.com/AgnostiqHQ/covalent/pull/123.
