### ISSUE TITLE
AWS Fargate Executor Tasks Failing

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#802]
From discussion: https://github.com/AgnostiqHQ/covalent/discussions/710

In the case of the fargate executor, I followed these steps:

### AWS Configuration setup
Configured aws credentials by copying the secret_access_key, access_key_id, and session_token generated for my profile into the `~/.aws/credentials` file.  I also set the  AWS environment variables to make sure that the right variables were pulled in the event that some variables were not properly set in the `~/.aws/credentials` file.
```
export AWS_REGION="us-east-1"
export AWS_DEFAULT_REGION="us-east-1"
export AWS_DEFAULT_PROFILE=“<profile_name>”
export AWS_ACCESS_KEY_ID=“<given_value>”
export AWS_SECRET_ACCESS_KEY=“<given_value>”
```

### Verifying CLI Access to Resources 

I ran some commands to verify cli access to AWS resources, especially those required by the fargate plugin, e.g,
`aws ecs describe-clusters —cluster covalent-fargate-cluster` to inspect the fargate-cluster

### Added entries for the fargate plugin to the covalent configuration file
I updated the `covalent.conf` file with entries for the fargate plugin

### Executing an electron on the fargate executor

I tried to execute an electron in the workflow below, but the task execution failed with exit code - 1. The exception was raised by `poll_ecs_task()` in `fargate.py`.
```
@ct.electron(executor="fargate")
def my_task(x, y):
    return x + y

@ct.lattice
def workflow(x, y, z):
    res =  z + my_task(x, y)
    return res


dispatch_id = ct.dispatch(workflow)(1, 2, 3)

print(dispatch_id)

result_obj = ct.get_result(dispatch_id)

print(result_obj)
```

<img width="1512" alt="Screen Shot 2022-06-21 at 10 44 21 PM" src="https://user-images.githubusercontent.com/6232188/174946034-6134bf2c-81ce-4613-b000-fa70f81f79e2.png">
<img width="1512" alt="Screen Shot 2022-06-21 at 10 48 53 PM" src="https://user-images.githubusercontent.com/6232188/174946036-4d390bb7-fbaf-430e-81c5-4b4eedf84543.png">

**Comment by AlejandroEsquivel** [comment]
@cjao's comments:

In `_format_exec_script()` (https://github.com/AgnostiqHQ/covalent-fargate-plugin/blob/1751ac1dc1dd3ef3856e4de5f74075b9bd689140/covalent_fargate_plugin/fargate.py#L282), there is a string representation of the args and kwargs passed to the function which can't possibly work for non-json type inputs

**Comment by wjcunningham7** [comment]
@AlejandroEsquivel can this be closed?
