### ISSUE TITLE
Include node id & executor label in dispatch graph

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#814]
**Description**
To include the node id & executor label for each electron in the dispatch graph on the Web app GUI

**Mandatory acceptance criteria**
User is able to view the node id & executor label of the electron along with each electron in the dispatch graph

![image](https://user-images.githubusercontent.com/23229840/178516125-2842f3fb-b6a5-46b1-a4d6-a8d27769a5b3.png)

**Optional**
An option to show or hide the node id will help users.
An option to show or hide the exector label will help users
It will help to also show the node id & executor label as part of the electon side bar when an electron is selected

**Implementation details**

1. Electron's node ID points to the `transport_graph_node_id` in the `electrons` table. 
2. Electron's dispatcher label is available in the `dispatcher_name` column starting from v11 of the database

**Comment by mshkanth** [comment]
**Description**
To include the node id of each electron in the dispatch graph on the Web app GUI

**Mandatory acceptance criteria**
User is able to view the node id of the electron along with each electron in the dispatch graph

**Optional**
An option to show or hide the node id will help users
It will help to also show the node id as part of the electon side bar when an electron is selected

**Implementation details**

1. Most likely points to the `transport_graph_node_id` in the `electrons` table.
2. If this field is not being sent to the UI already, then the graph API & electron side bar API will need to be modified

**Comment by mshkanth** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Psi-Engineers-6220381c7f976300196f8756/issues/AgnostiqHQ/covalent/814?planning-poker) with ZenHub @ArunPsiog @Prasy12

**Comment by Prasy12** [comment]
@mshkanth Can you tell mw where exactly is the case for user viewing the node id on the UI? Is it available on Figma?

**Comment by mshkanth** [comment]
> @mshkanth Can you tell mw where exactly is the case for user viewing the node id on the UI? Is it available on Figma?

Updated description with screenshot. Yes, it is there in Figma

**Comment by mshkanth** [comment]
@Prasy12 - Updated issue to include executor label also.

**Comment by mshkanth** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Psi-Engineers-6220381c7f976300196f8756/issues/AgnostiqHQ/covalent/814?planning-poker) with ZenHub @Prasy12

**Comment by Prasy12** [comment]
We have an option to hide labels in our current GUI now and till that is present we will show the executor and node id in a tooltip when the hide label feature is enabled. For normal view the UI will be as in the screenshot above :
Without hide labels:
![image](https://user-images.githubusercontent.com/54540812/185838343-fce12e5c-16db-4273-a46d-7fc05d19c3f5.png)

With hide labels:
![image](https://user-images.githubusercontent.com/54540812/185838581-a8d12755-9f41-4d8b-b531-3b61db8438f8.png)

cc : @santoshkumarradha @mshkanth @Kamalesh-suresh
