### ISSUE TITLE
Text files are pickled without .pkl extenstions

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#837]
Split from https://github.com/AgnostiqHQ/covalent/pull/823

Consider this code
https://github.com/AgnostiqHQ/covalent/blob/c1b5790c2ddc52d29982f370b15f62d48ddba449/covalent/_results_manager/result.py#L496
https://github.com/AgnostiqHQ/covalent/blob/c1b5790c2ddc52d29982f370b15f62d48ddba449/covalent/_results_manager/result.py#L529-L530

Notice that a string is being pickled to a file with a `.txt` extension. This is confusing. These files should either have `.pkl` extensions or they should not be pickle files.

**Comment by FyzHsn** [comment]
**Acceptance criteria:**

- [ ] Ensure that .log and .txt files are being stored as text files.

**Comment by mshkanth** [comment]
> **Acceptance criteria:**
> 
> * [ ]  Ensure that .log and .txt files are being stored as text files.

@FyzHsn - Just to confirm, we will be getting text files only and not a pickled object correct?
