### ISSUE TITLE
Dask Functional Tests Unstable

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#846]
### Environment

- **Covalent version**: 0.134.0
- **Python version**: 3.8
- **Operating system**: Ubuntu 20.04

### What is happening?

Dask CLI functional tests can fail somewhat frequently in the CI pipeline.  Example [here](https://github.com/AgnostiqHQ/covalent/runs/7371490781?check_suite_focus=true)

### How can we reproduce the issue?

Analyze the CI logs

### What should happen?

Tests should always pass

### Any suggestions?

Improve the tests so they make no assumptions about prior states

**Comment by venkatBala** [comment]
@wjcunningham7 should this be closed...#845 is merged
