### ISSUE TITLE
DB filename and pickling Transportable Objects

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#853]
Currently, some of the node values that are being written to the DB field are stored as TransportableObjects which is not consistent with DB schema. Furthermore, some of the filenames are called .txt files but stored as pickle files. These need to be changed.

**Acceptance criteria:**
- [ ] Ensure that TransportableObjects are not stored in the DB fields. Rather, when loading them from the DB convert them to

**Comment by scottwn** [comment]
Separate issue for the `.log` and `.txt` files https://github.com/AgnostiqHQ/covalent/issues/837

**Comment by cjao** [comment]
To recap our Slack conversation, the schema will be updated to reflect that the files now hold TransportableObjects. The UI should not deserialize `TransportableObject`s but instead access the string representation of the decoded object via the `object_string` attribute.
