### ISSUE TITLE
Ensure that the local / dask Executor object get pickled in the DB

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#854]
Currently, if `dask` / `local` executor is specified in the metadata as a string, the actual executor is not pickled in the filename but rather the string.

**Acceptance criteria:**

- [ ] When dask / local executor string is passed into the metadata, ensure that the actual executor objects are stored instead.

**Comment by cjao** [comment]
Hi @FyzHsn , the discussion #878 may help clarify the scope of this issue.

**Comment by wjcunningham7** [comment]
@FyzHsn can this be closed?

**Comment by cjao** [comment]
Yes
