### ISSUE TITLE
Pennylane Kernel Tutorial Optimization

### ISSUE THREAD

**Issue by AnnaGwen** [AgnostiqHQ/covalent#868]
### What should we add?

The Pennylane kernel tutorial (Kernel_pennylane.ipynb) follows [this Pennylane tutorial](https://pennylane.ai/qml/demos/tutorial_kernel_based_training.html), converting it to run in Covalent. The text and content is completed, but the optimization step doesn't run properly in current Covalent versions. 
The photos below show the optimization process with and without Covalent.

<img width="484" alt="PL_optimization_with_cova" src="https://user-images.githubusercontent.com/10732247/179768609-46104682-c47c-434c-bf64-d91fa92eda05.png">
<img width="476" alt="PL_optimization_without_cova" src="https://user-images.githubusercontent.com/10732247/179768627-f992609a-3fde-426b-a9d3-7828676e16f9.png">
.

**Comment by scottwn** [comment]
@wjcunningham7 @santoshkumarradha  should we put this in backlog or icebox or close it?
