### ISSUE TITLE
AWS EC2 Executor Planning

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#872]
## Acceptance Criteria

A design document that should outline:
- Proposal of how new & existing [cloud] executors should change in order to support new hooks during the workflow lifecycle in order to provision cloud resources programatically via Terraform CDK 
- How this affects the plugin ecosystem (organization of plugins within Git and pip deployments)
- How automated testing should be performed on executors

Additional requirements:
- All terraform infrastructure code should live in the `AgnostiqHQ/terraform` repo, and in a seperate mono repo `AgnostiqHQ/cloud-executors`. Therefore there should be a mapping from a cloud executor and a folder under `AgnostiqHQ/terraform`

**Comment by Emmanuel289** [comment]
The related discussion for this issue is #893
