### ISSUE TITLE
S3 File Transfer Strategy

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#882]
## Acceptance Criteria

- [x] Add an S3 File Transfer Strategy under `covalent/_file_transfer/strategies/` to perform download, and upload operations using the AWS S3 (boto) client
- [x] Add tests for S3 File Transfer Client
- [x] Add How To Guide & Update Concepts in RTD to include information about the S3 Strategy 
-  [x]  Configuration such as access key id, secret access key, and default region should be arguments to the S3 File Transfer class but should default to the following environment variables `AWS_ACCESS_KEY_ID` , `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION`

## Additional Notes

- TransferTo functionality with implicit `from` path (i.e when not providing an explicit `from` path) is currently being developed

**Comment by scottwn** [comment]
is this awaiting further review or can it be closed?
