### ISSUE TITLE
Number of electrons & completed electrons should only reflect only 'executable' electrons

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#900]
**Description**
The columns `electron_num` and `completed_electron_num` in the `lattices` table should only include the count for actual executable electrons and not include other electron types like parameters.

**Details**

- Currently even non executable electron types are considered while populating these columns Eg `parameter` type electrons. Note the 19/19 besides 'Completed' in the image below. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/23229840/180445336-b572da7f-b3c2-44b0-a067-599983f87eb0.png)

- It is proposed to include only electrons that are executable since these two columns are shown to the end use in tandem with the graph as shown above. 
- The DB schema proposes a list of possible electon types - `function`, `sublattice`, `parameter`, `electron_list`, `electron_dict`, `attribute`, `generated`, `subscripted`, `arg`. The understanding is that only the `function` type should be considered since the end user is looking for that count.

**Comment by santoshkumarradha** [comment]
@mshkanth , I would say the list of possible "types" of electron are [listed here](https://github.com/AgnostiqHQ/covalent/blob/e7d46bc77e06c9bf93ecc2b88a581275233b1821/covalent/_shared_files/defaults.py#L28:L35) (and functional electron, which is the main normal electron that is not listed here). Following this I would say we need both sublattice/functional electron for the status.

This also reminds me, lets discuss with Soc on potentially differentiating the various forms of electrons here (Plus we need collapse in the minimap for the "types" of electrons above as well.)

**Comment by mshkanth** [comment]
> 



> @mshkanth , I would say the list of possible "types" of electron are [listed here](https://github.com/AgnostiqHQ/covalent/blob/e7d46bc77e06c9bf93ecc2b88a581275233b1821/covalent/_shared_files/defaults.py#L28:L35) (and functional electron, which is the main normal electron that is not listed here). Following this I would say we need both sublattice/functional electron for the status.
> 
> This also reminds me, lets discuss with Soc on potentially differentiating the various forms of electrons here (Plus we need collapse in the minimap for the "types" of electrons above as well.)

@santoshkumarradha - There is already a 'parameter' hide/show toggle today. We can extend it to different things potentially. Is the tweak in total/completed electron,  something we can expect for v11? Techncially it doesn't impact us at all, since we show this data from the DB directly to the GUI. However, the user might wrongly infer data shown on the screen as a result of this.

**Comment by FyzHsn** [comment]
> @mshkanth , I would say the list of possible "types" of electron are [listed here](https://github.com/AgnostiqHQ/covalent/blob/e7d46bc77e06c9bf93ecc2b88a581275233b1821/covalent/_shared_files/defaults.py#L28:L35) (and functional electron, which is the main normal electron that is not listed here). Following this I would say we need both sublattice/functional electron for the status.
> 
> This also reminds me, lets discuss with Soc on potentially differentiating the various forms of electrons here (Plus we need collapse in the minimap for the "types" of electrons above as well.)

Hey @santoshkumarradha and @mshkanth - Just FYI the logic for getting electron types is right [here](https://github.com/AgnostiqHQ/covalent/blob/1f5443cdac2ec7d5c3da46e192723165b602595e/covalent/_results_manager/write_result_to_db.py#L305). Normal electron is designated as a "function".

**Comment by mshkanth** [comment]
Hi @cjao - There were a few pending tweaks/requests we had based on v9 & v10 schema. Can you clarify if this issue is already covered in your v11 implementation? Else request @FyzHsn to share some timeline of when this might be incorporated.

**Comment by wjcunningham7** [comment]
@mshkanth can you clarify the request?

**Comment by cjao** [comment]
Hi @mshkanth, V11 doesn't yet differentiate between functional and non-functional electrons in its electron count. Actually, while parameter electrons require no processing, the other electron types, indicated by `electron_dict_prefix` or `electron_list_prefix` do actually involve a small amount of computation.

**Comment by santoshkumarradha** [comment]
@mshkanth , we can go ahead with the current implementation and consider all these electrons are same. Lets have it as backlog to make this change both from DB side as well as front end side.

**Comment by mshkanth** [comment]
> @mshkanth can you clarify the request?

The request was to maintain only count of functional electrons in `lattices.electron_num` and `lattices.total_electron_num`. These fields were introduced to primarily server the UI and might make more sense to the user if the above tweak was done.

**Comment by FyzHsn** [comment]
> > @mshkanth can you clarify the request?
> 
> The request was to maintain only count of functional electrons in `lattices.electron_num` and `lattices.total_electron_num`. These fields were introduced to primarily server the UI and might make more sense to the user if the above tweak was done.

What about sublattices? They're not categorized as functional electrons but rather sublattices

**Comment by mshkanth** [comment]
> > > @mshkanth can you clarify the request?
> > 
> > 
> > The request was to maintain only count of functional electrons in `lattices.electron_num` and `lattices.total_electron_num`. These fields were introduced to primarily server the UI and might make more sense to the user if the above tweak was done.
> 
> What about sublattices? They're not categorized as functional electrons but rather sublattices

Would request @santoshkumarradha to clarify. Whatever makes sense to a user on the GUI for a workflow with multiple sub-lattices, that count needs to be recorded in the DB.

**Comment by santoshkumarradha** [comment]
Closing as duplicate
