### ISSUE TITLE
Restore ability to query result object properties from memory

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#908]
During the initial migration to the new DB schema in #823, several methods of `Result` to query the transport graph were modified to always look up the data in the db. These are:

* `get_node_result()`
* `get_all_node_results()`
* `get_all_node_outputs()`
* `_get_node_name()`
* `_get_node_status()`
* `_get_node_output()`
* `_get_node_error()`

We will need to query the db for this information once we add the ability to resume workflows as the server would then need to rehydrate a partially executed computational graph. Presently, however, hitting the db is not yet necessary; the dispatcher  holds the entire transport graph in memory during execution. Further, these methods are also exposed to the client which also has the entire Result object in memory but doesn't have access to the server's db.

**Comment by scottwn** [comment]
@wjcunningham7 I believe this is out of scope until we support resuming workflows, is that correct?

**Comment by scottwn** [comment]
`get_node_result()` relies on `get_node_name()`, `get_node_output()`, etc., which were updated to use the in memory `Result` in #1216

`get_all_node_results()` in turn relies on `get_node_result()`

`_get_node_output()` was changed to get the output from the in memory `Result` in https://github.com/AgnostiqHQ/covalent/commit/9e321a9a97ea82a816db95b2c62b09cd00366686. `get_all_node_outputs()` relies on `_get_node_output()`.

`_get_node_status()` was changed to get status from the in memory `Result` in https://github.com/AgnostiqHQ/covalent/commit/32929263ab5defc3232f72b8da2c2fe8facf33f9

Functionality to retrieve the error from the in memory `Result` was added in https://github.com/AgnostiqHQ/covalent/commit/32929263ab5defc3232f72b8da2c2fe8facf33f9

Functionality to retrieve the node name from the in memory `Result` was added in https://github.com/AgnostiqHQ/covalent/commit/32929263ab5defc3232f72b8da2c2fe8facf33f9
