### ISSUE TITLE
Return executor info for each task

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#921]
Executors may generate potentially interesting information that are auxiliary to the task being run. These include slurm logs or perhaps profiling info. We should provide a way for the dispatcher to retrieve this information from the executor for each task run and store it in the DB.

**Comment by cjao** [comment]
[Related discussion](https://github.com/AgnostiqHQ/covalent/discussions/938)

**Comment by jimmylism** [comment]
Users can print to stdout to retrieve whatever info is desired.
