### ISSUE TITLE
Revising Executor RTD (Simplification of Executors & Async)

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#929]
## Acceptance Criteria

- Update [Executor Template](https://github.com/AgnostiqHQ/covalent-executor-template) to implement simplified UX for executor & any async functionality if needed
- Ensure existing executor documentation is in-sync with latest covalent features including simplification of executor UX & async updates and effectively acts as a tutorial to clone the executor plugin (above) and make updates to it to create a new executor (see PR https://github.com/AgnostiqHQ/covalent/pull/930)

**Comment by AlejandroEsquivel** [comment]
Duplicate Issue for executor template https://github.com/AgnostiqHQ/covalent-executor-template/issues/11

**Comment by kessler-frost** [comment]
Related issue: https://github.com/AgnostiqHQ/covalent/issues/1028

**Comment by kessler-frost** [comment]
Related Issue: https://github.com/AgnostiqHQ/covalent/issues/1028

Edit: Something to be careful about when writing the new RTDs.
