### ISSUE TITLE
Test action failed

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#93]
### Environment

- **Covalent version**: 0.24.5
- **Python version**: 3.8
- **Operating system**: Centos 7

### What is happening?

The test action failed on the develop branch: https://github.com/AgnostiqHQ/covalent/runs/5078639903?check_suite_focus=true

### How can we reproduce the issue?

Hard to reproduce.

### What should happen?

Test should pass.

### Any suggestions?

The unit test `test_dispatch_cancellation` has failed because the workflow completes before it can be cancelled.  This will not happen often, as evidenced by the test passing in the other environments.  Suggested remedy is to increase the sleep time to something very large, to ensure it absolutely cannot complete before cancellation.

**Comment by santoshkumarradha** [comment]
One can have infinite while loop in one electron to make it stay up until we cancel it.

**Comment by santoshkumarradha** [comment]
I guess you could force kill the job (dispatch) at the end of this test. We want it unbound just till this particular test completes.

**Comment by cjao** [comment]
The PR
