### ISSUE TITLE
Database migrations run after fresh install

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#962]
## Description

If one attempts to run `covalent start` and there are migrations pending we instruct the user to run `covalent db migrate`. However when a user installs a fresh version of covalent given there have been no migrations run at all we want for those migrations to run automatically without instructing the user to run the migration themselves.

## Acceptance Criteria

- [ ] Using `covalent._data_store.datastore.DataStore` class, one can use alembic functionallity to detect if there has been any migrations run from the `alembic_version` table, if there has not, then we can run the migrations automatically during `covalent start` using the `run_migrations` functionality exposed by `DataStore`
- [ ] Running `covalent start` after installing covalent in a new virtualenv should not instruct users to run migrations manually (with `covalent db migrate`) rather we want the migrations to run automatically 
- [ ] Any new DB changes (new pending migrations) should still instruct the user to run migrations (`covalent db migrate`)

**Comment by oliviacarino** [comment]
Hey, can I take this on for Hacktoberfest? Also, is this essentially automating the migrations command when updating a DB model and such?

**Comment by AlejandroEsquivel** [comment]
Hi @oliviacarino , I have updated the acceptance criteria to provide more information on the issue. Let me know if all is clear. Thanks!

**Comment by oliviacarino** [comment]
@AlejandroEsquivel thanks for clarifying the criteria! So upon fresh install, using the `covalent._data_store.datastore.DataStore` class will check whether there have been any migrations or not? If it is a fresh install and no migrations have been run, perform migrations automatically without prompting the user? Then, if it is NOT a fresh install, continue to prompt the user for running migrations when necessary?

**Comment by AlejandroEsquivel** [comment]
Yes that's exactly right @oliviacarino

**Comment by oliviacarino** [comment]
@AlejandroEsquivel I don't see the DataStore class under `covalent._data_store.datastore.DataStore` but instead see it within `covalent_dispatcher/_db/datastore.py` Is this the correct class?

**Comment by wjcunningham7** [comment]
@oliviacarino this was recently migrated from the SDK to the dispatcher module.  You're correct, that's the new location.

**Comment by AlejandroEsquivel** [comment]
Resolved by https://github.com/AgnostiqHQ/covalent/pull/1388
