### ISSUE TITLE
To maintain 'inputs' attribute in the electrons table in new database schema

### ISSUE THREAD

**Issue by mshkanth** [AgnostiqHQ/covalent#963]
**Description**
There is a need to maintain an `inputs` attribute in the `electrons` table in the new DB schema. This is a field shown on today's OS application GUI to the end user at the electron level. Ref below 

![image](https://user-images.githubusercontent.com/23229840/182545912-755d4f89-acf2-4319-a13a-4bcb804c935d.png)

**Technical implementation**
Given that all lattice & electron fields shown on the GUI are maintained as direct fields on the DB, it is requested to implement this for the `inputs` attribute also. 

Ref below comments from @FyzHsn in a Slack conversation

_Electron inputs are actually computed during run time - it's not something that might necessarily exist at first. If I had to query the inputs, I would use the electron dependency table to determine all the parents and check the output / value stored in them to determine the inputs field_

**Comment by mshkanth** [comment]
@FyzHsn & @santoshkumarradha - Logging this here, to take to closure. Right now, there is no input shown at electron level since it is not available as a field on the DB. Pls share your thoughts on how we can take this to logical closure.

**Comment by cjao** [comment]
Hi @mshkanth, Covalent determines the inputs of an electron using the transport graph -- @FyzHsn's comment
>Electron inputs are actually computed during run time - it's not something that might necessarily exist at first. If I had to query the inputs, I would use the electron dependency table to determine all the parents and check the output / value stored in them to determine the inputs field

is accurate. You can model your code on  `_get_task_inputs()` in `execution.py`.

**Comment by cjao** [comment]
Please also keep in mind that all electron inputs are encoded, and you should not attempt to decode them directly. Instead, access their string representations via `TransportableObject.object_string`.

**Comment by mshkanth** [comment]
> Please also keep in mind that all electron inputs are encoded, and you should not attempt to decode them. Instead, access their string representations via `TransportableObject.object_string`.

Thank you @cjao . Apologies for dropping the ball. Given the above inputs, I see the following as an efficient way for the web app to get electron inputs - 
1. Get a result object from a lattice record by calling `result_from(lattice_record)` defined in `results_manager`
2. Get the inputs for the above result object by calling `_get_task_inputs` defined in `execution.py`

This way, we do not need to re-write any of this core logic.

**Comment by cjao** [comment]
@mshkanth Yes, that should work.

**Comment by mshkanth** [comment]
> > Please also keep in mind that all electron inputs are encoded, and you should not attempt to decode them. Instead, access their string representations via `TransportableObject.object_string`.
> 
> Thank you @cjao . Apologies for dropping the ball. Given the above inputs, I see the following as an efficient way for the web app to get electron inputs -
> 
> 1. Get a result object from a lattice record by calling `result_from(lattice_record)` defined in `results_manager`
> 2. Get the inputs for the above result object by calling `_get_task_inputs` defined in `execution.py`
> 
> This way, we do not need to re-write any of this core logic.

Closing this as we retreived inputs at runtime using the above and no longer need to add a column to the DB
