### ISSUE TITLE
DB schema V11 implementation still does not completely capture lattice attributes

### ISSUE THREAD

**Issue by cjao** [AgnostiqHQ/covalent#975]
There are still some gaps in the schema as shown in the following example:
```python
@ct.electron
def join_words(a, b):
    return ", ".join([a, b])

@ct.electron
def excitement(a):
    return f"{a}!"

# Construct a workflow of tasks
@ct.lattice(executor="dask")
def simple_workflow(a, b):
    phrase = join_words(a, b)
    return excitement(phrase)
```
Now I do 
```python
>>> dispatch_id = ct.dispatch(simple_workflow)("Hello", "World")
>>> res = ct.get_result(dispatch_id, wait=True)
```
and compare lattice attributes:
```python
>>> res.lattice.__dict__
```
```python
{'metadata': {'executor': 'dask',
  'executor_data': {},
  'workflow_executor': 'dask',
  'workflow_executor_data': {}},
 'args': [<covalent.TransportableObject at 0x7f90e1cf6fd0>,
  <covalent.TransportableObject at 0x7f90e1cf6430>],
 'kwargs': {},
 'named_args': {'a': <covalent.TransportableObject at 0x7f90e1cf67c0>,
  'b': <covalent.TransportableObject at 0x7f90e1cf6700>},
 'named_kwargs': {},
 'transport_graph': <covalent._workflow.transport._TransportGraph at 0x7f90e1cf63d0>,
 'workflow_function': <covalent.TransportableObject at 0x7f90e1cf6730>}
```
Some keys are missing relative to the original lattice:
```python
>>> simple_workflow.__dict__
```
```python
{'workflow_function': <covalent.TransportableObject at 0x7f90e1cfc160>,
 'workflow_function_string': '@ct.lattice(executor="dask")\ndef simple_workflow(a, b):\n    phrase = join_words(a, b)\n    return excitement(phrase)\n\n\n',
 'transport_graph': <covalent._workflow.transport._TransportGraph at 0x7f90e1d11490>,
 'metadata': {'executor': 'dask',
  'results_dir': '/var/home/casey/Agnostiq/code/cova-experiments/results',
  'workflow_executor': 'dask',
  'deps': {},
  'call_before': [],
  'call_after': []},
 '__name__': 'simple_workflow',
 'post_processing': False,
 'args': [],
 'kwargs': {},
 'named_args': {},
 'named_kwargs': {},
 'electron_outputs': {},
 'lattice_imports': 'import builtins as __builtin__\nimport builtins as __builtins__\n# import covalent as ct\nimport time\n',
 'cova_imports': {'ct', 'electron'},
 '__doc__': None}
```
The missing keys are: `__name__`, `workflow_function_string`, `metadata.deps`, `metadata.call_before/after`, `metadata.results_dir`, `post_processing`, `electron_outputs`, `lattice_imports`, `cova_imports`

**Comment by cjao** [comment]
`__name__` and `workflow_function_string` were [previously used](https://github.com/AgnostiqHQ/covalent/blob/develop/covalent_dispatcher/_db/dispatchdb.py#L137-L166) by the UI and could introduce regressions if they are missing.

**Comment by cjao** [comment]
@santoshkumarradha @FyzHsn should this be fixed before release?

**Comment by cjao** [comment]
@mshkanth is your team independently retrieving `lattice.__name__` and `lattice.workflow_function_string` in your data layer?

**Comment by santoshkumarradha** [comment]
@cjao great catch as long as this does not affect UI, this does not matter much for this release. For now, since we are close to release, as this is not a bug, I would probably have this for the next version (if we need).

**Comment by mshkanth** [comment]
> @mshkanth is your team independently retrieving `lattice.__name__` and `lattice.workflow_function_string` in your data layer?

@cjao - We are directly reading from the DB - `lattices.name` and `lattices.function_string_filename`
